# Generated by Django 5.2.17 on 2026-08-18 17:15

import app.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeEvent',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('MATTER_CREATED', 'Teema loodud'), ('MATTER_ASSIGNED', 'Teema määratud'), ('MATTER_VISIBILITY_CHANGED', 'Nähtavus muudetud'), ('MATTER_CLOSED', 'Teema suletud'), ('MATTER_REOPENED', 'Teema taasavatud'), ('DOCUMENT_CREATED', 'Dokument loodud'), ('EVIDENCE_VERSION_ADDED', 'Tõendiversioon lisatud'), ('TAG_ASSIGNED', 'Silt lisatud'), ('TAG_REMOVED', 'Silt eemaldatud'), ('IMPORT_APPLIED', 'Import rakendatud')], db_index=True, max_length=64)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('object_type', models.CharField(blank=True, help_text='app_label.ModelName kirjest, mida sündmus puudutab.', max_length=100)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_events', to=settings.AUTH_USER_MODEL, verbose_name='tegija')),
                ('matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_events', to='matters.matter', verbose_name='teema')),
            ],
            options={
                'verbose_name': 'muudatussündmus',
                'verbose_name_plural': 'muudatussündmused',
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['matter', '-occurred_at'], name='audit_change_matter_time')],
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditEvent',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('BREAK_GLASS_GRANTED', 'Hädaligipääs antud'), ('BREAK_GLASS_REVOKED', 'Hädaligipääs tühistatud'), ('BREAK_GLASS_USED', 'Hädaligipääsu kasutati'), ('RESTRICTED_RECORD_ACCESSED', 'Piiratud kirjet vaadati'), ('DOCUMENT_DOWNLOADED', 'Dokument alla laaditud'), ('EXPORT_GENERATED', 'Väljavõte koostatud'), ('IMPORT_RUN', 'Import käivitatud'), ('ROLE_CHANGED', 'Roll muudetud'), ('AUTHENTICATION_SUCCEEDED', 'Sisselogimine õnnestus'), ('AUTHENTICATION_FAILED', 'Sisselogimine ebaõnnestus')], db_index=True, max_length=64)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('subject_type', models.CharField(blank=True, max_length=100)),
                ('subject_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('succeeded', models.BooleanField(default=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='security_events', to=settings.AUTH_USER_MODEL, verbose_name='tegija')),
            ],
            options={
                'verbose_name': 'turvasündmus',
                'verbose_name_plural': 'turvasündmused',
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['actor', '-occurred_at'], name='audit_security_actor_time')],
            },
        ),
    ]
