# Generated by Django 5.2.17 on 2026-08-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_changeevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityauditevent',
            name='event_type',
            field=models.CharField(choices=[('BREAK_GLASS_GRANTED', 'Hädaligipääs antud'), ('BREAK_GLASS_REVOKED', 'Hädaligipääs tühistatud'), ('BREAK_GLASS_USED', 'Hädaligipääsu kasutati'), ('RESTRICTED_RECORD_ACCESSED', 'Piiratud kirjet vaadati'), ('DOCUMENT_DOWNLOADED', 'Dokument alla laaditud'), ('EXPORT_GENERATED', 'Väljavõte koostatud'), ('IMPORT_RUN', 'Import käivitatud'), ('ROLE_CHANGED', 'Roll muudetud'), ('AUTHENTICATION_SUCCEEDED', 'Sisselogimine õnnestus'), ('AUTHENTICATION_FAILED', 'Sisselogimine ebaõnnestus'), ('SHARED_GATE_PASSED', 'Jagatud parool sisestati'), ('SHARED_GATE_CLOSED', 'Jagatud seanss lõpetati'), ('PERSONA_SELECTED', 'Kasutajavaade valiti')], db_index=True, max_length=64),
        ),
    ]
