"""`ENGAGEMENT_FEEDBACK_CLOSED` joins the `ChangeEvent` vocabulary.

One `AlterField` over a `choices` list, which is Python metadata rather than a
database object: Django emits it because the field's declaration changed, and
PostgreSQL is told nothing it did not already know. The column is a
`varchar(64)` before this migration and a `varchar(64)` after it, so no row is
read, no row is written and no constraint is validated.

**No `RunPython` and no `RunSQL`.** There is no history to rewrite: no event of
this type exists, because nothing could write one until the completion service
in this release did. Re-reading an existing `ENGAGEMENT_CHANGED` row as a
completed consultation would be the application deciding that somebody's
correction was a decision they never made, and `ChangeEvent` is append-only
besides (docs/adr/0085 §6).
"""

# Generated by Django 5.2.17 on 2026-09-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0019_external_position_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeevent',
            name='event_type',
            field=models.CharField(choices=[('MATTER_CREATED', 'Teema loodud'), ('MATTER_ASSIGNED', 'Teema määratud'), ('MATTER_TITLE_CHANGED', 'Pealkiri muudetud'), ('MATTER_STAGE_CHANGED', 'Hetkeseis muudetud'), ('MATTER_TRACK_CHANGED', 'Menetlusliik muudetud'), ('MATTER_ORGANISATION_CHANGED', 'Asutus muudetud'), ('MATTER_DATE_CHANGED', 'Kuupäev muudetud'), ('MATTER_POSITION_UPDATED', 'Seisukohta täiendatud'), ('MATTER_BRIEF_SUMMARY_SET', 'Lühikokkuvõte muudetud'), ('MATTER_POLICY_AREAS_CHANGED', 'Valdkonnad muudetud'), ('MATTER_POLICY_AREA_OTHER_SET', 'Muu valdkond muudetud'), ('MATTER_LEGAL_INSTRUMENTS_CHANGED', 'Õigusakt muudetud'), ('MATTER_LEGAL_INSTRUMENT_OTHER_SET', 'Muu õigusakt muudetud'), ('MATTER_VISIBILITY_CHANGED', 'Nähtavus muudetud'), ('MATTER_DATA_CLASS_CHANGED', 'Andmeklass muudetud'), ('MATTER_CLOSED', 'Teema suletud'), ('MATTER_REOPENED', 'Teema taasavatud'), ('MATTER_PROMOTED', 'Arhiivikirjest aktiivne teema'), ('NEXT_ACTION_SET', 'Järgmiseks määratud'), ('NEXT_ACTION_COMPLETED', 'Järgmiseks tehtud'), ('NEXT_ACTION_CANCELLED', 'Järgmiseks tühistatud'), ('NEXT_ACTION_REVIEWED', 'Järgmiseks üle vaadatud'), ('ENTRY_ADDED', 'Sissekanne lisatud'), ('ENTRY_EDITED', 'Sissekannet muudetud'), ('SUBMISSION_CREATED', 'Arvamus loodud'), ('SUBMISSION_SENT', 'Arvamus välja saadetud'), ('SUBMISSION_WITHDRAWN', 'Arvamus tagasi võetud'), ('SUBMISSION_SUPERSEDED', 'Arvamus asendatud'), ('SUBMISSION_RECIPIENTS_CHANGED', 'Arvamuse saajad muudetud'), ('DOCUMENT_CREATED', 'Dokument loodud'), ('EVIDENCE_VERSION_ADDED', 'Tõendiversioon lisatud'), ('TAG_ASSIGNED', 'Silt lisatud'), ('TAG_REMOVED', 'Silt eemaldatud'), ('IMPORT_APPLIED', 'Import rakendatud'), ('IMPORTANT_DATE_ADDED', 'Oluline tähtaeg lisatud'), ('IMPORTANT_DATE_CHANGED', 'Olulist tähtaega muudetud'), ('IMPORTANT_DATE_CANCELLED', 'Oluline tähtaeg tühistatud'), ('EFFECTIVE_DATE_ADDED', 'Jõustumine lisatud'), ('EFFECTIVE_DATE_CHANGED', 'Jõustumist muudetud'), ('EFFECTIVE_DATE_CANCELLED', 'Jõustumine tühistatud'), ('WORK_VICTORY_PROPOSED', 'Töövõidu kandidaat lisatud'), ('WORK_VICTORY_CHANGED', 'Töövõidu kirjet muudetud'), ('WORK_VICTORY_CONFIRMED', 'Töövõit kinnitatud'), ('WORK_VICTORY_REJECTED', 'Töövõit ei realiseerunud'), ('MATTER_HISTORICAL_CUTOVER_CLOSED', 'Ajalooline kirje: enam mitte jooksev töö'), ('MATTER_REGISTER_CUTOVER_RETIRED', 'Lõpliku registri järgi enam mitte jooksev töö'), ('MATTER_REGISTER_CUTOVER_ACTIVATED', 'Lõpliku registri järgi jooksev töö'), ('MATTER_SOURCE_FIELDS_REFRESHED', 'Väljad uuendatud registri põhjal'), ('ENGAGEMENT_ADDED', 'Kaasamine lisatud'), ('ENGAGEMENT_CHANGED', 'Kaasamist muudetud'), ('ENGAGEMENT_FEEDBACK_CLOSED', 'Kaasamise tagasiside laekunud'), ('MATTER_RELATION_ADDED', 'Teema seotud teise teemaga'), ('MATTER_RELATION_REMOVED', 'Teemade seos eemaldatud'), ('BACKGROUND_MATERIAL_ADDED', 'Taustmaterjal lisatud'), ('BACKGROUND_MATERIAL_REMOVED', 'Taustmaterjal eemaldatud'), ('WEBSITE_OVERVIEW_PLANNED', 'Kodulehe ülevaade plaanis'), ('WEBSITE_OVERVIEW_PUBLISHED', 'Kodulehe ülevaade avaldatud'), ('WEBSITE_OVERVIEW_CANCELLED', 'Kodulehe ülevaade tühistatud'), ('WEBSITE_OVERVIEW_LINK_CORRECTED', 'Kodulehe ülevaate linki või kuupäeva parandatud'), ('EXTERNAL_POSITION_RECORDED', 'Väline seisukoht lisatud'), ('EXTERNAL_POSITION_CORRECTED', 'Välist seisukohta parandatud'), ('EXTERNAL_POSITION_SOURCE_CHANGED', 'Välise seisukoha link muudetud'), ('EXTERNAL_POSITION_DOCUMENT_LINKED', 'Välise seisukoha fail lisatud')], db_index=True, max_length=64),
        ),
    ]
