# Generated by Django 5.2.17 on 2026-10-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0034_document_title_changed_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityauditevent',
            name='event_type',
            field=models.CharField(choices=[('BREAK_GLASS_GRANTED', 'Hädaligipääs antud'), ('BREAK_GLASS_REVOKED', 'Hädaligipääs tühistatud'), ('BREAK_GLASS_USED', 'Hädaligipääsu kasutati'), ('RESTRICTED_RECORD_ACCESSED', 'Piiratud kirjet vaadati'), ('DOCUMENT_DOWNLOADED', 'Dokument alla laaditud'), ('EXPORT_GENERATED', 'Väljavõte koostatud'), ('IMPORT_RUN', 'Import käivitatud'), ('ROLE_CHANGED', 'Roll muudetud'), ('AUTHENTICATION_SUCCEEDED', 'Sisselogimine õnnestus'), ('AUTHENTICATION_FAILED', 'Sisselogimine ebaõnnestus'), ('SHARED_GATE_PASSED', 'Jagatud parool sisestati'), ('SHARED_GATE_CLOSED', 'Jagatud seanss lõpetati'), ('PERSONA_SELECTED', 'Kasutajavaade valiti'), ('SIGNED_OUT', 'Välja logitud'), ('SESSION_ENDED', 'Seanss lõpetati'), ('REAUTHENTICATED', 'Isik kinnitati uuesti'), ('ACCOUNT_CREATED', 'Konto loodud'), ('ACCOUNT_UPDATED', 'Konto andmeid muudeti'), ('ACCOUNT_INVITED', 'Konto kinnitati ja kutsuti'), ('ACCOUNT_INVITATION_CANCELLED', 'Kutse tühistati'), ('ACCOUNT_ACTIVATED', 'Konto aktiveeriti'), ('ACCOUNT_DEACTIVATED', 'Konto lülitati välja'), ('ACCOUNT_REACTIVATED', 'Konto lülitati uuesti sisse'), ('LOGIN_EMAIL_CHANGED', 'Sisselogimise aadress muudeti'), ('EMAIL_EXCEPTION_APPROVED', 'Välise aadressi erand kinnitati'), ('CAPABILITIES_CHANGED', 'Õigused muudeti'), ('ADMINISTRATOR_BOOTSTRAPPED', 'Esimene haldur määrati'), ('PASSWORD_SET', 'Parool seati'), ('PASSWORD_CHANGED', 'Parool muudeti'), ('PASSWORD_RESET_REQUESTED', 'Parooli taastamist taotleti'), ('CREDENTIAL_LINK_ISSUED', 'Ühekordne link väljastati'), ('ACCOUNT_EMAIL_DELIVERY', 'Konto e-kiri'), ('MFA_ENROLLED', 'Teine tegur seadistati'), ('MFA_REMOVED', 'Teine tegur eemaldati'), ('MFA_RECOVERY_CODE_USED', 'Taastekoodi kasutati'), ('MFA_RECOVERY_CODES_REGENERATED', 'Taastekoodid loodi uuesti'), ('ACCESS_REFUSED', 'Turvatundlik toiming keelati')], db_index=True, max_length=64),
        ),
    ]
