# Generated by Django 5.2.17 on 2026-08-18 17:53

import app.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entra_object_id', models.UUIDField(blank=True, help_text='Muutumatu Microsoft Entra ID. Tühi ainult sünteetilistel arenduskasutajatel.', null=True, unique=True, verbose_name='Entra objekti ID')),
                ('upn', models.CharField(max_length=320, unique=True, verbose_name='kasutajanimi (UPN)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-post')),
                ('display_name', models.CharField(max_length=200, verbose_name='kuvatav nimi')),
                ('role', models.CharField(choices=[('SPECIALIST', 'Spetsialist / jurist'), ('DEPARTMENT_HEAD', 'Osakonnajuht'), ('ADMINISTRATOR', 'Süsteemiadministraator'), ('READER', 'Lugeja')], default='SPECIALIST', max_length=32, verbose_name='roll')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktiivne')),
                ('is_staff', models.BooleanField(default=False, help_text='Annab ligipääsu Django haldusliidesele, mitte piiratud sisule.', verbose_name='tehniline haldusligipääs')),
                ('is_synthetic', models.BooleanField(default=False, help_text='Ainult isoleeritud arenduskeskkonnas, mitte päris andmetega keskkonnas.', verbose_name='sünteetiline arenduskasutaja')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='loodud')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'kasutaja',
                'verbose_name_plural': 'kasutajad',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='BreakGlassGrant',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(verbose_name='põhjus')),
                ('starts_at', models.DateTimeField(verbose_name='algab')),
                ('expires_at', models.DateTimeField(verbose_name='lõpeb')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='tühistatud')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='break_glass_grants_given', to=settings.AUTH_USER_MODEL, verbose_name='andis')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='break_glass_grants_revoked', to=settings.AUTH_USER_MODEL, verbose_name='tühistas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_glass_grants', to=settings.AUTH_USER_MODEL, verbose_name='kasutaja')),
            ],
            options={
                'verbose_name': 'hädaligipääs',
                'verbose_name_plural': 'hädaligipääsud',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('entra_object_id__isnull', False), ('is_synthetic', True), _negated=True), name='accounts_user_synthetic_has_no_entra_identity'),
        ),
        migrations.AddConstraint(
            model_name='breakglassgrant',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('starts_at'))), name='accounts_breakglass_expires_after_start'),
        ),
    ]
