# Generated by Django 5.2.17 on 2026-08-21 04:19

import app.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_entra_object_id_immutable'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedGateThrottle',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_key', models.CharField(help_text='Aadressi räsi, mitte aadress ise.', max_length=64, unique=True, verbose_name='kliendi tunnus')),
                ('failures', models.PositiveIntegerField(default=0, verbose_name='ebaõnnestumisi')),
                ('lockout_cycles', models.PositiveIntegerField(default=0, verbose_name='lukustusi')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='lukus kuni')),
                ('last_failure_at', models.DateTimeField(blank=True, null=True, verbose_name='viimane katse')),
            ],
            options={
                'verbose_name': 'jagatud värava piirang',
                'verbose_name_plural': 'jagatud värava piirangud',
                'ordering': ['-last_failure_at'],
            },
        ),
    ]
