# Generated by Django 5.2.17 on 2026-10-08 10:38

import app.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sharedgatethrottle'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCredentialToken',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('ACTIVATION', 'Konto aktiveerimine'), ('PASSWORD_RESET', 'Parooli taastamine')], max_length=32, verbose_name='eesmärk')),
                ('selector', models.CharField(max_length=32, unique=True, verbose_name='valija')),
                ('verifier_digest', models.CharField(max_length=64, verbose_name='kontrollväärtuse räsi')),
                ('expires_at', models.DateTimeField(verbose_name='aegub')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='kasutatud')),
                ('invalidated_at', models.DateTimeField(blank=True, null=True, verbose_name='tühistatud')),
                ('invalidation_reason', models.CharField(blank=True, max_length=64, verbose_name='tühistamise põhjus')),
            ],
            options={
                'verbose_name': 'ühekordne link',
                'verbose_name_plural': 'ühekordsed lingid',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthenticationThrottle',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('SIGN_IN_PAIR', 'Sisselogimine: konto ja võrk'), ('SIGN_IN_ACCOUNT', 'Sisselogimine: konto'), ('SIGN_IN_NETWORK', 'Sisselogimine: võrk'), ('SECOND_FACTOR', 'Teine tegur'), ('REAUTHENTICATION', 'Isiku kinnitamine'), ('CREDENTIAL_LINK', 'Ühekordne link'), ('RESET_REQUEST_ACCOUNT', 'Taastamise taotlus: konto'), ('RESET_REQUEST_NETWORK', 'Taastamise taotlus: võrk'), ('PASSWORD_CHANGE', 'Parooli muutmine')], max_length=32, verbose_name='ulatus')),
                ('key_digest', models.CharField(max_length=64, verbose_name='tunnuse räsi')),
                ('failures', models.PositiveIntegerField(default=0, verbose_name='ebaõnnestumisi')),
                ('lockout_cycles', models.PositiveIntegerField(default=0, verbose_name='lukustusi')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='lukus kuni')),
                ('last_failure_at', models.DateTimeField(blank=True, null=True, verbose_name='viimane katse')),
            ],
            options={
                'verbose_name': 'autentimise piirang',
                'verbose_name_plural': 'autentimise piirangud',
                'ordering': ['-last_failure_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salt', models.CharField(max_length=32, verbose_name='sool')),
                ('code_digest', models.CharField(max_length=64, verbose_name='koodi räsi')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='kasutatud')),
            ],
            options={
                'verbose_name': 'taastekood',
                'verbose_name_plural': 'taastekoodid',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TotpDevice',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encrypted_secret', models.TextField(verbose_name='krüpteeritud saladus')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='kinnitatud')),
                ('last_used_step', models.BigIntegerField(default=0, verbose_name='viimati kasutatud samm')),
            ],
            options={
                'verbose_name': 'autentimisrakendus',
                'verbose_name_plural': 'autentimisrakendused',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='kinnitatud'),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_approved', to=settings.AUTH_USER_MODEL, verbose_name='kinnitas'),
        ),
        migrations.AddField(
            model_name='user',
            name='capability_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Rolli vaikimisi õigustest erinevad load ja keelud. Muudetakse ainult kasutajate halduse kaudu.', verbose_name='isiklikud õigused'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_created', to=settings.AUTH_USER_MODEL, verbose_name='lõi'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_exception_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='välise aadressi erand kinnitatud'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_exception_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_exceptions_approved', to=settings.AUTH_USER_MODEL, verbose_name='välise aadressi erandi kinnitas'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_exception_reason',
            field=models.TextField(blank=True, verbose_name='välise aadressi erandi põhjus'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_authenticated_at',
            field=models.DateTimeField(blank=True, help_text='Ainult isikliku parooliga sisselogimine. Jagatud värava taga kasutaja valimine ei ole sisselogimine ega muuda seda.', null=True, verbose_name='viimane isiklik sisselogimine'),
        ),
        migrations.AddField(
            model_name='user',
            name='local_password_set_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='isiklik parool seatud'),
        ),
        migrations.AddField(
            model_name='user',
            name='provisioning_state',
            field=models.CharField(choices=[('PENDING', 'Ootab kinnitust'), ('INVITED', 'Kutsutud'), ('ACTIVATED', 'Aktiveeritud')], default='ACTIVATED', help_text='Uus konto ootab kinnitust, siis kutset; kasutatavaks teeb selle ainult inimene ise, oma parooli seades.', max_length=16, verbose_name='konto seis'),
        ),
        migrations.AddField(
            model_name='user',
            name='security_epoch',
            field=models.PositiveIntegerField(default=0, verbose_name='turvaversioon'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', True), ('provisioning_state__in', ['PENDING', 'INVITED']), _negated=True), name='accounts_user_unactivated_is_inactive'),
        ),
        migrations.AddField(
            model_name='accountcredentialtoken',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credential_tokens_issued', to=settings.AUTH_USER_MODEL, verbose_name='väljastas'),
        ),
        migrations.AddField(
            model_name='accountcredentialtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credential_tokens', to=settings.AUTH_USER_MODEL, verbose_name='kasutaja'),
        ),
        migrations.AddConstraint(
            model_name='authenticationthrottle',
            constraint=models.UniqueConstraint(fields=('scope', 'key_digest'), name='accounts_auththrottle_scope_key'),
        ),
        migrations.AddField(
            model_name='recoverycode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recovery_codes', to=settings.AUTH_USER_MODEL, verbose_name='kasutaja'),
        ),
        migrations.AddField(
            model_name='totpdevice',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='totp_device', to=settings.AUTH_USER_MODEL, verbose_name='kasutaja'),
        ),
        migrations.AddIndex(
            model_name='accountcredentialtoken',
            index=models.Index(fields=['user', 'purpose'], name='accounts_token_user_purpose'),
        ),
        migrations.AddConstraint(
            model_name='accountcredentialtoken',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='accounts_token_expires_after_issue'),
        ),
    ]
