# Generated by Django 5.2.17 on 2026-08-19 08:00

import app.core.ids
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matters', '0004_entry_revision_append_only'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDocument',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_kind', models.CharField(choices=[('MATTER', 'Teema'), ('ENTRY', 'Sissekanne'), ('SUBMISSION', 'Arvamus')], default='MATTER', max_length=32, verbose_name='allika liik')),
                ('source_object_id', models.UUIDField(blank=True, help_text='Sama mis teema, kui dokument projitseerib teemat ennast.', null=True, verbose_name='allika objekt')),
                ('title', models.TextField(blank=True, verbose_name='pealkiri')),
                ('identifiers', models.TextField(blank=True, help_text='Normaliseeritud viited, mille järgi saab täpselt otsida.', verbose_name='identifikaatorid')),
                ('alias_text', models.TextField(blank=True, help_text='Asutuste, valdkondade ja siltide nimed ning nimekujud.', verbose_name='nimekujud')),
                ('body_text', models.TextField(blank=True, help_text='Tühi 2A etapis; sissekannete ja arvamuste tekst tuleb 2B-s.', verbose_name='sisutekst')),
                ('source_locator', models.CharField(blank=True, help_text='Kust tulemus avaneb, kui allikas ei ole teema ise.', max_length=200, verbose_name='allika asukoht')),
                ('search_estonian', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('search_simple', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('index_version', models.CharField(default='2A.1', editable=False, max_length=16)),
                ('indexed_at', models.DateTimeField(db_index=True, verbose_name='indekseeritud')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_documents', to='matters.matter', verbose_name='teema')),
            ],
            options={
                'verbose_name': 'otsingudokument',
                'verbose_name_plural': 'otsingudokumendid',
                'ordering': ['matter', 'source_kind'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_estonian'], name='search_estonian_gin'), django.contrib.postgres.indexes.GinIndex(fields=['search_simple'], name='search_simple_gin'), django.contrib.postgres.indexes.GinIndex(fields=['title'], name='search_title_trigram', opclasses=['gin_trgm_ops']), django.contrib.postgres.indexes.GinIndex(fields=['identifiers'], name='search_identifiers_trigram', opclasses=['gin_trgm_ops']), models.Index(fields=['matter', 'source_kind'], name='search_matter_kind')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_object_id__isnull', False)), fields=('source_kind', 'source_object_id'), name='search_one_document_per_source_object')],
            },
        ),
    ]
