# Generated by Django 5.2.17 on 2026-08-19 08:24

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0004_entry_revision_append_only'),
        ('search', '0002_search_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdocument',
            name='search_title',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='searchdocument',
            name='index_version',
            field=models.CharField(default='2A.2', editable=False, max_length=16),
        ),
        migrations.AddIndex(
            model_name='searchdocument',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_title'], name='search_title_gin'),
        ),
    ]
