# Generated by Django 5.2.17 on 2026-08-19 13:00

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_derivatives_and_email_provenance'),
        ('matters', '0004_entry_revision_append_only'),
        ('search', '0003_search_title_vector'),
        ('submissions', '0003_structured_recipients'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='searchdocument',
            name='search_title_trigram',
        ),
        migrations.RemoveIndex(
            model_name='searchdocument',
            name='search_identifiers_trigram',
        ),
        migrations.AddField(
            model_name='searchdocument',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_documents', to='documents.document', verbose_name='dokument'),
        ),
        migrations.AddField(
            model_name='searchdocument',
            name='document_version',
            field=models.ForeignKey(blank=True, help_text='Täpne versioon, mille sisu see rida esindab.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_documents', to='documents.documentversion', verbose_name='tõendiversioon'),
        ),
        migrations.AddField(
            model_name='searchdocument',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_documents', to='matters.entry', verbose_name='sissekanne'),
        ),
        migrations.AddField(
            model_name='searchdocument',
            name='fragment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_documents', to='documents.documenttextfragment', verbose_name='tekstiosa'),
        ),
        migrations.AddField(
            model_name='searchdocument',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_documents', to='submissions.submission', verbose_name='arvamus'),
        ),
        migrations.AlterField(
            model_name='searchdocument',
            name='body_text',
            field=models.TextField(blank=True, help_text='Sissekande, arvamuse või dokumendi tekstiosa sisu.', verbose_name='sisutekst'),
        ),
        migrations.AlterField(
            model_name='searchdocument',
            name='index_version',
            field=models.CharField(default='2B.1', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='searchdocument',
            name='source_kind',
            field=models.CharField(choices=[('MATTER', 'Teema'), ('ENTRY', 'Sissekanne'), ('SUBMISSION', 'Arvamus'), ('DOCUMENT_FRAGMENT', 'Dokumendi sisu')], default='MATTER', max_length=32, verbose_name='allika liik'),
        ),
        migrations.AddIndex(
            model_name='searchdocument',
            index=django.contrib.postgres.indexes.GinIndex(condition=models.Q(('source_kind', 'MATTER')), fields=['title'], name='search_title_trigram', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='searchdocument',
            index=django.contrib.postgres.indexes.GinIndex(condition=models.Q(('source_kind', 'MATTER')), fields=['identifiers'], name='search_identifiers_trigram', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='searchdocument',
            index=models.Index(fields=['document_version'], name='search_by_version'),
        ),
    ]
