# Generated by Django 5.2.17 on 2026-08-20 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_import', '0004_historical_corpus'),
        ('search', '0004_child_content_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdocument',
            name='matter_source_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_documents', to='legacy_import.mattersourcepage', verbose_name='ajalooline lähteleht'),
        ),
        migrations.AlterField(
            model_name='searchdocument',
            name='index_version',
            field=models.CharField(default='2D.1', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='searchdocument',
            name='source_kind',
            field=models.CharField(choices=[('MATTER', 'Teema'), ('ENTRY', 'Sissekanne'), ('SUBMISSION', 'Arvamus'), ('DOCUMENT_FRAGMENT', 'Dokumendi sisu'), ('LEGACY_SOURCE_PAGE', "Ajalooline OneNote'i leht")], default='MATTER', max_length=32, verbose_name='allika liik'),
        ),
    ]
