# Generated by Django 5.2.17 on 2026-08-26 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0011_matter_successor'),
        ('search', '0005_historical_source_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdocument',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_documents', to='matters.matterengagement', verbose_name='kaasamine'),
        ),
        migrations.AlterField(
            model_name='searchdocument',
            name='index_version',
            field=models.CharField(default='AUTH003.1', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='searchdocument',
            name='source_kind',
            field=models.CharField(choices=[('MATTER', 'Teema'), ('ENTRY', 'Sissekanne'), ('SUBMISSION', 'Arvamus'), ('DOCUMENT_FRAGMENT', 'Dokumendi sisu'), ('LEGACY_SOURCE_PAGE', "Ajalooline OneNote'i leht"), ('ENGAGEMENT', 'Kaasamine')], default='MATTER', max_length=32, verbose_name='allika liik'),
        ),
    ]
