"""`Märge` and `Arvamus / tagasiside` become things the corpus can hold.

Two nullable foreign keys and nothing else. Additive, reversible, and with no
backfill: the columns are how a projection row points at the record it
projects, and the rows themselves are written by the indexer, never by a
migration guessing at content.

**Why they were missing.** The indexer was built around `Entry`, and the
composer simplification made `+ Märge` write a `MatterProceduralDevelopment`
instead. Nothing bridged the two, so every note a lawyer wrote after that
change was absent from search while the seeded legacy entries went on matching
— search answering against a capture model the product had left behind.
`MatterExternalPosition` had never been indexed at all, which also made a body
known to a Matter only through its feedback unfindable (QA-003, QA-020).

**`INDEX_VERSION` moves to `TEEMA.1`** in the same change. The default on the
column alters; no stored row is rewritten. Rows built before this hold neither
kind, so a deployment that has not rebuilt still answers against the older
projection — and a fail-closed version is how `check_search_integrity` says so
out loud rather than leaving it to be discovered. A production rebuild is
required after deployment.

`ARCHIVE_INDEX_VERSION` is untouched. The archive's projection did not change.
"""

# Generated by Django 5.2.17 on 2026-09-21 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0034_timeline_step"),
        ("search", "0008_opinion_summary_index_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchdocument",
            name="development",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_documents",
                to="matters.matterproceduraldevelopment",
                verbose_name="märge",
            ),
        ),
        migrations.AddField(
            model_name="searchdocument",
            name="external_position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_documents",
                to="matters.matterexternalposition",
                verbose_name="arvamus või tagasiside",
            ),
        ),
        migrations.AlterField(
            model_name="searchdocument",
            name="index_version",
            field=models.CharField(default="TEEMA.1", editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name="searchdocument",
            name="source_kind",
            field=models.CharField(
                choices=[
                    ("MATTER", "Teema"),
                    ("ENTRY", "Sissekanne"),
                    ("SUBMISSION", "Arvamus"),
                    ("DOCUMENT_FRAGMENT", "Dokumendi sisu"),
                    ("LEGACY_SOURCE_PAGE", "Ajalooline OneNote'i leht"),
                    ("ENGAGEMENT", "Kaasamine"),
                    ("PROCEDURAL_DEVELOPMENT", "Märge"),
                    ("EXTERNAL_POSITION", "Arvamus või tagasiside"),
                ],
                default="MATTER",
                max_length=32,
                verbose_name="allika liik",
            ),
        ),
    ]
