"""Synthetic register workbooks, generated by the tests that use them.

No real workbook ever enters CI, and no ``.xlsx`` is committed at all — the
repository ignores the extension outright, so a checked-in workbook could only
be a real one that arrived by accident. These builders produce a file with the
same *shape* as the real register and none of its content.

Every name and title here is invented. The eras, the column moves, the
pre-numbering and the anomalies are real, because those are what the parser has
to survive; the matters are not.
"""

from __future__ import annotations

import datetime as dt
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from openpyxl import Workbook
from openpyxl.worksheet.hyperlink import Hyperlink

from app.workflow.vocabulary import RAW_LABEL_TO_DISPOSITION, RAW_LABEL_TO_STAGE

#: Column layouts, matching the reviewed era contracts exactly. Kept here rather
#: than derived from the contracts so that a contract edited by mistake shows up
#: as a test failure instead of being silently agreed with.
HEADERS_2011 = [
    "NR",
    "TEEMA",
    "ÕIGUSAKT",
    "SISSE",
    "ARVAMUSE TÄHTAEG",
    "VÄLJA",
    "KELLELT",
    "VASTUTAJA",
]
FEEDBACK_HEADERS = [
    "LIIKMETE ARV, KES ANDSID TAGASISIDET",
    "LIIKMETE ARV, KELLELT OTSE KÜSISIME TAGASISIDET",
]
HEADERS_2018 = [*HEADERS_2011, *FEEDBACK_HEADERS]
HEADERS_2020 = [
    "NR",
    "TEEMA",
    "ÕIGUSAKT",
    "SISSE",
    "ARVAMUSE TÄHTAEG",
    "VÄLJA",
    "KELLELE",
    "VASTUTAJA",
    *FEEDBACK_HEADERS,
]
HEADERS_2023 = [*HEADERS_2020, "HETKESEIS"]
HEADERS_2025 = [*HEADERS_2023, "JÄRGMISEKS"]

HEADERS_BY_YEAR: dict[int, list[str]] = {
    **dict.fromkeys(range(2011, 2018), HEADERS_2011),
    2018: HEADERS_2018,
    2019: HEADERS_2018,
    2020: HEADERS_2020,
    2021: HEADERS_2020,
    2022: HEADERS_2020,
    2023: HEADERS_2023,
    2024: HEADERS_2023,
    2025: HEADERS_2025,
    2026: HEADERS_2025,
}

ONENOTE_LINK = "onenote:https://example.invalid/Notebook/Section#Page&section-id=synthetic"


@dataclass
class Row:
    """One synthetic register row. ``None`` is a blank cell, and it stays blank."""

    reference: str | None = None
    title: str | None = None
    instrument: str | None = None
    received: Any = None
    deadline: Any = None
    sent: Any = None
    counterparty: str | None = None
    owner: str | None = None
    responded: Any = None
    requested: Any = None
    status: str | None = None
    next_action: str | None = None
    extra: Any = None
    hyperlink: str | None = None

    def cells(self, year: int) -> list[Any]:
        values: list[Any] = [
            self.reference,
            self.title,
            self.instrument,
            self.received,
            self.deadline,
            self.sent,
            self.counterparty,
            self.owner,
        ]
        if year >= 2018:
            values += [self.responded, self.requested]
        if year == 2022:
            values.append(self.extra)
        if year >= 2023:
            values.append(self.status)
        if year >= 2025:
            values.append(self.next_action)
        return values


@dataclass
class Sheet:
    year: int
    rows: list[Row] = field(default_factory=list)


def _headers_for(year: int) -> list[str]:
    headers = list(HEADERS_BY_YEAR[year])
    if year == 2022:
        # The unlabelled column the real 2022 sheet carries. Its position
        # matters; its meaning is not established and must stay that way.
        headers = [*HEADERS_2020, ""]
    return headers


def write_workbook(path: Path, sheets: list[Sheet], *, vocabulary: bool = True) -> Path:
    """Write a workbook laid out like the register. Returns the path."""
    workbook = Workbook()
    workbook.remove(workbook.active)

    for sheet in sorted(sheets, key=lambda s: -s.year):
        worksheet = workbook.create_sheet(title=str(sheet.year))
        header_row = 1
        if sheet.year == 2021:
            # The 2021 sheet really does put a title above its headers.
            worksheet.append([f"Tööd eelnõudega {sheet.year}"])
            header_row = 2
        worksheet.append(_headers_for(sheet.year))

        for offset, row in enumerate(sheet.rows):
            worksheet.append(row.cells(sheet.year))
            if row.hyperlink:
                cell = worksheet.cell(row=header_row + 1 + offset, column=2)
                cell.hyperlink = Hyperlink(ref=cell.coordinate, target=row.hyperlink)

    if vocabulary:
        reference = workbook.create_sheet(title="Hetkeseisu info")
        reference.append(["HETKESEISU ETAPP", "SELGITUS"])
        for label in [*RAW_LABEL_TO_STAGE, *RAW_LABEL_TO_DISPOSITION]:
            reference.append([label, f"Sünteetiline selgitus: {label}."])

    path.parent.mkdir(parents=True, exist_ok=True)
    workbook.save(path)
    workbook.close()
    return path


# --------------------------------------------------------------------------
# The corpus the acceptance scenarios use. One row per thing that can go wrong.
# --------------------------------------------------------------------------


def era_corpus() -> list[Sheet]:
    """One sheet per era boundary, each carrying its era's characteristic rows."""
    return [
        Sheet(
            2011,
            [
                Row(
                    reference="2011_1",
                    title="Sünteetiline määruse eelnõu õppeotstarbeks",
                    instrument="M",
                    # Pre-2020 sheets store dates as serial numbers typed as text.
                    received="40543",
                    deadline="40547",
                    counterparty="Näidisministeerium",
                    owner="Kadri",
                ),
                Row(),  # blank padding, counted separately
            ],
        ),
        Sheet(
            2017,
            [
                Row(
                    reference="2017_1",
                    title="Sünteetiline veoteenuste seaduse eelnõu",
                    instrument="VTK",
                    received=dt.datetime(2016, 12, 23),
                    deadline=dt.datetime(2017, 1, 13),
                    sent=dt.datetime(2017, 1, 13),
                    counterparty="Näidisministeerium",
                    owner="Kadri",
                ),
            ],
        ),
        Sheet(
            2018,
            [
                Row(
                    reference="2018_1",
                    title="Sünteetiline tarbijakaitse direktiiv",
                    instrument="direktiiv",
                    received=dt.datetime(2017, 12, 13),
                    deadline=dt.datetime(2018, 1, 31),
                    counterparty="Näidisministeerium",
                    owner="Kadri",
                    responded=0,  # a measured zero
                    requested=None,  # blank: not the same fact
                ),
            ],
        ),
        Sheet(
            2020,
            [
                Row(
                    reference="2020_1",
                    title="Sünteetiline maksukorralduse VTK",
                    instrument="VTK",
                    received=dt.datetime(2019, 12, 5),
                    deadline=dt.datetime(2020, 1, 20),
                    counterparty="Näidisamet",
                    owner="Kadri",
                    responded=15,
                    requested=178,
                ),
            ],
        ),
        Sheet(
            2021,
            [
                Row(
                    reference="2021_1",
                    title="Sünteetiline sundkoormiste korraldus",
                    instrument="korraldus",
                    received=dt.datetime(2020, 11, 30),
                    deadline=dt.datetime(2021, 1, 4),
                    counterparty="Näidisamet",
                    owner="Kadri",
                    # More answered than were asked directly. Legitimate.
                    responded=9,
                    requested=3,
                ),
            ],
        ),
        Sheet(
            2022,
            [
                Row(
                    reference="2022_1",
                    title="Sünteetiline välisinvesteeringute seadus",
                    instrument="seadus",
                    received=dt.datetime(2021, 12, 13),
                    deadline=dt.datetime(2022, 1, 3),
                    counterparty="Näidisamet",
                    owner="Kadri",
                    extra="X",  # unlabelled column, meaning unknown
                ),
            ],
        ),
        Sheet(
            2023,
            [
                Row(
                    reference="2023_1",
                    title="Sünteetiline üüriteenuste määrus",
                    instrument="EL määrus",
                    received=dt.datetime(2022, 11, 10),
                    deadline=dt.datetime(2023, 1, 5),
                    counterparty="Näidisamet",
                    owner="Kadri",
                    status="",  # sparse use is the era's characteristic
                ),
            ],
        ),
        Sheet(
            2024,
            [
                Row(
                    reference="2024_1",
                    title="Sünteetiline raamatupidamise seadus",
                    instrument="seadus",
                    received=dt.datetime(2023, 12, 14),
                    deadline=dt.datetime(2024, 1, 15),
                    counterparty="Näidisministeerium",
                    owner="Kadri",
                    # Free text outside the controlled vocabulary. Never mapped.
                    status="Riigikogus 2. lugemisel",
                ),
                Row(
                    reference="2024_2",
                    title="Sünteetiline vigase kuupäevaga rida",
                    instrument="muu",
                    received="mitte kuupäev",
                    deadline=dt.datetime(2024, 2, 1),
                    counterparty="Näidisministeerium",
                    owner="Kadri",
                ),
            ],
        ),
        Sheet(
            2025,
            [
                Row(
                    reference="2025_1",
                    title="Sünteetiline küberturvalisuse seadus",
                    instrument="seadus",
                    received=dt.datetime(2024, 12, 9),
                    # Deadline before arrival. Real, and never clamped.
                    deadline=dt.datetime(2024, 12, 1),
                    counterparty="Näidisministeerium",
                    owner="Kadri",
                    status="jõustunud",
                    next_action="Ootan eelnõud 2027. aasta 2. kvartalis.",
                ),
                Row(
                    reference="2025_2",
                    title="Sünteetiline lõpetatud teema",
                    instrument="muu",
                    received=dt.datetime(2024, 11, 1),
                    counterparty="Näidisministeerium",
                    owner="Kadri",
                    status="rohkem pole tegevusi plaanis",
                ),
            ],
        ),
        Sheet(
            2026,
            [
                Row(
                    reference="2026_1",
                    title="Sünteetiline avaliku teabe seaduse eelnõu",
                    instrument="seadus",
                    received=dt.datetime(2025, 12, 18),
                    deadline=dt.datetime(2026, 1, 15),
                    sent=dt.datetime(2026, 1, 15),
                    counterparty="Näidisministeerium",
                    owner="Kadri",
                    responded=0,
                    requested=0,
                    status="kooskõlastusringil",
                    next_action="vaata 01.09.2026 üle, 07.08.2026 seisuga",
                    hyperlink=ONENOTE_LINK,
                ),
                Row(
                    reference="2026_2",
                    title="Sünteetiline tundmatu vastutajaga teema",
                    instrument="määrus",
                    received=dt.datetime(2026, 1, 2),
                    counterparty="Tundmatu Näidisasutus",
                    owner="Keegi Tundmatu",
                    status="valitsuses",
                    next_action="Räägime läbi ja vaatame, mis edasi saab.",
                ),
                # Reserved numbers: the register pre-numbers ahead of use.
                Row(reference="2026_3"),
                Row(reference="2026_4"),
            ],
        ),
    ]


def duplicate_reference_corpus() -> list[Sheet]:
    return [
        Sheet(
            2026,
            [
                Row(reference="2026_1", title="Sünteetiline esimene", owner="Kadri"),
                Row(reference="2026_1", title="Sünteetiline teine", owner="Kadri"),
                Row(reference="mitte viide", title="Sünteetiline vigase viitega", owner="Kadri"),
            ],
        )
    ]


def pre_numbered_corpus(*, filled: int = 2, reserved_to: int = 300) -> list[Sheet]:
    """A 2026 sheet numbered to ``reserved_to`` with only ``filled`` rows used."""
    rows = [
        Row(
            reference=f"2026_{number}",
            title=f"Sünteetiline teema {number}",
            received=dt.datetime(2026, 1, number % 28 + 1),
            counterparty="Näidisministeerium",
            owner="Kadri",
            status="kooskõlastusringil",
        )
        for number in range(1, filled + 1)
    ]
    rows += [Row(reference=f"2026_{number}") for number in range(filled + 1, reserved_to + 1)]
    return [Sheet(2026, rows)]
