"""The repository must not be able to carry real source material.

At the time Stage 2A was built, GitHub reported ``Kauror/juristid`` as **public**.
Even if that changes, real workbooks and the row-level reports derived from them
do not belong in Git — a private repository is a smaller audience, not a
different rule.

These tests are cheap and boring and they check the thing that would be
catastrophic and silent: a workbook, or a report full of matter titles and
colleagues' names, committed by an ``git add -A`` on a tired evening.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest
from django.conf import settings

from app.legacy_import.reporting import AGGREGATE_REPORTS, ROW_LEVEL_REPORTS

REPOSITORY = Path(settings.BASE_DIR)

#: Directories an operator is told to use for real material. Every one of them
#: must be ignored, and the tests below prove it rather than trusting the
#: .gitignore to be read.
LOCAL_ONLY_DIRECTORIES = (
    "private-data",
    "import-input",
    "import-output",
    # Stage 2H's reconciliation output. The row-level report names matters,
    # ministries and archive filenames.
    ".local",
    "opinion-archive",
)


def _git(*arguments: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(  # noqa: S603
        ["git", *arguments],  # noqa: S607
        cwd=REPOSITORY,
        capture_output=True,
        text=True,
        check=False,
    )


def _is_git_repository() -> bool:
    return (REPOSITORY / ".git").exists() and _git("rev-parse", "--git-dir").returncode == 0


requires_git = pytest.mark.skipif(
    not _is_git_repository(), reason="not a git checkout (CI containers, sdists)"
)


@requires_git
@pytest.mark.parametrize("directory", LOCAL_ONLY_DIRECTORIES)
def test_local_data_directories_are_ignored(directory: str) -> None:
    result = _git("check-ignore", "-q", f"{directory}/anything.txt")
    assert result.returncode == 0, f"{directory}/ is not ignored by .gitignore"


@requires_git
@pytest.mark.parametrize("extension", ["xlsx", "xlsm", "xls"])
def test_no_workbook_can_be_committed_from_anywhere(extension: str) -> None:
    """Blanket, not path-scoped.

    The synthetic fixtures are generated by the tests that use them, so a
    checked-in workbook could only be a real one that arrived by accident.
    """
    for candidate in (f"anywhere.{extension}", f"tests/fixtures/sample.{extension}"):
        assert _git("check-ignore", "-q", candidate).returncode == 0, candidate


@requires_git
def test_no_workbook_is_currently_tracked() -> None:
    tracked = _git("ls-files").stdout.splitlines()
    offenders = [path for path in tracked if path.lower().endswith((".xlsx", ".xlsm", ".xls"))]
    assert offenders == [], f"real source material is tracked: {offenders}"


@requires_git
def test_no_import_report_is_currently_tracked() -> None:
    tracked = _git("ls-files").stdout.splitlines()
    offenders = [
        path
        for path in tracked
        if any(path.startswith(f"{directory}/") for directory in LOCAL_ONLY_DIRECTORIES)
    ]
    assert offenders == [], f"import material is tracked: {offenders}"


def test_the_report_classes_do_not_overlap() -> None:
    """A file is publishable or it is not. There is no third state."""
    assert not set(AGGREGATE_REPORTS) & set(ROW_LEVEL_REPORTS)


def test_only_summaries_are_classified_as_publishable() -> None:
    """The separation is physical, so it cannot be got wrong under pressure."""
    assert set(AGGREGATE_REPORTS) == {"summary.json", "summary.md"}


def test_the_aggregate_summary_carries_no_source_content(tmp_path: Path) -> None:
    """The load-bearing claim: summary.json is safe to attach to anything."""
    import json

    from app.legacy_import.inspection import build_summary, inspect_workbook
    from tests.synthetic_register import Row, Sheet, write_workbook

    unique_title = "Kordumatu pealkiri mida koondaruandes olla ei tohi"
    path = write_workbook(
        tmp_path / "synthetic.xlsx",
        [
            Sheet(
                2026,
                [
                    Row(
                        reference="2026_1",
                        title=unique_title,
                        counterparty="Kordumatu asutus",
                        owner="Kordumatu inimene",
                        next_action="Kordumatu järgmine tegevus",
                        hyperlink="onenote:https://example.invalid/kordumatu",
                    )
                ],
            )
        ],
    )
    summary = json.dumps(build_summary(inspect_workbook(path)), ensure_ascii=False)

    for forbidden in (
        unique_title,
        "Kordumatu asutus",
        "Kordumatu inimene",
        "Kordumatu järgmine tegevus",
        "example.invalid",
    ):
        assert forbidden not in summary, f"{forbidden!r} leaked into the aggregate summary"


def test_the_row_level_report_does_contain_source_content(tmp_path: Path) -> None:
    """Stated as a test so the split is deliberate rather than accidental.

    These files are useful precisely because they reproduce the source. That is
    why they stay in ignored local storage and are never uploaded.
    """
    from app.legacy_import.inspection import inspect_workbook, write_inspection_reports
    from tests.synthetic_register import Row, Sheet, write_workbook

    title = "Kordumatu pealkiri reafailis"
    path = write_workbook(
        tmp_path / "synthetic.xlsx",
        [Sheet(2026, [Row(reference="2026_1", title=title, owner="Kadri")])],
    )
    written = write_inspection_reports(inspect_workbook(path), tmp_path / "reports")

    rows = next(report for report in written.row_level if report.name == "rows.csv")
    assert title in rows.read_text(encoding="utf-8-sig")


# --------------------------------------------------------------------------
# Secrets
#
# The shared gate's password is a host-side secret and the repository is public.
# A committed shared password is a published one, and unlike a leaked workbook
# it would not look wrong in a diff — it would look like a default
# (Stage-2D auth brief 2, 13; docs/adr/0016).
# --------------------------------------------------------------------------

#: Files that legitimately talk *about* secrets: templates, documentation and
#: the tests below. They are allowed to name the variables; they may not carry
#: a value.
_SECRET_NAMES = (
    "JURISTID_SHARED_GATE_PASSWORD",
    "DJANGO_SECRET_KEY",
    "POSTGRES_PASSWORD",
    "DEV_LOGIN_PIN",
)

#: Values a template is allowed to assign. Anything else assigned to one of the
#: names above is a value somebody meant to keep.
_PLACEHOLDER_PREFIXES = ("", "replace-me", "${", "$(", "changeme", "unknown")


def _tracked_files() -> list[str]:
    result = _git("ls-files")
    assert result.returncode == 0, result.stderr
    return [line for line in result.stdout.splitlines() if line]


@requires_git
def test_no_tracked_file_assigns_a_secret_a_real_value() -> None:
    offenders: list[str] = []
    for relative in _tracked_files():
        path = REPOSITORY / relative
        if path.suffix in {".png", ".ico", ".woff2", ".lock"} or not path.is_file():
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        for number, line in enumerate(text.splitlines(), start=1):
            stripped = line.strip()
            if stripped.startswith("#"):
                continue
            for name in _SECRET_NAMES:
                marker = f"{name}="
                if marker not in stripped:
                    continue
                value = stripped.split(marker, 1)[1].strip().strip("\"'")
                if value.lower().startswith(_PLACEHOLDER_PREFIXES):
                    continue
                offenders.append(f"{relative}:{number} {name}")
    assert not offenders, "a real-looking secret is committed: " + ", ".join(offenders)


@requires_git
def test_the_shared_gate_password_is_never_a_compose_or_dockerfile_default() -> None:
    """Not a default anywhere an image or a stack would inherit it."""
    for relative in _tracked_files():
        if not (relative.endswith((".yml", ".yaml")) or relative.endswith("Dockerfile")):
            continue
        text = (REPOSITORY / relative).read_text(encoding="utf-8")
        assert "JURISTID_SHARED_GATE_PASSWORD" not in text, relative


@requires_git
def test_the_environment_file_pattern_is_ignored() -> None:
    """`*.env` and the server's own file, so a copied one cannot be added."""
    for candidate in ("juristid.env", "server.env", "deploy/unraid-main/juristid.env"):
        result = _git("check-ignore", "-q", candidate)
        assert result.returncode == 0, f"{candidate} is not ignored"


@requires_git
def test_the_historical_corpus_directories_are_ignored() -> None:
    for candidate in (
        "onenote-desktop-archive/pages/x/page.json",
        "onenote-juristid-export/anything",
        "migration-audit/reports/reconciliation/exact-matches.csv",
        "legacy-source/page.xml",
    ):
        result = _git("check-ignore", "-q", candidate)
        assert result.returncode == 0, f"{candidate} is not ignored"


@requires_git
def test_a_database_dump_cannot_be_committed() -> None:
    for candidate in ("juristid.sql", "backup.sql.gz", "juristid-main.dump"):
        result = _git("check-ignore", "-q", candidate)
        assert result.returncode == 0, f"{candidate} is not ignored"


# ---------------------------------------------------------------------------
# The visual-regression baselines
#
# `*.png` is excluded for a stated reason: a screenshot of the real deployment
# is real data in an image, and no reviewer of a diff would think to look at
# it. `e2e/baselines/` is the one exception, and it is safe only for as long as
# those files can come from nowhere but the browser job — which runs against
# the synthetic seed with REAL_DATA_ALLOWED off, on a command that refuses to
# run anywhere real data is permitted.
#
# The exception is therefore fenced here rather than trusted: the directory
# must stay the only one, it must hold nothing but the suite's own scenarios,
# and the command that fills it must keep its refusal.
# ---------------------------------------------------------------------------

BASELINE_DIRECTORY = REPOSITORY / "e2e" / "baselines"


@requires_git
def test_the_png_exception_is_scoped_to_the_baseline_directory() -> None:
    """No blanket `!*.png`, now or later.

    A repository-wide exception would put every screenshot anybody ever drops
    into the tree one `git add` away from being committed.
    """
    ignore = (REPOSITORY / ".gitignore").read_text(encoding="utf-8").splitlines()
    negations = [line.strip() for line in ignore if line.strip().startswith("!")]
    png_negations = [line for line in negations if line.endswith(".png")]
    assert sorted(png_negations) == ["!e2e/baselines/*.png", "!static/**/*.png"], png_negations


@requires_git
def test_a_screenshot_outside_the_baseline_directory_cannot_be_committed() -> None:
    """The rule the exception must not have widened."""
    stray = REPOSITORY / "artifacts" / "stray-screenshot.png"
    assert _git("check-ignore", "-q", str(stray)).returncode == 0


@requires_git
def test_every_committed_baseline_belongs_to_a_scenario_in_the_suite() -> None:
    """The directory is a suite's baselines, not a screenshot dumping ground.

    A file nothing compares against is a file nobody reviews, which is exactly
    where an unreviewed screenshot would come to rest.
    """
    tracked = _git("ls-files", "e2e/baselines").stdout.split()
    assert tracked, "the visual suite has no committed baselines"

    suite = (REPOSITORY / "e2e" / "test_ui_regression.py").read_text(encoding="utf-8")
    for path in tracked:
        assert path.endswith(".png"), path
        name = Path(path).stem
        # `shell-1440` and friends are produced by one parametrised scenario.
        stem = name.rsplit("-", 1)[0] if name.rsplit("-", 1)[-1].isdigit() else name
        assert f'"{stem}' in suite or f"'{stem}" in suite, (
            f"{path} matches no scenario in the visual suite"
        )


def test_the_seed_the_baselines_come_from_refuses_real_data() -> None:
    """The whole exception rests on this refusal, so it is asserted here too.

    `tests/test_seed_data.py` owns the command's behaviour; this states the
    dependency, so that removing the guard breaks the test that explains why
    the baselines are allowed in the repository at all.
    """
    source = (
        REPOSITORY / "app" / "core" / "management" / "commands" / "seed_e2e_data.py"
    ).read_text(encoding="utf-8")
    assert "if settings.REAL_DATA_ALLOWED:" in source
    assert "CommandError" in source
