# Generated by Django 5.2.17 on 2026-08-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_structured_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='sent_at_precision',
            field=models.CharField(choices=[('TIMESTAMP', 'Kuupäev ja kellaaeg'), ('DATE', 'Ainult kuupäev')], default='TIMESTAMP', max_length=16, verbose_name='kuupäeva täpsus'),
        ),
    ]
