"""Two additive tables: an opinion's own `Märksõnad`, and its `Ülevaade / uudis` links.

**Purely additive, and deliberately so.** Two `CreateModel`, two `AddField` for
the `ManyToManyField` declarations that describe them — a `through` M2M adds no
column of its own — and two `AddConstraint` for the uniqueness each join needs.
No column is altered, no index is dropped, no row is read and no row is written.
The reverse is dropping two empty tables.

**No backfill, and that is the decision rather than an omission** (docs/adr/0093
§1, §2). Every `Submission` in the register starts with zero keywords and zero
linked write-ups, and goes on carrying zero until somebody opens the opinion and
chooses. Copying the Matter's tags onto its opinions would manufacture, on every
historical letter, a classification nobody made; deriving a link from a matching
URL, title, date or chronological proximity would put a statement on the file
that nobody stated.

**`tag` is `PROTECT` and both link sides are `CASCADE`.** A governed vocabulary
row something is classified by must not vanish under it, which is the rule
`matters.TagAssignment` already keeps. Both endpoints of the link already cascade
from their `Matter`, so a `PROTECT` on either would make deleting a Matter fail on
a metadata row — and unlinking, which deletes neither endpoint, is what the
service performs.
"""

# Generated by Django 5.2.17 on 2026-09-19 03:28

import app.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0030_procedural_development'),
        ('submissions', '0006_document_reparent_evidence_integrity'),
        ('taxonomy', '0008_lawyer_reviewed_legal_instruments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionTagAssignment',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='lisatud')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_submission_tags', to=settings.AUTH_USER_MODEL, verbose_name='lisas')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='submissions.submission', verbose_name='arvamus')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_assignments', to='taxonomy.tag', verbose_name='märksõna')),
            ],
            options={
                'verbose_name': 'arvamuse märksõna',
                'verbose_name_plural': 'arvamuse märksõnad',
                'ordering': ['tag__name_et'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='submissions', through='submissions.SubmissionTagAssignment', to='taxonomy.tag', verbose_name='märksõnad'),
        ),
        migrations.CreateModel(
            name='SubmissionWebsiteOverviewLink',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_at', models.DateTimeField(blank=True, null=True, verbose_name='seotud')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked_submission_overviews', to=settings.AUTH_USER_MODEL, verbose_name='sidus')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_overview_links', to='submissions.submission', verbose_name='arvamus')),
                ('website_overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_links', to='matters.matterwebsiteoverview', verbose_name='ülevaade / uudis')),
            ],
            options={
                'verbose_name': 'arvamuse seos ülevaatega',
                'verbose_name_plural': 'arvamuse seosed ülevaadetega',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='website_overviews',
            field=models.ManyToManyField(blank=True, related_name='submissions', through='submissions.SubmissionWebsiteOverviewLink', to='matters.matterwebsiteoverview', verbose_name='seotud ülevaated / uudised'),
        ),
        migrations.AddConstraint(
            model_name='submissiontagassignment',
            constraint=models.UniqueConstraint(fields=('submission', 'tag'), name='submissions_unique_tag_per_submission'),
        ),
        migrations.AddConstraint(
            model_name='submissionwebsiteoverviewlink',
            constraint=models.UniqueConstraint(fields=('submission', 'website_overview'), name='submissions_unique_overview_link'),
        ),
    ]
