# Generated by Django 5.2.17 on 2026-08-18 17:15

import app.core.ids
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StageVocabulary',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=64, unique=True, verbose_name='võti')),
                ('label_et', models.CharField(max_length=200, verbose_name='nimetus')),
                ('help_text', models.TextField(blank=True, verbose_name='selgitus')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktiivne')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='järjekord')),
                ('applicable_tracks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('DOMESTIC', 'Riigisisene'), ('EU_INITIATIVE', 'ELi algatus'), ('NATIONAL_TRANSPOSITION', 'ELi õiguse ülevõtmine'), ('STRATEGY', 'Strateegia või arengukava'), ('KODA_INITIATIVE', 'Koja algatus'), ('IMPLEMENTATION', 'Rakendamine või järelevalve'), ('OTHER', 'Muu')], max_length=32), blank=True, default=list, help_text='Tühi loend tähendab, et etapp kehtib kõikidele menetlusliikidele.', size=None, verbose_name='kehtib menetlusliikidele')),
                ('is_provisional', models.BooleanField(default=False, help_text='Märgitud seni, kuni osakonnajuht ja juristid on etapisõnastiku üle vaadanud.', verbose_name='esialgne')),
            ],
            options={
                'verbose_name': 'menetlusetapp',
                'verbose_name_plural': 'menetlusetapid',
                'ordering': ['sort_order', 'label_et'],
            },
        ),
        migrations.CreateModel(
            name='LegacyStatusMapping',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_label', models.CharField(help_text='Täpselt nii, nagu see töövihikus esineb.', max_length=200, unique=True, verbose_name='algne väärtus')),
                ('disposition', models.CharField(blank=True, choices=[('COMPLETED', 'Lõpetatud või jõustunud'), ('SUPERSEDED', 'Asendatud järgnenud teemaga'), ('INITIATIVE_WITHDRAWN', 'Algataja loobus'), ('MONITORING_STOPPED', 'Koda lõpetas jälgimise'), ('NO_POSITION_FORMED', 'Seisukohta ei kujundatud'), ('RESPONSE_COMPLETE', 'Vastus esitatud ja järeltegevus tehtud'), ('DUPLICATE', 'Duplikaat või liidetud'), ('OTHER', 'Muu')], default='', max_length=32, verbose_name='vastav lõpetamise põhjus')),
                ('source_era', models.CharField(blank=True, help_text='Näiteks 2023-2024 või 2025, kui tähendus on aastati erinev.', max_length=32, verbose_name='allika periood')),
                ('reviewed_by', models.CharField(blank=True, max_length=200, verbose_name='üle vaadanud')),
                ('notes', models.TextField(blank=True, verbose_name='märkused')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_labels', to='workflow.stagevocabulary', verbose_name='vastav etapp')),
            ],
            options={
                'verbose_name': 'ajaloolise seisundi vaste',
                'verbose_name_plural': 'ajalooliste seisundite vasted',
                'ordering': ['raw_label'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('stage__isnull', False), _negated=True), ('disposition', ''), _connector='OR'), name='workflow_legacy_status_single_interpretation')],
            },
        ),
    ]
