"""`PLANNED` next actions: several dated future actions behind the current one (docs/adr/0143).

One new `NextAction.status` value and one check. `OPEN` keeps meaning the
Matter's one current action — `workflow_one_open_action_per_matter` is
unchanged — and `PLANNED` rows are queued future work, which must be dated
(`workflow_planned_action_is_dated`). The status vocabulary check is recreated
with the new value. Every existing row keeps its status: the open action of a
Matter stays its current action, no row is rewritten and nothing is backfilled.
The revision still serving between `migrate` and the swap never writes
`PLANNED`, so both checks hold for everything it inserts. Reversible while no
`PLANNED` row exists.
"""

# Generated by Django 5.2.17 on 2026-10-06 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0046_save_once_and_plan_fulfilment'),
        ('workflow', '0012_save_once_and_plan_fulfilment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nextaction',
            name='workflow_next_action_status_vocabulary',
        ),
        migrations.AlterField(
            model_name='nextaction',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Kehtiv'), ('PLANNED', 'Planeeritud'), ('COMPLETED', 'Tehtud'), ('CANCELLED', 'Tühistatud'), ('SUPERSEDED', 'Asendatud')], db_index=True, default='OPEN', max_length=16, verbose_name='olek'),
        ),
        migrations.AddConstraint(
            model_name='nextaction',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'PLANNED', 'COMPLETED', 'CANCELLED', 'SUPERSEDED'])), name='workflow_next_action_status_vocabulary'),
        ),
        migrations.AddConstraint(
            model_name='nextaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PLANNED'), _negated=True), ('target_date__isnull', False), _connector='OR'), name='workflow_planned_action_is_dated'),
        ),
    ]
