# Generated by Django 5.2.17 on 2026-10-08 15:20

import app.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0047_website_overview_kind'),
        ('submissions', '0009_opinion_sent_files'),
        ('workflow', '0013_planned_actions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # docs/adr/0146. **Additive.** A new table (with its own constraints), two
    # new NextAction columns — `follow_up` nullable, `follow_up_outcome` with a
    # database default — and five NextAction constraints that every existing
    # row satisfies by construction (`follow_up IS NULL`, outcome `''`). No row
    # is rewritten and nothing is backfilled: no opinion sent before this
    # release gets a follow-up (docs/adr/0146 §9).
    operations = [
        migrations.CreateModel(
            name='OpinionFollowUp',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_on', models.DateField(verbose_name='saadetud')),
                ('first_due_on', models.DateField(verbose_name='esimene kontroll')),
                ('state', models.CharField(choices=[('MONITORING', 'Jälgimisel'), ('RESPONSE_RECEIVED', 'Vastus saabunud'), ('ENDED', 'Jälgimine lõpetatud'), ('CANCELLED', 'Tühistatud')], db_index=True, default='MONITORING', max_length=24, verbose_name='olek')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='lõpetatud')),
                ('end_reason', models.TextField(blank=True, default='', verbose_name='lõpetamise põhjus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_opinion_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ended_opinion_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='follow_up', to='submissions.submission', verbose_name='arvamus')),
            ],
            options={
                'verbose_name': 'arvamuse järelkontroll',
                'verbose_name_plural': 'arvamuste järelkontrollid',
                'ordering': ['-created_at'],
                'constraints': [
                    models.CheckConstraint(condition=models.Q(('state__in', ['MONITORING', 'RESPONSE_RECEIVED', 'ENDED', 'CANCELLED'])), name='workflow_follow_up_state_vocabulary'),
                    models.CheckConstraint(condition=models.Q(('first_due_on__gte', models.F('sent_on'))), name='workflow_follow_up_due_after_sending'),
                    models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', True), ('state', 'MONITORING')), models.Q(models.Q(('state', 'MONITORING'), _negated=True), ('ended_at__isnull', False)), _connector='OR'), name='workflow_follow_up_end_stamped'),
                    models.CheckConstraint(condition=models.Q(models.Q(('state', 'ENDED'), _negated=True), models.Q(('end_reason', ''), _negated=True), _connector='OR'), name='workflow_follow_up_end_has_reason'),
                ],
            },
        ),
        migrations.AddField(
            model_name='nextaction',
            name='follow_up_outcome',
            field=models.CharField(blank=True, choices=[('RESPONSE_RECEIVED', 'Vastus saabunud'), ('NO_RESPONSE', 'Vastust ei ole — kontrollin uuesti'), ('MONITORING_ENDED', 'Lõpetan jälgimise')], db_default='', default='', max_length=24, verbose_name='järelkontrolli tulemus'),
        ),
        migrations.AddField(
            model_name='nextaction',
            name='follow_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='workflow.opinionfollowup', verbose_name='arvamuse järelkontroll'),
        ),
        migrations.AddConstraint(
            model_name='nextaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['OPEN', 'PLANNED'])), fields=('follow_up',), name='workflow_one_active_check_per_follow_up'),
        ),
        migrations.AddConstraint(
            model_name='nextaction',
            constraint=models.CheckConstraint(condition=models.Q(('follow_up__isnull', True), ('target_date__isnull', False), _connector='OR'), name='workflow_follow_up_check_is_dated'),
        ),
        migrations.AddConstraint(
            model_name='nextaction',
            constraint=models.CheckConstraint(condition=models.Q(('follow_up_outcome__in', ['', 'RESPONSE_RECEIVED', 'NO_RESPONSE', 'MONITORING_ENDED'])), name='workflow_follow_up_outcome_vocabulary'),
        ),
        migrations.AddConstraint(
            model_name='nextaction',
            constraint=models.CheckConstraint(condition=models.Q(('follow_up_outcome', ''), models.Q(('follow_up__isnull', False), ('status', 'COMPLETED')), _connector='OR'), name='workflow_follow_up_outcome_on_completed_check'),
        ),
        migrations.AddConstraint(
            model_name='nextaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('follow_up__isnull', False), ('status', 'COMPLETED'), _negated=True), models.Q(('follow_up_outcome', ''), _negated=True), _connector='OR'), name='workflow_completed_check_has_outcome'),
        ),
    ]
