# Generated by Django 5.2.17 on 2026-08-21 12:47

import app.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legacy_import', '0004_historical_corpus'),
        ('matters', '0005_matter_origin_onenote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatterEffectiveDate',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility_override', models.CharField(blank=True, choices=[('NORMAL', 'Tavaline'), ('RESTRICTED', 'Piiratud')], db_index=True, default='', help_text='Tühi tähendab, et nähtavus päritakse teemalt.', max_length=16, verbose_name='nähtavuse kitsendus')),
                ('note', models.TextField(blank=True, verbose_name='märkus')),
                ('source_text', models.TextField(blank=True, help_text='Imporditud kirje puhul säilib siin allika täpne tekst.', verbose_name='algne sõnastus')),
                ('kind', models.CharField(choices=[('KNOWN_DATE', 'Teadaolev kuupäev'), ('GENERAL_ORDER', 'Jõustub üldises korras'), ('UNKNOWN', 'Kuupäev täpsustamisel')], db_index=True, default='KNOWN_DATE', max_length=16, verbose_name='jõustumise liik')),
                ('date_value', models.DateField(blank=True, db_index=True, null=True, verbose_name='jõustub')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='perioodi lõpp')),
                ('date_precision', models.CharField(choices=[('EXACT', 'Täpne'), ('MONTH', 'Kuu täpsusega'), ('QUARTER', 'Kvartali täpsusega'), ('HALF_YEAR', 'Poolaasta täpsusega'), ('YEAR', 'Aasta täpsusega'), ('INFERRED', 'Tuletatud tekstist')], default='EXACT', max_length=16, verbose_name='täpsus')),
                ('description', models.TextField(blank=True, help_text='Näiteks põhiosa, osad sätted või konkreetne muudatus.', verbose_name='mis jõustub')),
                ('source_url', models.URLField(blank=True, help_text='Näiteks Riigi Teataja viide. Käsitsi sisestatud; süsteem seda ei kontrolli.', max_length=1000, verbose_name='ametlik allikas')),
                ('status', models.CharField(choices=[('ACTIVE', 'Kehtiv'), ('CANCELLED', 'Tühistatud'), ('SUPERSEDED', 'Asendatud')], db_index=True, default='ACTIVE', max_length=16, verbose_name='olek')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='lisas')),
                ('legacy_source_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='legacy_import.legacysourcepage', verbose_name='ajalooline lähteleht')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effective_dates', to='matters.matter', verbose_name='teema')),
            ],
            options={
                'verbose_name': 'jõustumine',
                'verbose_name_plural': 'jõustumised',
                'ordering': ['date_value', 'period_end', 'id'],
                'indexes': [models.Index(fields=['status', 'kind', 'date_value'], name='intel_effective_kind_date'), models.Index(fields=['matter', 'status'], name='intel_effective_matter_status'), models.Index(fields=['status', 'period_end'], name='intel_effective_status_end')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('date_value__isnull', False), ('kind', 'KNOWN_DATE')), models.Q(models.Q(('kind', 'KNOWN_DATE'), _negated=True), ('date_value__isnull', True)), _connector='OR'), name='intelligence_effective_date_matches_kind'), models.CheckConstraint(condition=models.Q(models.Q(('date_value__isnull', True), ('period_end__isnull', True)), models.Q(('date_value__isnull', False), ('period_end__isnull', False)), _connector='OR'), name='intelligence_effective_date_bounds_together'), models.CheckConstraint(condition=models.Q(('period_end__isnull', True), ('period_end__gte', models.F('date_value')), _connector='OR'), name='intelligence_effective_date_period_ordered'), models.CheckConstraint(condition=models.Q(('kind__in', ['KNOWN_DATE', 'GENERAL_ORDER', 'UNKNOWN'])), name='intelligence_effective_date_kind_vocabulary'), models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'CANCELLED', 'SUPERSEDED'])), name='intelligence_effective_date_status_vocabulary'), models.CheckConstraint(condition=models.Q(('date_precision__in', ['EXACT', 'MONTH', 'QUARTER', 'HALF_YEAR', 'YEAR', 'INFERRED'])), name='intelligence_effective_date_precision_vocabulary'), models.CheckConstraint(condition=models.Q(('visibility_override__in', ['', 'NORMAL', 'RESTRICTED'])), name='intelligence_effective_date_visibility_vocabulary')],
            },
        ),
        migrations.CreateModel(
            name='MatterImportantDate',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility_override', models.CharField(blank=True, choices=[('NORMAL', 'Tavaline'), ('RESTRICTED', 'Piiratud')], db_index=True, default='', help_text='Tühi tähendab, et nähtavus päritakse teemalt.', max_length=16, verbose_name='nähtavuse kitsendus')),
                ('note', models.TextField(blank=True, verbose_name='märkus')),
                ('source_text', models.TextField(blank=True, help_text='Imporditud kirje puhul säilib siin allika täpne tekst.', verbose_name='algne sõnastus')),
                ('title', models.TextField(verbose_name='tähtaeg')),
                ('date_value', models.DateField(db_index=True, verbose_name='kuupäev või periood')),
                ('period_end', models.DateField(verbose_name='perioodi lõpp')),
                ('date_precision', models.CharField(choices=[('EXACT', 'Täpne'), ('MONTH', 'Kuu täpsusega'), ('QUARTER', 'Kvartali täpsusega'), ('HALF_YEAR', 'Poolaasta täpsusega'), ('YEAR', 'Aasta täpsusega'), ('INFERRED', 'Tuletatud tekstist')], default='EXACT', max_length=16, verbose_name='täpsus')),
                ('status', models.CharField(choices=[('ACTIVE', 'Kehtiv'), ('CANCELLED', 'Tühistatud'), ('SUPERSEDED', 'Asendatud')], db_index=True, default='ACTIVE', max_length=16, verbose_name='olek')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='lisas')),
                ('legacy_source_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='legacy_import.legacysourcepage', verbose_name='ajalooline lähteleht')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_dates', to='matters.matter', verbose_name='teema')),
                ('replaced_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='intelligence.matterimportantdate', verbose_name='asendatud kirjega')),
            ],
            options={
                'verbose_name': 'oluline tähtaeg',
                'verbose_name_plural': 'olulised tähtajad',
                'ordering': ['date_value', 'period_end', 'id'],
                'indexes': [models.Index(fields=['status', 'date_value'], name='intel_important_status_date'), models.Index(fields=['matter', 'status'], name='intel_important_matter_status'), models.Index(fields=['status', 'period_end'], name='intel_important_status_end')],
                'constraints': [models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='intelligence_important_date_title_required'), models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('date_value'))), name='intelligence_important_date_period_ordered'), models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'CANCELLED', 'SUPERSEDED'])), name='intelligence_important_date_status_vocabulary'), models.CheckConstraint(condition=models.Q(('date_precision__in', ['EXACT', 'MONTH', 'QUARTER', 'HALF_YEAR', 'YEAR', 'INFERRED'])), name='intelligence_important_date_precision_vocabulary'), models.CheckConstraint(condition=models.Q(('visibility_override__in', ['', 'NORMAL', 'RESTRICTED'])), name='intelligence_important_date_visibility_vocabulary')],
            },
        ),
        migrations.CreateModel(
            name='MatterWorkVictory',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility_override', models.CharField(blank=True, choices=[('NORMAL', 'Tavaline'), ('RESTRICTED', 'Piiratud')], db_index=True, default='', help_text='Tühi tähendab, et nähtavus päritakse teemalt.', max_length=16, verbose_name='nähtavuse kitsendus')),
                ('note', models.TextField(blank=True, verbose_name='märkus')),
                ('source_text', models.TextField(blank=True, help_text='Imporditud kirje puhul säilib siin allika täpne tekst.', verbose_name='algne sõnastus')),
                ('status', models.CharField(choices=[('CANDIDATE', 'Töövõidu kandidaat'), ('CONFIRMED', 'Kinnitatud töövõit'), ('NOT_REALIZED', 'Ei realiseerunud')], db_index=True, default='CANDIDATE', max_length=16, verbose_name='olek')),
                ('title', models.TextField(verbose_name='töövõit')),
                ('detail', models.TextField(blank=True, verbose_name='selgitus')),
                ('period_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='periood')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='perioodi lõpp')),
                ('date_precision', models.CharField(choices=[('EXACT', 'Täpne'), ('MONTH', 'Kuu täpsusega'), ('QUARTER', 'Kvartali täpsusega'), ('HALF_YEAR', 'Poolaasta täpsusega'), ('YEAR', 'Aasta täpsusega'), ('INFERRED', 'Tuletatud tekstist')], default='YEAR', max_length=16, verbose_name='täpsus')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='viide')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='kinnitatud')),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='oleku muutus')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_work_victories', to=settings.AUTH_USER_MODEL, verbose_name='kinnitas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='lisas')),
                ('legacy_source_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='legacy_import.legacysourcepage', verbose_name='ajalooline lähteleht')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_victories', to='matters.matter', verbose_name='teema')),
            ],
            options={
                'verbose_name': 'töövõit',
                'verbose_name_plural': 'töövõidud',
                'ordering': [models.OrderBy(models.F('period_date'), descending=True, nulls_last=True), '-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'period_date'], name='intel_victory_status_period'), models.Index(fields=['matter', 'status'], name='intel_victory_matter_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='intelligence_work_victory_title_required'), models.CheckConstraint(condition=models.Q(models.Q(('period_date__isnull', True), ('period_end__isnull', True)), models.Q(('period_date__isnull', False), ('period_end__isnull', False)), _connector='OR'), name='intelligence_work_victory_bounds_together'), models.CheckConstraint(condition=models.Q(('period_end__isnull', True), ('period_end__gte', models.F('period_date')), _connector='OR'), name='intelligence_work_victory_period_ordered'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'CONFIRMED'), _negated=True), ('confirmed_at__isnull', False), _connector='OR'), name='intelligence_work_victory_confirmed_has_timestamp'), models.CheckConstraint(condition=models.Q(('status__in', ['CANDIDATE', 'CONFIRMED', 'NOT_REALIZED'])), name='intelligence_work_victory_status_vocabulary'), models.CheckConstraint(condition=models.Q(('date_precision__in', ['EXACT', 'MONTH', 'QUARTER', 'HALF_YEAR', 'YEAR', 'INFERRED'])), name='intelligence_work_victory_precision_vocabulary'), models.CheckConstraint(condition=models.Q(('visibility_override__in', ['', 'NORMAL', 'RESTRICTED'])), name='intelligence_work_victory_visibility_vocabulary')],
            },
        ),
    ]
