# Generated by Django 5.2.17 on 2026-09-20 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
        ('legacy_import', '0015_alter_opinionmatchcandidate_match_class_and_more'),
        ('matters', '0033_development_process_phase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matterimportantdate',
            name='kind',
            field=models.CharField(choices=[('OTHER', 'Muu tähtaeg'), ('TRANSPOSITION_DEADLINE', 'ELi õiguse ülevõtmise tähtaeg')], db_index=True, default='OTHER', max_length=32, verbose_name='tähtaja liik'),
        ),
        migrations.AddConstraint(
            model_name='matterimportantdate',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['OTHER', 'TRANSPOSITION_DEADLINE'])), name='intelligence_important_date_kind_vocabulary'),
        ),
    ]
