"""`Kustuta` on a user-created block of `Teema käik` — the `app.intelligence` half.

The same two nullable columns `matters/0036_removable_records.py` adds, on the
three structured facts: `Oluline tähtaeg`, `Jõustumine` and the `Töövõit`
record. They inherit them from `MatterFact`, so one edit to the abstract base
produces three tables' worth of migration here (OWNER-04, docs/adr/0102).

**Removal is not `FactStatus.CANCELLED`, and this is why the column is new
rather than a fourth status value.** A cancelled deadline is an expectation
somebody called off: it was real, the calling-off is itself history, and the
row goes on reading in `Teema käik` saying `Tühistatud`. A removed one never
belonged to this file at all. Folding the two into one column would make every
cancelled row indistinguishable from a mistake and take a real piece of history
off the page.

Additive, reversible, no backfill.
"""


# Generated by Django 5.2.17 on 2026-09-21 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0002_important_date_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mattereffectivedate",
            name="removed_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Täidetud, kui kirje on aktiivsest teema käigust eemaldatud.",
                null=True,
                verbose_name="eemaldatud",
            ),
        ),
        migrations.AddField(
            model_name="mattereffectivedate",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="eemaldaja",
            ),
        ),
        migrations.AddField(
            model_name="matterimportantdate",
            name="removed_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Täidetud, kui kirje on aktiivsest teema käigust eemaldatud.",
                null=True,
                verbose_name="eemaldatud",
            ),
        ),
        migrations.AddField(
            model_name="matterimportantdate",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="eemaldaja",
            ),
        ),
        migrations.AddField(
            model_name="matterworkvictory",
            name="removed_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Täidetud, kui kirje on aktiivsest teema käigust eemaldatud.",
                null=True,
                verbose_name="eemaldatud",
            ),
        ),
        migrations.AddField(
            model_name="matterworkvictory",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="eemaldaja",
            ),
        ),
    ]
