# Generated by Django 5.2.17 on 2026-08-21 07:35

import app.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matters', '0005_matter_origin_onenote'),
        ('workflow', '0005_deadline_requires_a_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalMatterSnapshot',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField(db_index=True, verbose_name='hetktõmmise kuupäev')),
                ('stage_key', models.CharField(blank=True, max_length=64, verbose_name='hetkeseisu võti')),
                ('stage_label', models.CharField(blank=True, max_length=200, verbose_name='hetkeseisu nimetus')),
                ('track', models.CharField(blank=True, choices=[('DOMESTIC', 'Riigisisene'), ('EU_INITIATIVE', 'ELi algatus'), ('NATIONAL_TRANSPOSITION', 'ELi õiguse ülevõtmine'), ('STRATEGY', 'Strateegia või arengukava'), ('KODA_INITIATIVE', 'Koja algatus'), ('IMPLEMENTATION', 'Rakendamine või järelevalve'), ('OTHER', 'Muu')], default='', max_length=32, verbose_name='menetlusliik')),
                ('next_action_kind', models.CharField(blank=True, choices=[('DO', 'Teen'), ('WAIT', 'Ootan'), ('MONITOR', 'Jälgin')], default='', max_length=16, verbose_name='järgmise tegevuse liik')),
                ('next_action_date_semantics', models.CharField(blank=True, choices=[('DEADLINE', 'Tähtaeg'), ('REVIEW_ON', 'Vaatan üle'), ('EXPECTED_AROUND', 'Oodatav umbes')], default='', max_length=32, verbose_name='kuupäeva tähendus')),
                ('next_action_date', models.DateField(blank=True, null=True, verbose_name='tegevuse kuupäev')),
                ('response_deadline', models.DateField(blank=True, null=True, verbose_name='arvamuse tähtaeg')),
                ('captured_at', models.DateTimeField(verbose_name='hõivatud')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_snapshots', to='matters.matter', verbose_name='teema')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='vastutaja')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_snapshots', to='workflow.stagevocabulary', verbose_name='hetkeseis')),
            ],
            options={
                'verbose_name': 'teema hetktõmmis',
                'verbose_name_plural': 'teemade hetktõmmised',
                'ordering': ['-snapshot_date', 'matter'],
                'indexes': [models.Index(fields=['snapshot_date', 'owner'], name='reporting_snapshot_owner'), models.Index(fields=['snapshot_date', 'next_action_kind'], name='reporting_snapshot_action')],
                'constraints': [models.UniqueConstraint(fields=('snapshot_date', 'matter'), name='reporting_one_snapshot_per_matter_per_day')],
            },
        ),
    ]
