# Generated by Django 5.2.17 on 2026-08-18 17:15

import app.core.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, verbose_name='nimi')),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=300)),
                ('registry_code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='registrikood')),
                ('organisation_type', models.CharField(choices=[('MINISTRY', 'Ministeerium'), ('AUTHORITY', 'Amet või inspektsioon'), ('PARLIAMENT', 'Riigikogu'), ('GOVERNMENT', 'Valitsus'), ('EU_INSTITUTION', 'ELi institutsioon'), ('COMPANY', 'Ettevõte'), ('ASSOCIATION', 'Liit või ühendus'), ('CHAMBER', 'Koda'), ('OTHER', 'Muu')], default='OTHER', max_length=32, verbose_name='tüüp')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='kehtiv alates')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='kehtiv kuni')),
                ('source_reference', models.CharField(blank=True, help_text='Liikmeregistri või muu välise allika identifikaator, kui see on teada.', max_length=200, verbose_name='allika viide')),
                ('notes', models.TextField(blank=True, verbose_name='märkused')),
                ('predecessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='organisations.organisation', verbose_name='eelkäija')),
            ],
            options={
                'verbose_name': 'organisatsioon',
                'verbose_name_plural': 'organisatsioonid',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationAlias',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=300, verbose_name='nimekuju')),
                ('normalized_alias', models.CharField(db_index=True, editable=False, max_length=300)),
                ('alias_type', models.CharField(choices=[('HISTORICAL_NAME', 'Ajalooline nimi'), ('ABBREVIATION', 'Lühend'), ('SYNONYM', 'Sünonüüm'), ('SOURCE_SPELLING', 'Allika kirjapilt')], default='SYNONYM', max_length=32, verbose_name='tüüp')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='organisations.organisation', verbose_name='organisatsioon')),
            ],
            options={
                'verbose_name': 'organisatsiooni nimekuju',
                'verbose_name_plural': 'organisatsiooni nimekujud',
                'ordering': ['alias'],
            },
        ),
        migrations.AddConstraint(
            model_name='organisation',
            constraint=models.UniqueConstraint(condition=models.Q(('registry_code', ''), _negated=True), fields=('registry_code',), name='organisations_unique_registry_code'),
        ),
        migrations.AddConstraint(
            model_name='organisation',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_from__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='organisations_valid_period_ordered'),
        ),
        migrations.AddConstraint(
            model_name='organisationalias',
            constraint=models.UniqueConstraint(fields=('organisation', 'normalized_alias'), name='organisations_unique_alias_per_organisation'),
        ),
    ]
