"""Reading the file while `Uus teema` is still open, as a lawyer meets it.

The rules are proved sentence by sentence in `tests/test_assisted_intake.py`
and the contract around staging in `tests/test_intake_staging.py`. What only a
browser shows is the workflow this feature exists for: drop the ministry's
letter on the create form, watch it be read, take what it found, press one
button, and find the file under Dokumendid a moment later (docs/adr/0064).

Nothing here is mocked. The upload goes through the real staging route, the
real worker reads it in its own process, the real analyser produces the
suggestions, and the real `Loo teema` promotes the bytes. A test that stubbed
any of those would prove the page calls something, which was never the part in
doubt.

Nothing here is real, either. The letter is generated by the synthetic corpus
at test time and the ministry is the seeded «Näidisministeerium».
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

import pytest
from playwright.sync_api import expect

from e2e.conftest import SANDRA, sign_in

pytestmark = pytest.mark.e2e

REPOSITORY_ROOT = Path(__file__).resolve().parent.parent

TYPED_TITLE = "Käsitsi kirjutatud pealkiri, mida miski ei tohi üle kirjutada"

LETTER = """Näidisministeerium
Suur-Ameerika 1, Tallinn

Eesti Kaubandus-Tööstuskoda
Meie 05.09.2026 nr 1-4/26/5555-2

Pakendiseaduse muutmise seaduse eelnõu kooskõlastamiseks

Lugupeetud Koja esindajad

Saadame Teile kooskõlastamiseks pakendiseaduse muutmise seaduse eelnõu, mis on
registreeritud eelnõude infosüsteemis EIS toimik 26-0777. Eelnõuga muudetakse
pakendite ja jäätmete käitlemise korda ning keskkonnatasu määrasid. Palume
esitada arvamus hiljemalt 18. septembriks 2026. Seadus jõustub 1. jaanuaril 2027.

Lugupidamisega
Mari Näidis
nõunik
E-post: mari.naidis@naidisministeerium.invalid
"""


@pytest.fixture
def letter_pdf(tmp_path: Path) -> Path:
    sys.path.insert(0, str(REPOSITORY_ROOT))
    from tests.synthetic_corpus import text_pdf

    path = tmp_path / "kaaskiri.pdf"
    path.write_bytes(text_pdf([LETTER]))
    return path


@pytest.fixture
def annex_pdf(tmp_path: Path) -> Path:
    sys.path.insert(0, str(REPOSITORY_ROOT))
    from tests.synthetic_corpus import text_pdf

    path = tmp_path / "lisa.pdf"
    path.write_bytes(text_pdf(["Lisa 1. Pakendiaruande vorm."]))
    return path


def read_staged_files() -> str:
    """Drain the staged queue the way the deployment does.

    A subprocess rather than an in-process call, because that is what actually
    runs on the server: a separate process with its own database connection,
    seeing rows a web request committed. The settings module is forced for the
    same reason `e2e/test_document_content.py::run_worker` forces it — pytest
    sets the test settings for its own process and those mint a fresh temporary
    storage root, so a child inheriting them would look in an empty directory.
    """
    environment = {**os.environ, "DJANGO_SETTINGS_MODULE": "config.settings"}
    result = subprocess.run(
        [sys.executable, "manage.py", "extract_pending_intake_files", "--limit", "20"],
        cwd=REPOSITORY_ROOT,
        env=environment,
        capture_output=True,
        text=True,
        timeout=300,
        check=False,
    )
    report = "\n".join(["stdout:", result.stdout, "stderr:", result.stderr])
    assert result.returncode == 0, report
    # A worker that ran and found nothing is the failure this helper exists to
    # catch, and it is invisible unless asserted.
    assert "Loetud 0 faili" not in result.stdout, report
    return report


def open_create(page, base_url: str) -> None:
    page.goto(f"{base_url}/teemad/uus/")
    expect(page.get_by_role("heading", name="Uus teema")).to_be_visible()


def choose(page, paths: list[Path]) -> None:
    page.locator("#id_files").set_input_files([str(path) for path in paths])


def staged_rows(page):
    return page.locator("#intake-failid .dropzone__file")


def wait_for_reading(page) -> None:
    """The upload has landed and the page says what is happening."""
    expect(page.locator("#intake-panel")).to_have_attribute("data-intake-state", "reading")


def wait_for_suggestions(page) -> None:
    expect(page.locator("#intake-panel")).to_have_attribute(
        "data-intake-state", "ready", timeout=30_000
    )
    expect(page.get_by_role("heading", name="Failist leitud")).to_be_visible()


def open_documents(page) -> None:
    page.get_by_role("link", name=re.compile(r"^Dokumendid")).click()
    page.wait_for_load_state("networkidle")


def name_a_next_step(page) -> None:
    """Say what happens next, as a lawyer filing a real Teema would.

    Not decoration: a Teema this suite leaves behind with no next action joins
    the department's «järgmise tegevuseta» population permanently, and
    `e2e/test_kpi_navigation.py` reads the first rows of that list
    (e2e/test_uus_teema_files.py).
    """
    page.fill("#id_next-text", "Lugeda eelnõu ja koostada arvamus")
    page.locator("#jargmine-tegevus").get_by_role("button", name="+1 nädal").click()


def register_holds(page, base_url: str, title: str) -> int:
    """How many register rows carry this title. Zero is the assertion we want.

    Asked through the ordinary register rather than the database, because this
    suite deliberately has no database access: a browser test that read around
    the UI could mask exactly the authorization and visibility defects it is
    here to catch (e2e/conftest.py).

    In a tab of its own, so asking the question does not navigate away from the
    half-filled form that is the subject of it.
    """
    other = page.context.new_page()
    try:
        other.goto(f"{base_url}/teemad/")
        return other.get_by_role("link", name=title, exact=True).count()
    finally:
        other.close()


def test_the_letter_is_read_on_the_create_form_and_the_teema_keeps_what_was_confirmed(
    page, base_url, screenshots, letter_pdf
) -> None:
    """The whole workflow, in the order somebody performs it.

    One journey, without leaving the form: choose, watch it be read, take what
    it found, write a title, press the button once. The register is asked twice
    from a tab of its own, so «nothing exists yet» is checked without
    abandoning the half-filled page it is a claim about.
    """
    sign_in(page, base_url, SANDRA)
    title = "Pakendiseaduse muudatus, loetud loomisel"
    assert register_holds(page, base_url, title) == 0

    # -- 1. choose the file; it uploads itself and says so ------------------
    open_create(page, base_url)
    choose(page, [letter_pdf])
    wait_for_reading(page)
    expect(staged_rows(page)).to_have_count(1)
    expect(page.locator("#intake-failid")).to_contain_text("kaaskiri.pdf")
    expect(page.locator("#intake-panel")).to_contain_text("Loen faili")
    # Words a person can act on, and none of the stored vocabulary.
    panel = page.locator("#intake-panel").inner_text()
    assert "PENDING" not in panel and "Teksti eraldamine" not in panel
    screenshots(page, "40-uus-teema-loen-faili")

    # -- 2. the worker reads it, in its own process ------------------------
    read_staged_files()
    wait_for_suggestions(page)

    # -- 3. what the letter says, with the sentence it came from -----------
    expect(
        page.get_by_text("Palume esitada arvamus hiljemalt 18. septembriks 2026").first
    ).to_be_visible()
    expect(page.get_by_text("Arvamuse tähtaeg").first).to_be_visible()
    expect(page.get_by_text("Kellelt").first).to_be_visible()
    expect(page.get_by_text("EIS").first).to_be_visible()
    # The deadline is strong and unopposed, so it is already in the box; the
    # sender is ticked in the real control. Neither is saved.
    expect(page.locator("#id_response_deadline")).to_have_value("18.9.2026")
    ministry = page.locator("label.chip", has_text="Näidisministeerium").locator("input").first
    expect(ministry).to_be_checked()
    # The title is offered and never written, on any surface.
    expect(page.locator("#id_title")).to_have_value("")
    expect(page.locator('button[data-suggest-for="title"]').first).to_be_visible()
    screenshots(page, "41-uus-teema-failist-leitud")

    # Still nothing in the register: a suggestion is a proposal, and reading a
    # file creates no business data whatsoever.
    assert register_holds(page, base_url, title) == 0

    # -- 4. take the heading, write a title over it, and file it -----------
    page.locator('button[data-suggest-for="title"]').first.click()
    expect(page.locator("#id_title")).to_have_value("Pakendiseaduse muutmise seaduse eelnõu")
    page.locator("#id_title").fill(title)
    name_a_next_step(page)
    page.get_by_role("button", name="Loo teema").click()
    page.wait_for_load_state("domcontentloaded")

    complaints = page.locator(".field__error, .formerror, .message--error").all_inner_texts()
    assert not complaints, f"the form refused: {complaints}"
    page.wait_for_url(re.compile(r"/teemad/[0-9a-f-]{36}/$"))
    matter_url = page.url

    # -- 5. exactly one Teema, carrying what was confirmed -----------------
    expect(page.get_by_role("heading", name=title)).to_be_visible()
    expect(page.get_by_text("18.9.2026").first).to_be_visible()
    assert register_holds(page, base_url, title) == 1

    # -- 6. and the file is under Dokumendid, openable, byte for byte ------
    page.goto(matter_url)
    open_documents(page)
    expect(page.get_by_role("link", name="kaaskiri.pdf", exact=True)).to_be_visible()

    with page.expect_download() as download:
        page.get_by_role("link", name="Laadi alla kaaskiri.pdf").click()
    saved = download.value
    assert saved.suggested_filename == "kaaskiri.pdf"
    assert Path(saved.path()).read_bytes() == letter_pdf.read_bytes()


def test_a_suggestion_never_overwrites_what_the_person_typed_first(
    page, base_url, letter_pdf
) -> None:
    """The rule that makes an asynchronous answer safe.

    Extraction finishes seconds after somebody has begun typing, so the test
    is: type into the two controls the letter has strong answers for *before*
    the answer arrives, and assert both survive it (task §10, §28).
    """
    sign_in(page, base_url, SANDRA)
    open_create(page, base_url)
    choose(page, [letter_pdf])
    wait_for_reading(page)

    # Typed while the file is still being read.
    page.locator("#id_title").fill(TYPED_TITLE)
    page.locator("#id_response_deadline").fill("30.9.2026")
    page.locator("label.chip", has_text="Näidisamet").locator("input").first.check()

    read_staged_files()
    wait_for_suggestions(page)

    # The letter says 18.9.2026 and names the ministry. Neither is written over.
    expect(page.locator("#id_title")).to_have_value(TYPED_TITLE)
    expect(page.locator("#id_response_deadline")).to_have_value("30.9.2026")
    expect(
        page.locator("label.chip", has_text="Näidisministeerium").locator("input").first
    ).not_to_be_checked()
    expect(page.locator("label.chip", has_text="Näidisamet").locator("input").first).to_be_checked()

    # And both candidates are still offered beside what was typed, so nothing
    # is hidden — the person can still choose them.
    expect(page.locator('button[data-suggest-for="response_deadline"]').first).to_be_visible()


def test_a_file_taken_back_off_stops_suggesting_and_is_not_filed(
    page, base_url, letter_pdf, annex_pdf
) -> None:
    """The browser and the server must not disagree about a file half gone."""
    sign_in(page, base_url, SANDRA)
    title = "Ainult lisa jäi alles"
    open_create(page, base_url)
    choose(page, [letter_pdf, annex_pdf])
    expect(staged_rows(page)).to_have_count(2)
    read_staged_files()
    wait_for_suggestions(page)
    expect(page.locator("#id_response_deadline")).to_have_value("18.9.2026")

    page.locator("[data-intake-remove]").first.click()
    expect(staged_rows(page)).to_have_count(1)
    expect(page.locator("#intake-failid")).to_contain_text("lisa.pdf")
    expect(page.locator("#intake-failid")).not_to_contain_text("kaaskiri.pdf")
    # The removed letter's deadline is no longer offered by anything.
    expect(page.locator('button[data-suggest-for="response_deadline"]')).to_have_count(0)

    page.locator("#id_title").fill(title)
    name_a_next_step(page)
    page.get_by_role("button", name="Loo teema").click()
    page.wait_for_url(re.compile(r"/teemad/[0-9a-f-]{36}/$"))

    open_documents(page)
    expect(page.get_by_role("link", name="lisa.pdf", exact=True)).to_be_visible()
    expect(page.get_by_role("link", name="kaaskiri.pdf", exact=True)).to_have_count(0)


def test_a_refused_save_keeps_the_staged_file_and_what_was_found(
    page, base_url, screenshots, letter_pdf
) -> None:
    """A refusal must lose neither the upload nor the reading (task §20, §32)."""
    sign_in(page, base_url, SANDRA)
    title = "Parandatud ja uuesti saadetud"
    open_create(page, base_url)
    choose(page, [letter_pdf])
    read_staged_files()
    wait_for_suggestions(page)

    page.locator("#id_title").fill(title)
    # The ordinary refusal: «Muu» ticked with nothing written beside it.
    page.locator("#valdkond-muu input").check()
    page.get_by_role("button", name="Loo teema").click()
    page.wait_for_load_state("domcontentloaded")

    expect(page.get_by_role("heading", name="Uus teema")).to_be_visible()
    expect(staged_rows(page)).to_have_count(1)
    expect(page.locator("#intake-failid")).to_contain_text("kaaskiri.pdf")
    expect(page.get_by_role("heading", name="Failist leitud")).to_be_visible()
    expect(page.locator("#id_title")).to_have_value(title)
    expect(page.locator("#id_response_deadline")).to_have_value("18.9.2026")
    screenshots(page, "42-uus-teema-keeldumine-failiga")

    page.locator("#valdkond-muu-tekst input").fill("Pakendid")
    name_a_next_step(page)
    page.get_by_role("button", name="Loo teema").click()
    page.wait_for_url(re.compile(r"/teemad/[0-9a-f-]{36}/$"))

    open_documents(page)
    expect(page.get_by_role("link", name="kaaskiri.pdf", exact=True)).to_be_visible()


def test_a_file_that_cannot_be_read_does_not_stop_the_teema(
    page, base_url, screenshots, tmp_path
) -> None:
    """Automatic reading is help, never a gate (task §21, §33)."""
    sys.path.insert(0, str(REPOSITORY_ROOT))
    from tests.synthetic_corpus import corrupt_pdf

    broken = tmp_path / "katkine.pdf"
    broken.write_bytes(corrupt_pdf())

    sign_in(page, base_url, SANDRA)
    title = "Loetamatu fail, käsitsi täidetud"
    open_create(page, base_url)
    choose(page, [broken])
    wait_for_reading(page)
    read_staged_files()

    expect(page.locator("#intake-panel")).to_have_attribute(
        "data-intake-state", "ready", timeout=30_000
    )
    expect(page.get_by_text("Faili sisu ei õnnestunud automaatselt lugeda")).to_be_visible()
    expect(page.get_by_text("Fail ise on alles")).to_be_visible()
    screenshots(page, "43-uus-teema-lugemine-ebaonnestus")

    page.locator("#id_title").fill(title)
    name_a_next_step(page)
    page.get_by_role("button", name="Loo teema").click()
    page.wait_for_url(re.compile(r"/teemad/[0-9a-f-]{36}/$"))

    open_documents(page)
    expect(page.get_by_role("link", name="katkine.pdf", exact=True)).to_be_visible()


def test_three_initial_files_become_three_documents(
    page, base_url, letter_pdf, annex_pdf, tmp_path
) -> None:
    """The full intake envelope: each file stays a file (task §29)."""
    sys.path.insert(0, str(REPOSITORY_ROOT))
    from tests.synthetic_corpus import text_pdf

    memorandum = tmp_path / "seletuskiri.pdf"
    memorandum.write_bytes(text_pdf(["Seletuskiri pakendiseaduse muutmise seaduse juurde."]))

    sign_in(page, base_url, SANDRA)
    open_create(page, base_url)
    choose(page, [letter_pdf, annex_pdf, memorandum])
    expect(staged_rows(page)).to_have_count(3)
    read_staged_files()
    wait_for_suggestions(page)

    page.locator("#id_title").fill("Kolme failiga teema")
    name_a_next_step(page)
    page.get_by_role("button", name="Loo teema").click()
    page.wait_for_url(re.compile(r"/teemad/[0-9a-f-]{36}/$"))
    expect(page.locator(".message").first).to_contain_text("3 failiga")

    open_documents(page)
    for name in ("kaaskiri.pdf", "lisa.pdf", "seletuskiri.pdf"):
        expect(page.get_by_role("link", name=name, exact=True)).to_be_visible()


def test_uploading_a_document_later_starts_no_reading_workflow(
    page, base_url, letter_pdf, annex_pdf
) -> None:
    """Assisted reading belongs to the initial files, and stops there.

    A file added to a Teema that already exists is processed and indexed like
    any other; it does not reopen the suggestion workflow and it changes no
    field of the Matter (task §14, §35).
    """
    sign_in(page, base_url, SANDRA)
    title = "Hilisem fail ei muuda midagi"
    open_create(page, base_url)
    choose(page, [annex_pdf])
    read_staged_files()
    page.locator("#id_title").fill(title)
    page.locator("#id_response_deadline").fill("1.10.2026")
    name_a_next_step(page)
    page.get_by_role("button", name="Loo teema").click()
    page.wait_for_url(re.compile(r"/teemad/[0-9a-f-]{36}/$"))
    matter_url = page.url

    open_documents(page)
    page.get_by_role("button", name="↑ Lae dokument").click()
    page.locator("#lae-dokument input[name='upload']").set_input_files(str(letter_pdf))
    page.get_by_role("button", name="Salvesta dokument").click()
    page.wait_for_load_state("networkidle")
    expect(page.get_by_role("link", name="kaaskiri.pdf", exact=True)).to_be_visible()
    read_staged_files_is_a_noop()

    # The letter states 18.9.2026 and names a ministry. Neither reaches the
    # Matter, and no suggestion panel appears anywhere.
    page.goto(matter_url)
    expect(page.get_by_text("1.10.2026").first).to_be_visible()
    expect(page.get_by_text("18.9.2026")).to_have_count(0)
    expect(page.locator("#intake-panel")).to_have_count(0)
    expect(page.get_by_role("heading", name="Failist leitud")).to_have_count(0)


def read_staged_files_is_a_noop() -> None:
    """The staged queue is empty, because a later upload stages nothing.

    Deliberately asserted rather than skipped: "no staging was started" is the
    product decision this test is named after, and the only way to see it from
    a process with no database is that the queue the worker drains is empty.
    """
    environment = {**os.environ, "DJANGO_SETTINGS_MODULE": "config.settings"}
    result = subprocess.run(
        [sys.executable, "manage.py", "extract_pending_intake_files", "--limit", "20"],
        cwd=REPOSITORY_ROOT,
        env=environment,
        capture_output=True,
        text=True,
        timeout=300,
        check=False,
    )
    assert result.returncode == 0, result.stderr
    assert "Ootel: 0 ettevalmistatud faili" in result.stdout, result.stdout
