"""The cross-layer path a unit test cannot see: upload, extract, find, read.

Everything here is checked somewhere else in isolation — the parser against
bytes, the worker against the database, authorization against querysets. What
only a browser can show is that the four fit together: a file uploaded through
the real form is picked up by the real worker, indexed by the real signals, and
found by the real search page with a locator a person can act on.

Deliberately few tests. The browser suite exists for failures that live between
layers, and fifty brittle visual assertions would cost more than they catch
(docs/adr/0010, Stage-2B brief 90).
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import pytest
from playwright.sync_api import expect

from e2e.conftest import MARTIN, SANDRA, sign_in, sign_out

pytestmark = pytest.mark.e2e

REPOSITORY_ROOT = Path(__file__).resolve().parent.parent

#: A word that exists nowhere except inside the uploaded PDF. If search finds
#: it, search read the file — there is no other way it could know.
ONLY_INSIDE_THE_PDF = "kaubaaluste"
MATTER_TITLE = "Näidisministeeriumi digiaruandluse katse-eelnõu"


def run_worker() -> str:
    """Drain the extraction queue the way the deployment does.

    A subprocess rather than an in-process call, because that is what actually
    runs on the server: a separate container, a separate process, its own
    database connection. Calling the function directly would test the parser and
    quietly skip the part where a *different* process has to see the row the web
    request committed.
    """
    result = subprocess.run(
        [sys.executable, "manage.py", "extract_pending_documents", "--limit", "20"],
        cwd=REPOSITORY_ROOT,
        capture_output=True,
        text=True,
        timeout=300,
        check=False,
    )
    report = "\n".join(["stdout:", result.stdout, "stderr:", result.stderr])
    assert result.returncode == 0, report
    # A worker that ran and found nothing is the failure this whole helper
    # exists to catch, and it is invisible unless asserted: every downstream
    # expectation would fail somewhere else with a message about a missing
    # heading.
    assert "Töödeldud 0 faili" not in result.stdout, report
    assert "FAILED" not in result.stdout, report
    return report


@pytest.fixture
def synthetic_pdf(tmp_path: Path) -> Path:
    """A fictional consultation letter, written here rather than committed.

    Clearly synthetic content, generated by the same corpus module the unit
    tests use. No government document from the internet, and nothing real
    (Stage-2B brief 95).
    """
    sys.path.insert(0, str(REPOSITORY_ROOT))
    from tests.synthetic_corpus import government_pdf

    path = tmp_path / "katse-eelnou.pdf"
    path.write_bytes(government_pdf())
    return path


def test_a_pdf_uploaded_through_saabunud_becomes_searchable_by_its_contents(
    page, base_url, screenshots, synthetic_pdf
) -> None:
    sign_in(page, base_url, SANDRA)

    # -- file first: the intake surface takes the file, not a form --------
    page.goto(f"{base_url}/saabunud/lisa/")
    page.set_input_files("input[name='uploads']", str(synthetic_pdf))
    page.fill("input[name='title']", MATTER_TITLE)
    page.get_by_role("button", name="Salvesta ja ava teema").click()

    expect(page.get_by_role("heading", name=MATTER_TITLE)).to_be_visible()
    screenshots(page, "20-saabunud-lisatud")

    # -- the lawyer is not made to wait for extraction --------------------
    page.goto(f"{page.url.rstrip('/')}/dokumendid/")
    expect(page.get_by_text(re.compile("Teksti töötlemine ootel|Töötlemisel"))).to_be_visible()
    screenshots(page, "21-tootlemine-ootel")

    run_worker()

    page.reload()
    expect(page.get_by_text("Tekst olemas")).to_be_visible()

    # -- a safe preview, clearly marked as derived ------------------------
    page.get_by_role("link", name="Vaata sisu").first.click()
    expect(page.get_by_role("heading", name="Originaal")).to_be_visible()
    expect(page.get_by_role("heading", name="Tuletatud eelvaade")).to_be_visible()
    expect(page.get_by_text("See ei ole originaal", exact=False)).to_be_visible()
    expect(page.get_by_text("lk 4")).to_be_visible()
    expect(page.get_by_role("link", name="Laadi alla originaal")).to_be_visible()
    screenshots(page, "22-eelvaade")

    # -- and the words inside it are findable, with the page they are on ---
    page.get_by_placeholder("Otsi teemat, viidet, asutust…").fill(ONLY_INSIDE_THE_PDF)
    page.keyboard.press("Enter")

    expect(page.get_by_role("heading", name="Otsing")).to_be_visible()
    result = page.locator(".result").first
    expect(result).to_contain_text("Dokument")
    expect(result).to_contain_text("lk 4")
    expect(result.locator("mark").first).to_be_visible()
    screenshots(page, "23-otsing-dokumendist")

    # Clicking lands on the document, not merely on the matter.
    result.click()
    expect(page.get_by_role("heading", name="Tuletatud eelvaade")).to_be_visible()


def test_a_restricted_document_is_invisible_to_an_unrelated_lawyer(
    page, base_url, synthetic_pdf
) -> None:
    """The count is the test.

    Not "the row is absent" — a hidden document must not move a number either,
    and a search saying "1 vaste" beside an empty list would disclose it just as
    well (Stage-2B brief 44).
    """
    sign_in(page, base_url, SANDRA)
    page.goto(f"{base_url}/saabunud/lisa/")
    page.set_input_files("input[name='uploads']", str(synthetic_pdf))
    page.fill("input[name='title']", "Piiratud katsedokument")
    page.select_option("select[name='visibility']", "RESTRICTED")
    page.get_by_role("button", name="Salvesta ja ava teema").click()
    expect(page.get_by_role("heading", name="Piiratud katsedokument")).to_be_visible()

    run_worker()

    page.get_by_placeholder("Otsi teemat, viidet, asutust…").fill(ONLY_INSIDE_THE_PDF)
    page.keyboard.press("Enter")
    expect(page.get_by_text(re.compile(r"\d+ vastet päringule"))).to_be_visible()
    owner_summary = page.locator(".pagehead__context").inner_text()

    sign_out(page, base_url)
    sign_in(page, base_url, MARTIN)
    page.get_by_placeholder("Otsi teemat, viidet, asutust…").fill(ONLY_INSIDE_THE_PDF)
    page.keyboard.press("Enter")

    expect(page.locator("body")).not_to_contain_text("Piiratud katsedokument")
    outsider_summary = page.locator(".pagehead__context").inner_text()
    assert outsider_summary != owner_summary, (
        "the outsider's result count matched the owner's, so the restricted "
        f"document influenced it: {outsider_summary!r}"
    )


def test_an_email_shows_its_sender_and_its_attachments(
    page, base_url, screenshots, tmp_path
) -> None:
    sys.path.insert(0, str(REPOSITORY_ROOT))
    from tests.synthetic_corpus import consultation_eml

    path = tmp_path / "kooskolastus.eml"
    path.write_bytes(consultation_eml())

    sign_in(page, base_url, SANDRA)
    page.goto(f"{base_url}/saabunud/lisa/")
    page.set_input_files("input[name='uploads']", str(path))
    page.fill("input[name='title']", "Saabunud kiri ministeeriumist")
    page.get_by_role("button", name="Salvesta ja ava teema").click()
    expect(page.get_by_role("heading", name="Saabunud kiri ministeeriumist")).to_be_visible()

    run_worker()

    page.goto(f"{page.url.rstrip('/')}/dokumendid/")
    page.reload()
    # The message and both of its attachments, each its own document.
    expect(page.get_by_text("lisa-1.pdf")).to_be_visible()
    expect(page.get_by_text("markmed.txt")).to_be_visible()
    # The signature logo was an inline resource and is deliberately not here.
    expect(page.locator("body")).not_to_contain_text("allkiri-logo.png")

    page.get_by_role("link", name="Vaata sisu").first.click()
    expect(page.get_by_text("Kadri Näidis")).to_be_visible()
    screenshots(page, "24-kirja-eelvaade")
