"""The assisted review, as a lawyer meets it.

The rules are proved sentence by sentence in tests/test_assisted_intake.py.
What only a browser shows is the workflow: material filed through Saabunud,
read by the real worker, and the review page that pre-fills what it is sure
of, offers what it is not, keeps what the person already wrote, and saves
exactly what the person confirms.

Nothing here is real. The letter is generated by the synthetic corpus at
test time and the ministry is the seeded «Näidisministeerium».
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import pytest
from playwright.sync_api import expect

from e2e.conftest import SANDRA, sign_in
from e2e.test_document_content import run_worker

pytestmark = pytest.mark.e2e

REPOSITORY_ROOT = Path(__file__).resolve().parent.parent

TYPED_TITLE = "Sünteetiline pakendiseaduse teema — kasutaja enda pealkiri"
MECHANICAL_TITLE_STEM = "abistatud-katse-kaaskiri"

LETTER = """Näidisministeerium
Suur-Ameerika 1, Tallinn

Eesti Kaubandus-Tööstuskoda
Meie 05.09.2026 nr 1-4/26/9876-2

Pakendiseaduse muutmise seaduse eelnõu kooskõlastamiseks

Lugupeetud Koja esindajad

Saadame Teile kooskõlastamiseks pakendiseaduse muutmise seaduse eelnõu, mis on
registreeritud eelnõude infosüsteemis EIS toimik 26-0321. Eelnõuga muudetakse
pakendite ja jäätmete käitlemise korda ning keskkonnatasu määrasid. Näidisettevõtete
liit on eelnõu kooskõlastanud. Palume esitada arvamus hiljemalt 18. septembriks 2026.
Seadus jõustub 1. jaanuaril 2027.

Lugupidamisega
Mari Näidis
nõunik
E-post: mari.naidis@naidisministeerium.invalid
"""


@pytest.fixture
def letter_pdf(tmp_path: Path) -> Path:
    sys.path.insert(0, str(REPOSITORY_ROOT))
    from tests.synthetic_corpus import text_pdf

    path = tmp_path / f"{MECHANICAL_TITLE_STEM}.pdf"
    path.write_bytes(text_pdf([LETTER]))
    return path


@pytest.fixture
def message_eml(tmp_path: Path) -> Path:
    sys.path.insert(0, str(REPOSITORY_ROOT))
    from tests.synthetic_corpus import consultation_eml

    path = tmp_path / "abistatud-katse-kiri.eml"
    path.write_bytes(consultation_eml(attachments=False, inline_logo=False))
    return path


def file_through_saabunud(page, base_url: str, files: list[Path], title: str = "") -> str:
    page.goto(f"{base_url}/saabunud/lisa/")
    page.set_input_files("input[name='uploads']", [str(path) for path in files])
    if title:
        page.fill("input[name='title']", title)
    page.get_by_role("button", name="Registreeri ja loo teema").click()
    page.wait_for_url(re.compile(r"/teemad/[0-9a-f-]{36}/$"))
    return page.url


def review_url(matter_url: str) -> str:
    return f"{matter_url.rstrip('/')}/muuda/dokumendist/"


def test_the_review_pre_fills_what_it_is_sure_of_and_saves_what_the_person_confirms(
    page, base_url, screenshots, letter_pdf, message_eml
) -> None:
    sign_in(page, base_url, SANDRA)
    matter_url = file_through_saabunud(page, base_url, [letter_pdf, message_eml])

    # -- before extraction the page says so, and pre-fills nothing ---------
    page.goto(review_url(matter_url))
    expect(page.get_by_role("heading", name="Dokumendist leitud")).to_be_visible()
    expect(page.get_by_text("Teksti eraldamine on ootel")).to_be_visible()
    expect(page.get_by_text("vormil eeltäidetud")).to_have_count(0)
    expect(page.locator("#id_response_deadline")).to_have_value("")
    screenshots(page, "30-dokumendist-leitud-ootel")

    run_worker([letter_pdf.name, message_eml.name])

    # -- after extraction: suggestion, evidence, pre-filled blank fields ----
    page.goto(review_url(matter_url))
    expect(
        page.get_by_text("Palume esitada arvamus hiljemalt 18. septembriks 2026").first
    ).to_be_visible()
    expect(page.get_by_text("kirja päis").first).to_be_visible()
    expect(page.locator("#id_response_deadline")).to_have_value("18.9.2026")
    # **No `Menetlusliik`, pre-filled or otherwise.** The extractor still reads
    # the track out of the letter and the corpus-quality floor is still scored
    # on what it found — nothing about the analysis changed — but this review is
    # `MatterEditForm`, and that form stopped asking the question
    # (docs/adr/0097 §3). A prefill for a field the form never declares is a
    # value that reaches a widget nobody draws, so the prefill went with it.
    expect(page.locator('input[name="track"]')).to_have_count(0)
    # And the panel does not *offer* one either. This caught the real defect:
    # the analyser still finds the track, `FORM_FIELDS` still listed it, and the
    # panel printed «Menetlusliik» with a `Kasuta` button pointing at a box that
    # is not on the page — a suggestion a reader cannot accept, which is worse
    # than one that was never made (`intake_suggestions/types.py`).
    expect(page.get_by_text("Menetlusliik", exact=True)).to_have_count(0)
    expect(page.get_by_text("vormil eeltäidetud").first).to_be_visible()
    # The title is never written into the box, even here, where the Matter
    # still carries intake's mechanical filename: nothing in the record
    # separates that from a title a person typed (docs/adr/0060).
    expect(page.locator("#id_title")).to_have_value(MECHANICAL_TITLE_STEM.replace("-", " "))
    expect(page.locator('button[data-suggest-for="title"]').first).to_be_visible()
    # The message's sender, straight from its headers, with the address.
    expect(page.get_by_text("Saatja kontakt").first).to_be_visible()
    expect(page.get_by_text("kadri@naidisministeerium.invalid").first).to_be_visible()
    screenshots(page, "31-dokumendist-leitud")

    # -- the person takes the title, edits a pre-filled value, and saves ----
    page.locator('button[data-suggest-for="title"]').first.click()
    expect(page.locator("#id_title")).to_have_value("Pakendiseaduse muutmise seaduse eelnõu")
    page.fill("#id_response_deadline", "19.9.2026")
    page.get_by_role("button", name="Salvesta").click()
    page.wait_for_url(re.compile(r"/teemad/[0-9a-f-]{36}/$"))
    expect(
        page.get_by_role("heading", name="Pakendiseaduse muutmise seaduse eelnõu")
    ).to_be_visible()
    # **The deadline itself, not the whole page.**
    #
    # This read `get_by_text("18.9.2026")).to_have_count(0)`, which asked whether
    # the letter's suggested day appears *anywhere* — and the letter's day is a
    # fixed string in `LETTER` while half this page is dated from the clock. On
    # 18 September 2026 in Tallinn the two met: `Saabus`, `Teema loodud` and the
    # process strip all printed 18.9.2026 honestly, and the assertion failed
    # without anything being wrong. A guard that depends on the calendar not
    # reaching a date is a guard that is one morning from a false red.
    #
    # The fact being proved is narrower than the old spelling and is the whole
    # point of the step above: the person replaced the suggested deadline, and
    # the Matter carries theirs. So it is asked of the deadline.
    #
    # The page-wide `get_by_text("19.9.2026").first` that used to precede this
    # is gone with it, and for the mirror-image reason: on 19 September it can
    # be satisfied by `Saabus` and prove nothing. The scoped pair below says
    # everything it said and says it of the right element.
    deadline = page.locator(".metaline__value--deadline")
    expect(deadline).to_contain_text("19.9.2026")
    expect(deadline).not_to_contain_text("18.9.2026")


def test_a_medium_suggestion_is_saved_only_when_chosen_and_a_typed_title_stays(
    page, base_url, letter_pdf
) -> None:
    sign_in(page, base_url, SANDRA)
    matter_url = file_through_saabunud(page, base_url, [letter_pdf], title=TYPED_TITLE)
    run_worker([letter_pdf.name])

    page.goto(review_url(matter_url))
    # The person's own title is kept; the heading is offered beside it.
    expect(page.locator("#id_title")).to_have_value(TYPED_TITLE)
    use = page.locator('button[data-suggest-for="title"]')
    expect(use.first).to_be_visible()

    # The letterhead ministry is pre-ticked; the association the letter merely
    # names in passing is not — a mention is not a sender.
    ministry_box = page.locator("label.chip", has_text="Näidisministeerium").locator("input").first
    expect(ministry_box).to_be_checked()
    partner_box = (
        page.locator("label.chip", has_text="Näidisettevõtete liit").locator("input").first
    )
    expect(partner_box).not_to_be_checked()

    # Save without choosing the title suggestion: the typed title survives.
    page.get_by_role("button", name="Salvesta").click()
    page.wait_for_url(re.compile(r"/teemad/[0-9a-f-]{36}/$"))
    expect(page.get_by_role("heading", name=TYPED_TITLE)).to_be_visible()

    # Now choose it with «Kasuta» and save: the chosen value is what is stored.
    page.goto(review_url(matter_url))
    page.locator('button[data-suggest-for="title"]').first.click()
    expect(page.locator("#id_title")).to_have_value("Pakendiseaduse muutmise seaduse eelnõu")
    page.get_by_role("button", name="Salvesta").click()
    page.wait_for_url(re.compile(r"/teemad/[0-9a-f-]{36}/$"))
    expect(
        page.get_by_role("heading", name="Pakendiseaduse muutmise seaduse eelnõu")
    ).to_be_visible()
