"""The assisted review, as a lawyer meets it.

The rules are proved sentence by sentence in tests/test_assisted_intake.py.
What only a browser shows is the workflow: material filed through Saabunud,
read by the real worker, and the review page that pre-fills what it is sure
of, offers what it is not, keeps what the person already wrote, and saves
exactly what the person confirms.

Nothing here is real. The letter is generated by the synthetic corpus at
test time and the ministry is the seeded «Näidisministeerium».
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import pytest
from playwright.sync_api import expect

from e2e.conftest import SANDRA, sign_in
from e2e.test_document_content import run_worker

pytestmark = pytest.mark.e2e

REPOSITORY_ROOT = Path(__file__).resolve().parent.parent

TYPED_TITLE = "Sünteetiline pakendiseaduse teema — kasutaja enda pealkiri"
MECHANICAL_TITLE_STEM = "abistatud-katse-kaaskiri"

LETTER = """Näidisministeerium
Suur-Ameerika 1, Tallinn

Eesti Kaubandus-Tööstuskoda
Meie 05.09.2026 nr 1-4/26/9876-2

Pakendiseaduse muutmise seaduse eelnõu kooskõlastamiseks

Lugupeetud Koja esindajad

Saadame Teile kooskõlastamiseks pakendiseaduse muutmise seaduse eelnõu, mis on
registreeritud eelnõude infosüsteemis EIS toimik 26-0321. Eelnõuga muudetakse
pakendite ja jäätmete käitlemise korda ning keskkonnatasu määrasid. Näidisettevõtete
liit on eelnõu kooskõlastanud. Palume esitada arvamus hiljemalt 18. septembriks 2026.
Seadus jõustub 1. jaanuaril 2027.

Lugupidamisega
Mari Näidis
nõunik
E-post: mari.naidis@naidisministeerium.invalid
"""


@pytest.fixture
def letter_pdf(tmp_path: Path) -> Path:
    sys.path.insert(0, str(REPOSITORY_ROOT))
    from tests.synthetic_corpus import text_pdf

    path = tmp_path / f"{MECHANICAL_TITLE_STEM}.pdf"
    path.write_bytes(text_pdf([LETTER]))
    return path


@pytest.fixture
def message_eml(tmp_path: Path) -> Path:
    sys.path.insert(0, str(REPOSITORY_ROOT))
    from tests.synthetic_corpus import consultation_eml

    path = tmp_path / "abistatud-katse-kiri.eml"
    path.write_bytes(consultation_eml(attachments=False, inline_logo=False))
    return path


def file_through_saabunud(page, base_url: str, files: list[Path], title: str = "") -> str:
    page.goto(f"{base_url}/saabunud/lisa/")
    page.set_input_files("input[name='uploads']", [str(path) for path in files])
    if title:
        page.fill("input[name='title']", title)
    page.get_by_role("button", name="Registreeri ja loo teema").click()
    page.wait_for_url(re.compile(r"/teemad/[0-9a-f-]{36}/$"))
    return page.url


def review_url(matter_url: str) -> str:
    return f"{matter_url.rstrip('/')}/muuda/dokumendist/"


def test_the_review_pre_fills_what_it_is_sure_of_and_saves_what_the_person_confirms(
    page, base_url, screenshots, letter_pdf, message_eml
) -> None:
    sign_in(page, base_url, SANDRA)
    matter_url = file_through_saabunud(page, base_url, [letter_pdf, message_eml])

    # -- before extraction the page says so, and pre-fills nothing ---------
    page.goto(review_url(matter_url))
    expect(page.get_by_role("heading", name="Dokumendist leitud")).to_be_visible()
    expect(page.get_by_text("Teksti eraldamine on ootel")).to_be_visible()
    expect(page.get_by_text("vormil eeltäidetud")).to_have_count(0)
    expect(page.locator("#id_response_deadline")).to_have_value("")
    screenshots(page, "30-dokumendist-leitud-ootel")

    run_worker()

    # -- after extraction: suggestion, evidence, pre-filled blank fields ----
    page.goto(review_url(matter_url))
    expect(
        page.get_by_text("Palume esitada arvamus hiljemalt 18. septembriks 2026").first
    ).to_be_visible()
    expect(page.get_by_text("kirja päis").first).to_be_visible()
    expect(page.locator("#id_response_deadline")).to_have_value("18.9.2026")
    expect(page.locator("#id_title")).to_have_value("Pakendiseaduse muutmise seaduse eelnõu")
    expect(page.locator('input[name="track"][value="DOMESTIC"]')).to_be_checked()
    expect(page.get_by_text("vormil eeltäidetud").first).to_be_visible()
    # The message's sender, straight from its headers, with the address.
    expect(page.get_by_text("Saatja kontakt").first).to_be_visible()
    expect(page.get_by_text("kadri@naidisministeerium.invalid").first).to_be_visible()
    screenshots(page, "31-dokumendist-leitud")

    # -- the person changes a pre-filled value and saves --------------------
    page.fill("#id_response_deadline", "19.9.2026")
    page.get_by_role("button", name="Salvesta").click()
    page.wait_for_url(re.compile(r"/teemad/[0-9a-f-]{36}/$"))
    expect(
        page.get_by_role("heading", name="Pakendiseaduse muutmise seaduse eelnõu")
    ).to_be_visible()
    expect(page.get_by_text("19.9.2026").first).to_be_visible()
    expect(page.get_by_text("18.9.2026")).to_have_count(0)


def test_a_medium_suggestion_is_saved_only_when_chosen_and_a_typed_title_stays(
    page, base_url, letter_pdf
) -> None:
    sign_in(page, base_url, SANDRA)
    matter_url = file_through_saabunud(page, base_url, [letter_pdf], title=TYPED_TITLE)
    run_worker()

    page.goto(review_url(matter_url))
    # The person's own title is kept; the heading is offered beside it.
    expect(page.locator("#id_title")).to_have_value(TYPED_TITLE)
    use = page.locator('button[data-suggest-for="title"]')
    expect(use.first).to_be_visible()

    # The letterhead ministry is pre-ticked; the association the letter merely
    # names in passing is not — a mention is not a sender.
    ministry_box = page.locator("label.chip", has_text="Näidisministeerium").locator("input").first
    expect(ministry_box).to_be_checked()
    partner_box = (
        page.locator("label.chip", has_text="Näidisettevõtete liit").locator("input").first
    )
    expect(partner_box).not_to_be_checked()

    # Save without choosing the title suggestion: the typed title survives.
    page.get_by_role("button", name="Salvesta").click()
    page.wait_for_url(re.compile(r"/teemad/[0-9a-f-]{36}/$"))
    expect(page.get_by_role("heading", name=TYPED_TITLE)).to_be_visible()

    # Now choose it with «Kasuta» and save: the chosen value is what is stored.
    page.goto(review_url(matter_url))
    page.locator('button[data-suggest-for="title"]').first.click()
    expect(page.locator("#id_title")).to_have_value("Pakendiseaduse muutmise seaduse eelnõu")
    page.get_by_role("button", name="Salvesta").click()
    page.wait_for_url(re.compile(r"/teemad/[0-9a-f-]{36}/$"))
    expect(
        page.get_by_role("heading", name="Pakendiseaduse muutmise seaduse eelnõu")
    ).to_be_visible()
