# Generated by Django 5.2.17 on 2026-08-18 17:15

import app.core.ids
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('taxonomy', '0001_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatterReferenceSequence',
            fields=[
                ('year', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='aasta')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='viimane number')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'viitenumbrite jada',
                'verbose_name_plural': 'viitenumbrite jadad',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='viite aasta')),
                ('reference_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='viite number')),
                ('title', models.TextField(verbose_name='pealkiri')),
                ('alternate_titles', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Varasemad või allikapõhised pealkirjad, mis peavad jääma otsitavaks.', size=None, verbose_name='muud pealkirjad')),
                ('record_mode', models.CharField(choices=[('FULL', 'Täielik'), ('ARCHIVE', 'Arhiiv')], db_index=True, default='FULL', max_length=16, verbose_name='kirje liik')),
                ('origin', models.CharField(choices=[('NATIVE', 'Loodud süsteemis'), ('LEGACY_IMPORT', 'Imporditud registrist'), ('PROMOTED_LEGACY', 'Arhiivist aktiveeritud'), ('OTHER', 'Muu')], db_index=True, default='NATIVE', max_length=32, verbose_name='päritolu')),
                ('data_quality_tier', models.CharField(blank=True, choices=[('TIER_1', '1 — üleminekul kinnitatud aktiivne'), ('TIER_2', '2 — hiljutine sisukas ajalugu'), ('TIER_3', '3 — vanem registriarhiiv'), ('TIER_4', '4 — sidumata või kontrollimata')], default='', max_length=16, verbose_name='andmekvaliteedi tase')),
                ('source_era', models.CharField(blank=True, help_text='Töövihiku ajastu, mille reeglite järgi see kirje imporditi.', max_length=32, verbose_name='allika periood')),
                ('reporting_year', models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Püsiv aruandlusidentiteet, mis ei muutu, kui teema aastaid kestab.', null=True, verbose_name='aruandlusaasta')),
                ('track', models.CharField(blank=True, choices=[('DOMESTIC', 'Riigisisene'), ('EU_INITIATIVE', 'ELi algatus'), ('NATIONAL_TRANSPOSITION', 'ELi õiguse ülevõtmine'), ('STRATEGY', 'Strateegia või arengukava'), ('KODA_INITIATIVE', 'Koja algatus'), ('IMPLEMENTATION', 'Rakendamine või järelevalve'), ('OTHER', 'Muu')], default='', max_length=32, verbose_name='menetlusliik')),
                ('is_open', models.BooleanField(db_index=True, default=True, verbose_name='avatud')),
                ('disposition', models.CharField(blank=True, choices=[('COMPLETED', 'Lõpetatud või jõustunud'), ('SUPERSEDED', 'Asendatud järgnenud teemaga'), ('INITIATIVE_WITHDRAWN', 'Algataja loobus'), ('MONITORING_STOPPED', 'Koda lõpetas jälgimise'), ('NO_POSITION_FORMED', 'Seisukohta ei kujundatud'), ('RESPONSE_COMPLETE', 'Vastus esitatud ja järeltegevus tehtud'), ('DUPLICATE', 'Duplikaat või liidetud'), ('OTHER', 'Muu')], default='', max_length=32, verbose_name='lõpetamise põhjus')),
                ('disposition_reason', models.TextField(blank=True, verbose_name='lõpetamise selgitus')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='suletud')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='saabus')),
                ('response_deadline', models.DateField(blank=True, db_index=True, null=True, verbose_name='arvamuse tähtaeg')),
                ('position_summary', models.TextField(blank=True, verbose_name='Koja seisukoht')),
                ('rationale_summary', models.TextField(blank=True, verbose_name='põhjendus')),
                ('visibility', models.CharField(choices=[('NORMAL', 'Tavaline'), ('RESTRICTED', 'Piiratud')], db_index=True, default='NORMAL', max_length=16, verbose_name='nähtavus')),
                ('addressee_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matters_as_addressee', to='organisations.organisation', verbose_name='adressaat')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_matters', to=settings.AUTH_USER_MODEL, verbose_name='sulges')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborating_matters', to=settings.AUTH_USER_MODEL, verbose_name='kaastöötajad')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_matters', to=settings.AUTH_USER_MODEL, verbose_name='vastutaja')),
                ('policy_areas', models.ManyToManyField(blank=True, related_name='matters', to='taxonomy.policyarea', verbose_name='valdkonnad')),
                ('source_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matters_as_source', to='organisations.organisation', verbose_name='algataja või saatja')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matters', to='workflow.stagevocabulary', verbose_name='hetkeseis')),
            ],
            options={
                'verbose_name': 'teema',
                'verbose_name_plural': 'teemad',
                'ordering': ['-reference_year', '-reference_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TagAssignment',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Käsitsi'), ('IMPORTED', 'Imporditud'), ('APPROVED_RULE', 'Kinnitatud reegel')], default='MANUAL', max_length=32, verbose_name='allikas')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='kinnitatud')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_tag_assignments', to=settings.AUTH_USER_MODEL, verbose_name='kinnitas')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='matters.matter', verbose_name='teema')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='taxonomy.tag', verbose_name='silt')),
            ],
            options={
                'verbose_name': 'sildi seos',
                'verbose_name_plural': 'sildi seosed',
                'ordering': ['tag__name_et'],
            },
        ),
        migrations.AddField(
            model_name='matter',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='matters', through='matters.TagAssignment', to='taxonomy.tag', verbose_name='sildid'),
        ),
        migrations.AddConstraint(
            model_name='tagassignment',
            constraint=models.UniqueConstraint(fields=('matter', 'tag'), name='matters_unique_tag_per_matter'),
        ),
        migrations.AddIndex(
            model_name='matter',
            index=models.Index(fields=['owner', 'is_open'], name='matters_owner_open'),
        ),
        migrations.AddIndex(
            model_name='matter',
            index=models.Index(fields=['record_mode', 'is_open'], name='matters_mode_open'),
        ),
        migrations.AddIndex(
            model_name='matter',
            index=models.Index(condition=models.Q(('is_open', True)), fields=['response_deadline'], name='matters_open_deadline'),
        ),
        migrations.AddConstraint(
            model_name='matter',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_number__isnull', False), ('reference_year__isnull', False)), fields=('reference_year', 'reference_number'), name='matters_unique_human_reference'),
        ),
        migrations.AddConstraint(
            model_name='matter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reference_number__isnull', True), ('reference_year__isnull', True)), models.Q(('reference_number__isnull', False), ('reference_year__isnull', False)), _connector='OR'), name='matters_reference_year_and_number_together'),
        ),
        migrations.AddConstraint(
            model_name='matter',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='matters_title_required'),
        ),
        migrations.AddConstraint(
            model_name='matter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('disposition', ''), ('is_open', True)), models.Q(('is_open', False), ('record_mode', 'ARCHIVE')), models.Q(('closed_at__isnull', False), ('is_open', False), ('record_mode', 'FULL'), models.Q(('disposition', ''), _negated=True)), _connector='OR'), name='matters_closure_fields_consistent'),
        ),
    ]
