# Generated by Django 5.2.17 on 2026-08-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0004_entry_revision_append_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matter',
            name='origin',
            field=models.CharField(choices=[('NATIVE', 'Loodud süsteemis'), ('LEGACY_IMPORT', 'Imporditud registrist'), ('LEGACY_ONENOTE', "Imporditud OneNote'ist"), ('PROMOTED_LEGACY', 'Arhiivist aktiveeritud'), ('OTHER', 'Muu')], db_index=True, default='NATIVE', max_length=32, verbose_name='päritolu'),
        ),
    ]
