# Generated by Django 5.2.17 on 2026-08-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0005_matter_origin_onenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='matter',
            name='policy_area_other',
            field=models.CharField(blank=True, help_text='Vabatekst, kui ükski loetletud valdkond ei sobi. Ei ole taksonoomia: siit ei teki uut valdkonda ega silti, ja statistika ei loe seda kanoonilise valdkonna hulka.', max_length=400, verbose_name='muu valdkond'),
        ),
    ]
