# Generated by Django 5.2.17 on 2026-08-29 10:46

import app.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0011_matter_successor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalScratchpad',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True, default='', verbose_name='märkmed')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scratchpad', to=settings.AUTH_USER_MODEL, verbose_name='kasutaja')),
            ],
            options={
                'verbose_name': 'isiklik märkmik',
                'verbose_name_plural': 'isiklikud märkmikud',
                'ordering': ['-updated_at'],
            },
        ),
    ]
