# Generated by Django 5.2.17 on 2026-08-31 04:09

import app.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0012_personal_scratchpad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatterAssignmentNotice',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='vaadatud')),
                ('superseded_at', models.DateTimeField(blank=True, null=True, verbose_name='asendatud')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_notices_given', to=settings.AUTH_USER_MODEL, verbose_name='määraja')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_notices', to='matters.matter', verbose_name='teema')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_notices', to=settings.AUTH_USER_MODEL, verbose_name='saaja')),
            ],
            options={
                'verbose_name': 'uue asja teavitus',
                'verbose_name_plural': 'uue asja teavitused',
                'ordering': ['-created_at'],
                'indexes': [models.Index(condition=models.Q(('superseded_at__isnull', True), ('viewed_at__isnull', True)), fields=['recipient', '-created_at'], name='matters_active_notice_read')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('superseded_at__isnull', True), ('viewed_at__isnull', True)), fields=('matter', 'recipient'), name='matters_one_active_assignment_notice')],
            },
        ),
    ]
