# Generated by Django 5.2.17 on 2026-09-08 16:48

import app.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0013_matter_assignment_notice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatterIntakeSession',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='aegub')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='kasutatud')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matter_intake_sessions', to=settings.AUTH_USER_MODEL, verbose_name='omanik')),
            ],
            options={
                'verbose_name': 'teema ettevalmistus',
                'verbose_name_plural': 'teemade ettevalmistused',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatterIntakeFile',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordinal', models.PositiveIntegerField(verbose_name='järjekord')),
                ('storage_key', models.CharField(max_length=500, verbose_name='hoidla võti')),
                ('original_filename', models.CharField(max_length=400, verbose_name='algne failinimi')),
                ('mime_type', models.CharField(max_length=200, verbose_name='MIME tüüp')),
                ('size_bytes', models.BigIntegerField(verbose_name='suurus baitides')),
                ('sha256', models.CharField(max_length=64, verbose_name='SHA-256')),
                ('role', models.CharField(choices=[('INCOMING_AUTHORITY', 'Saabunud ametlik dokument'), ('ORIGINAL_EMAIL', 'Algne e-kiri'), ('MEMBER_FEEDBACK', 'Liikme tagasiside'), ('EXTERNAL_POSITION', 'Välise osapoole seisukoht'), ('KODA_SUBMISSION_FINAL', 'Koja väljasaadetud arvamus'), ('EMAIL_ATTACHMENT', 'E-kirja manus'), ('LEGACY_MATERIAL', 'Ajalooline materjal'), ('OUTCOME_EVIDENCE', 'Tulemuse tõend'), ('WORKING_DOCUMENT', 'Töödokument'), ('OTHER', 'Muu')], default='INCOMING_AUTHORITY', max_length=32, verbose_name='roll')),
                ('malware_scan_state', models.CharField(choices=[('PENDING', 'Ootel'), ('CLEAN', 'Puhas'), ('INFECTED', 'Nakatunud'), ('QUARANTINED', 'Karantiinis'), ('SKIPPED', 'Vahele jäetud'), ('ERROR', 'Viga')], default='PENDING', max_length=32, verbose_name='pahavarakontroll')),
                ('extraction_state', models.CharField(choices=[('PENDING', 'Ootel'), ('PROCESSING', 'Töötlemisel'), ('DONE', 'Tehtud'), ('FAILED', 'Ebaõnnestus'), ('NOT_APPLICABLE', 'Ei kohaldu')], db_index=True, default='PENDING', max_length=32, verbose_name='teksti eraldamine')),
                ('extraction_claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='töötlemine algas')),
                ('extraction_note', models.CharField(blank=True, max_length=300, verbose_name='eraldamise märkus')),
                ('text', models.JSONField(blank=True, default=list, verbose_name='eraldatud tekst')),
                ('text_character_count', models.PositiveIntegerField(default=0, verbose_name='tähemärke')),
                ('email_metadata', models.JSONField(blank=True, null=True, verbose_name='kirja metaandmed')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='eemaldatud')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='matters.matterintakesession', verbose_name='ettevalmistus')),
            ],
            options={
                'verbose_name': 'ettevalmistatud fail',
                'verbose_name_plural': 'ettevalmistatud failid',
                'ordering': ['session', 'ordinal'],
            },
        ),
        migrations.AddIndex(
            model_name='matterintakesession',
            index=models.Index(fields=['owner', '-created_at'], name='matters_intake_owner'),
        ),
        migrations.AddIndex(
            model_name='matterintakefile',
            index=models.Index(condition=models.Q(('extraction_state__in', ['PENDING', 'PROCESSING']), ('removed_at__isnull', True)), fields=['created_at'], name='matters_intake_queue'),
        ),
        migrations.AddConstraint(
            model_name='matterintakefile',
            constraint=models.UniqueConstraint(fields=('session', 'ordinal'), name='matters_intake_file_unique_ordinal'),
        ),
        migrations.AddConstraint(
            model_name='matterintakefile',
            constraint=models.UniqueConstraint(fields=('storage_key',), name='matters_intake_file_unique_storage_key'),
        ),
        migrations.AddConstraint(
            model_name='matterintakefile',
            constraint=models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-f]{64}$')), name='matters_intake_file_sha256_is_lowercase_hex'),
        ),
        migrations.AddConstraint(
            model_name='matterintakefile',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gte', 0)), name='matters_intake_file_size_not_negative'),
        ),
    ]
