# Generated by Django 5.2.17 on 2026-09-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0015_matter_legal_instruments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matterintakefile',
            name='extraction_state',
            field=models.CharField(choices=[('PENDING', 'Ootel'), ('PROCESSING', 'Töötlemisel'), ('DONE', 'Tehtud'), ('FAILED', 'Ebaõnnestus'), ('NOT_APPLICABLE', 'Ei kohaldu'), ('INTAKE_READ', 'Loetud teema loomisel')], db_index=True, default='PENDING', max_length=32, verbose_name='teksti eraldamine'),
        ),
    ]
