"""`Koosolek` and `Vastuseid` — the two facts the approved Teema target asks for.

Additive, and only additive. Nothing here touches a stored row: every existing
engagement keeps its `kind`, its `title`, its `url`, its `note` and its date, and
gains a `response_count` of NULL because nobody counted responses before the
question existed. There is no backfill and there is nothing to backfill — a
default of 0 would report «nobody answered» about consultations whose replies
were never tallied (docs/adr/0074 §5).

**The check constraint is dropped and recreated, not relaxed.** Widening the
vocabulary means the database has to accept `MEETING`, and PostgreSQL has no
in-place edit for a CHECK; the pair of operations is one ALTER TABLE in one
transaction, and the recreated constraint still refuses everything outside the
enumeration. `WEB_CALL`, `EMAIL_CAMPAIGN`, `SURVEY` and `OTHER` are all still in
it, so no row that satisfied the old constraint fails the new one — which is
what makes the reverse migration safe as well, on any database that has not
recorded a `MEETING` since (docs/adr/0074 §3).
"""

# Generated by Django 5.2.17 on 2026-09-11 04:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0016_alter_matterintakefile_extraction_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matterengagement',
            name='matters_engagement_kind_vocabulary',
        ),
        migrations.AddField(
            model_name='matterengagement',
            name='response_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='vastuseid'),
        ),
        migrations.AlterField(
            model_name='matterengagement',
            name='kind',
            field=models.CharField(choices=[('WEB_CALL', 'Kaasamiskutse veebis'), ('EMAIL_CAMPAIGN', 'E-kiri või kampaania'), ('SURVEY', 'Küsitlus'), ('MEETING', 'Koosolek'), ('OTHER', 'Muu')], db_index=True, default='OTHER', max_length=32, verbose_name='liik'),
        ),
        migrations.AddConstraint(
            model_name='matterengagement',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['WEB_CALL', 'EMAIL_CAMPAIGN', 'SURVEY', 'MEETING', 'OTHER'])), name='matters_engagement_kind_vocabulary'),
        ),
    ]
