"""`EMAIL_CAMPAIGN` is called `Kirjade voor`, and nothing else changes.

**Labels only. No schema, no data, no SQL.** `choices` is one of Django's
`non_db_attrs`, so `AlterField` here emits nothing at all against PostgreSQL —
this migration exists because the autodetector tracks the field's rendered
state, not because the column, its index, its default or the
`matters_engagement_kind_vocabulary` check constraint move. Every stored value
is untouched and no row is rewritten: `EMAIL_CAMPAIGN` was and remains
`EMAIL_CAMPAIGN`.

What it corrects is a label that existed three times over. The enum said
«E-kiri või kampaania», the `+ Kaasamine` chips said «Kirjade voor» and
`EngagementForm` said «Otsepostitus» — so somebody recorded a mailing under one
word and read it back in the chronology under another, having never been shown
the third. `Kirjade voor` is the department's own word and is now the only one
(post-QA R2-06, app/matters/enums.py `EngagementKind`).
"""

# Generated by Django 5.2.17 on 2026-09-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0017_engagement_meeting_and_response_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matterengagement",
            name="kind",
            field=models.CharField(
                choices=[
                    ("WEB_CALL", "Kaasamiskutse veebis"),
                    ("EMAIL_CAMPAIGN", "Kirjade voor"),
                    ("SURVEY", "Küsitlus"),
                    ("MEETING", "Koosolek"),
                    ("OTHER", "Muu"),
                ],
                db_index=True,
                default="OTHER",
                max_length=32,
                verbose_name="liik",
            ),
        ),
    ]
