"""`Kodulehe ülevaade` — one new table, and nothing else at all.

A single `CreateModel`. No column is added to an existing table, nothing is
read, nothing is rewritten, no constraint elsewhere is recreated and no index on
another table is rebuilt.

**There is no data migration and there is nothing to migrate.** This record did
not exist before, so every Matter in the register has zero of them — which is
what an empty table means, with no `RunPython`, no `RunSQL` and no backfill.
Deriving a planned overview from a note, a tag, an engagement of kind
`Kaasamiskutse veebis` or a koda.ee address somebody once pasted somewhere would
put an intention on the file that nobody stated (docs/adr/0081 §6).

The constraints arrive with the table rather than after it, so there is no
window in which a row could be written that the rule would later refuse: a
`PUBLISHED` row has an address and a publication date, every other row has
neither, and one address is filed at most once against one Matter.
"""

# Generated by Django 5.2.17 on 2026-09-14 12:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import app.core.ids


class Migration(migrations.Migration):
    dependencies = [
        ("matters", "0020_engagement_feedback_deadline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatterWebsiteOverview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=app.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "visibility_override",
                    models.CharField(
                        blank=True,
                        choices=[("NORMAL", "Tavaline"), ("RESTRICTED", "Piiratud")],
                        db_index=True,
                        default="",
                        help_text="Tühi tähendab, et nähtavus päritakse teemalt.",
                        max_length=16,
                        verbose_name="nähtavuse kitsendus",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Plaanis"),
                            ("PUBLISHED", "Avaldatud"),
                            ("CANCELLED", "Tühistatud"),
                        ],
                        db_index=True,
                        default="PLANNED",
                        max_length=16,
                        verbose_name="olek",
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, max_length=1000, verbose_name="link"),
                ),
                (
                    "published_on",
                    models.DateField(blank=True, null=True, verbose_name="avaldamise kuupäev"),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="avaldatuks märgitud"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="tühistatud"),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="oleku muutus"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planned_website_overviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="lisas",
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="website_overviews",
                        to="matters.matter",
                        verbose_name="teema",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_website_overviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="avaldamise kirjutas",
                    ),
                ),
            ],
            options={
                "verbose_name": "kodulehe ülevaade",
                "verbose_name_plural": "kodulehe ülevaated",
                "ordering": [
                    models.OrderBy(models.F("published_on"), descending=True, nulls_last=True),
                    "-created_at",
                    "-id",
                ],
                "indexes": [
                    models.Index(fields=["matter", "status"], name="matters_weboverview_mat_stat"),
                    models.Index(
                        fields=["matter", "-published_on"],
                        name="matters_weboverview_mat_pub",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["PLANNED", "PUBLISHED", "CANCELLED"])),
                        name="matters_website_overview_status_vocabulary",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "PUBLISHED"), _negated=True),
                            models.Q(
                                models.Q(("url", ""), _negated=True),
                                ("published_on__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="matters_website_overview_published_has_link_and_date",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status", "PUBLISHED"),
                            models.Q(("published_on__isnull", True), ("url", "")),
                            _connector="OR",
                        ),
                        name="matters_website_overview_unpublished_has_neither",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "PUBLISHED"), _negated=True),
                            ("published_at__isnull", False),
                            _connector="OR",
                        ),
                        name="matters_website_overview_published_has_timestamp",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "CANCELLED"), _negated=True),
                            ("cancelled_at__isnull", False),
                            _connector="OR",
                        ),
                        name="matters_website_overview_cancelled_has_timestamp",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "PUBLISHED")),
                        fields=("matter", "url"),
                        name="matters_website_overview_one_row_per_published_link",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("visibility_override__in", ["", "NORMAL", "RESTRICTED"])
                        ),
                        name="matters_website_overview_visibility_vocabulary",
                    ),
                ],
            },
        ),
    ]
