"""`Väline seisukoht` — one new table, and nothing else at all.

A single `CreateModel`. No column is added to an existing table, nothing is
read, nothing is rewritten, no constraint elsewhere is recreated and no index on
another table is rebuilt. `documents/0010_document_link_external_position` is
the other half of the release and is likewise additive; it depends on this one,
because a foreign key cannot name a table that does not exist yet.

**There is no data migration and there is nothing to migrate.** This record did
not exist before, so every Matter in the register has zero of them — which is
what an empty table means, with no `RunPython`, no `RunSQL` and no backfill.
Deriving a position from a `Märge` naming a ministry, from a document filed
under the `EXTERNAL_POSITION` role, or from a URL somebody once pasted into a
note would put an organisation's stated position on the file when nobody stated
that it was one (docs/adr/0084 §9).

The constraints arrive with the table rather than after it, so there is no
window in which a row could be written that the rule would later refuse: the
precision vocabulary is closed, and a row with no date carries no precision
either.
"""

# Generated by Django 5.2.17 on 2026-09-15 13:37

import app.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0022_matter_website_overview"),
        ("organisations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatterExternalPosition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=app.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "visibility_override",
                    models.CharField(
                        blank=True,
                        choices=[("NORMAL", "Tavaline"), ("RESTRICTED", "Piiratud")],
                        db_index=True,
                        default="",
                        help_text="Tühi tähendab, et nähtavus päritakse teemalt.",
                        max_length=16,
                        verbose_name="nähtavuse kitsendus",
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, max_length=1000, verbose_name="link"),
                ),
                (
                    "stated_on",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="kuupäev"
                    ),
                ),
                (
                    "stated_on_precision",
                    models.CharField(
                        choices=[
                            ("EXACT", "Täpne"),
                            ("MONTH", "Kuu täpsusega"),
                            ("QUARTER", "Kvartali täpsusega"),
                            ("HALF_YEAR", "Poolaasta täpsusega"),
                            ("YEAR", "Aasta täpsusega"),
                            ("INFERRED", "Tuletatud tekstist"),
                        ],
                        default="EXACT",
                        max_length=16,
                        verbose_name="kuupäeva täpsus",
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="selgitus")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_external_positions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="lisas",
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_positions",
                        to="matters.matterengagement",
                        verbose_name="seotud kaasamine",
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_positions",
                        to="matters.matter",
                        verbose_name="teema",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matter_external_positions",
                        to="organisations.organisation",
                        verbose_name="organisatsioon",
                    ),
                ),
            ],
            options={
                "verbose_name": "väline seisukoht",
                "verbose_name_plural": "välised seisukohad",
                "ordering": [
                    models.OrderBy(
                        models.F("stated_on"), descending=True, nulls_last=True
                    ),
                    "-created_at",
                    "-id",
                ],
                "indexes": [
                    models.Index(
                        fields=["matter", "-stated_on"],
                        name="matters_extpos_matter_date",
                    ),
                    models.Index(
                        fields=["matter", "organisation"],
                        name="matters_extpos_matter_org",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "stated_on_precision__in",
                                [
                                    "EXACT",
                                    "MONTH",
                                    "QUARTER",
                                    "HALF_YEAR",
                                    "YEAR",
                                    "INFERRED",
                                ],
                            )
                        ),
                        name="matters_external_position_precision_vocabulary",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("stated_on__isnull", False),
                            ("stated_on_precision", "EXACT"),
                            _connector="OR",
                        ),
                        name="matters_external_position_undated_is_exact",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("visibility_override__in", ["", "NORMAL", "RESTRICTED"])
                        ),
                        name="matters_external_position_visibility_vocabulary",
                    ),
                ],
            },
        ),
    ]
