# Generated by Django 5.2.17 on 2026-09-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matters", "0023_matter_external_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matterwebsiteoverview",
            options={
                "ordering": [
                    models.OrderBy(models.F("published_on"), descending=True, nulls_last=True),
                    "-created_at",
                    "-id",
                ],
                "verbose_name": "ülevaade / uudis",
                "verbose_name_plural": "ülevaated / uudised",
            },
        ),
    ]
