"""`Kaasamine` learns that a feedback wait can be finished, and what came back.

Three additive nullable/blank columns and one `CHECK`, and nothing else
(docs/adr/0085 §6).

* ``feedback_received`` — `Saadud tagasiside / arvamused`, a `TextField` that
  defaults to the empty string every existing row already means. Blank is a
  real answer for a completed round («keegi ei vastanud»), so there is nothing
  an existing row is being made to say.
* ``feedback_closed_at`` / ``feedback_closed_by`` — who ended the wait and
  when. `NULL` for every stored row, which is the truthful answer: no wait has
  ever been closed, because nothing could close one until now.
* ``matters_engagement_feedback_closure_needs_deadline`` — a closure timestamp
  requires the deadline that opened the wait. Every existing row satisfies it
  by carrying no timestamp at all, so PostgreSQL validates it against the
  table and finds nothing to refuse.

**No `RunPython`, no `RunSQL`, no backfill and no default that invents a
state.** A wait nobody opened is not a wait somebody completed, and deriving a
closure from `response_count`, from the deadline having passed, or from the
note would put a decision on the file that nobody made — the manufactured-fact
failure docs/adr/0078 §2 removed from `occurred_on`.

Nothing here touches the search projection, the archive projection or any
reporting table. `feedback_received` is deliberately outside
`app/search/child_indexing.py`, so no reindex follows this migration.
"""

# Generated by Django 5.2.17 on 2026-09-16 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0023_matter_external_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matterengagement',
            name='feedback_closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='tagasiside ootamine lõpetatud'),
        ),
        migrations.AddField(
            model_name='matterengagement',
            name='feedback_closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_engagement_feedback', to=settings.AUTH_USER_MODEL, verbose_name='tagasiside ootamise lõpetas'),
        ),
        migrations.AddField(
            model_name='matterengagement',
            name='feedback_received',
            field=models.TextField(blank=True, verbose_name='saadud tagasiside'),
        ),
        migrations.AddConstraint(
            model_name='matterengagement',
            constraint=models.CheckConstraint(condition=models.Q(('feedback_closed_at__isnull', True), ('feedback_deadline__isnull', False), _connector='OR'), name='matters_engagement_feedback_closure_needs_deadline'),
        ),
    ]
