# Generated by Django 5.2.17 on 2026-09-20 00:18

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0031_external_position_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matter',
            options={'base_manager_name': 'all_objects', 'ordering': ['-reference_year', '-reference_number', '-created_at'], 'verbose_name': 'teema', 'verbose_name_plural': 'teemad'},
        ),
        migrations.AlterModelManagers(
            name='matter',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='matter',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='kustutatud'),
        ),
        migrations.AddField(
            model_name='matter',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_matters', to=settings.AUTH_USER_MODEL, verbose_name='kustutaja'),
        ),
    ]
