# Generated by Django 5.2.17 on 2026-09-20 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0032_matter_deletion_tombstone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matterproceduraldevelopment',
            name='process_phase',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='etapp'),
        ),
        migrations.AddConstraint(
            model_name='matterproceduraldevelopment',
            constraint=models.CheckConstraint(condition=models.Q(('process_phase__in', ('', 'algus', 'vtk', 'koja-ettepanek', 'kooskolastus', 'valitsus', 'riigikogu', 'joustumine', 'eli-konsultatsioon', 'eesti-seisukoht', 'eli-menetlus', 'ulevotmine'))), name='matters_development_phase_vocabulary'),
        ),
    ]
