# Generated by Django 5.2.17 on 2026-09-20 20:26

import app.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0033_development_process_phase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatterTimelineStep',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility_override', models.CharField(blank=True, choices=[('NORMAL', 'Tavaline'), ('RESTRICTED', 'Piiratud')], db_index=True, default='', help_text='Tühi tähendab, et nähtavus päritakse teemalt.', max_length=16, verbose_name='nähtavuse kitsendus')),
                ('phase_key', models.CharField(max_length=32, verbose_name='etapp')),
                ('hidden', models.BooleanField(default=False, verbose_name='peidetud')),
                ('occurs_on', models.DateField(blank=True, null=True, verbose_name='kuupäev')),
                ('occurs_on_precision', models.CharField(choices=[('EXACT', 'Täpne'), ('MONTH', 'Kuu täpsusega'), ('QUARTER', 'Kvartali täpsusega'), ('HALF_YEAR', 'Poolaasta täpsusega'), ('YEAR', 'Aasta täpsusega'), ('INFERRED', 'Tuletatud tekstist')], default='EXACT', max_length=16, verbose_name='kuupäeva täpsus')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_steps', to='matters.matter', verbose_name='teema')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edited_timeline_steps', to=settings.AUTH_USER_MODEL, verbose_name='muutis')),
            ],
            options={
                'verbose_name': 'menetluse kulu samm',
                'verbose_name_plural': 'menetluse kulu sammud',
                'ordering': ['phase_key'],
                'constraints': [models.UniqueConstraint(fields=('matter', 'phase_key'), name='matters_timeline_step_unique'), models.CheckConstraint(condition=models.Q(('phase_key__in', ('algus', 'vtk', 'koja-ettepanek', 'kooskolastus', 'valitsus', 'riigikogu', 'joustumine', 'eli-konsultatsioon', 'eesti-seisukoht', 'eli-menetlus', 'ulevotmine'))), name='matters_timeline_step_phase_vocabulary'), models.CheckConstraint(condition=models.Q(('occurs_on_precision__in', ['EXACT', 'MONTH', 'QUARTER', 'HALF_YEAR', 'YEAR', 'INFERRED'])), name='matters_timeline_step_precision_vocabulary'), models.CheckConstraint(condition=models.Q(('occurs_on__isnull', False), ('occurs_on_precision', 'EXACT'), _connector='OR'), name='matters_timeline_step_undated_is_exact'), models.CheckConstraint(condition=models.Q(('visibility_override__in', ['', 'NORMAL', 'RESTRICTED'])), name='matters_timeline_step_visibility_vocabulary')],
            },
        ),
    ]
