"""Received feedback may name nobody.

The constraint is **relaxed**, never tightened: every row that satisfied the old
condition satisfies the new one, so no existing record can be made invalid by
this and nothing is rewritten, backfilled or reclassified.

Before: an organisation, or `RECEIVED` with a non-empty `source_label`.
After:  an organisation, or `RECEIVED`.

`DISCOVERED` is untouched and still requires an author — an unattributed
published opinion is an anonymous claim on a professional file (docs/adr/0091
§3.3). What changed is the other half: a lawyer writing down what a member said
on the telephone has neither a catalogue row nor a collection to name, and a
form that refuses to save until one of them exists is what puts invented names
on files (OWNER-01, docs/adr/0101).

The record still cannot be empty. `EXTERNAL_POSITION_NEEDS_SOURCE` means a
position, a link or a file is always present; what may be absent is whose it
was.
"""

# Generated by Django 5.2.17 on 2026-09-21 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0034_timeline_step"),
        ("organisations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="matterexternalposition",
            name="matters_external_position_author_or_label",
        ),
        migrations.AddConstraint(
            model_name="matterexternalposition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("organisation__isnull", False),
                    ("provenance", "RECEIVED"),
                    _connector="OR",
                ),
                name="matters_external_position_author_or_label",
            ),
        ),
    ]
