"""`Kustuta` on a user-created block of `Teema käik` — the `app.matters` half.

Two nullable columns per removable record type, and nothing else: `removed_at`
and `removed_by`. Additive, reversible and backfill-free — every existing row
is `NULL`, which reads as «still on the file», which is what every existing row
is (OWNER-04, docs/adr/0102).

**No data is migrated and none could be.** Removal is a decision a person
makes; there is no column, flag or heuristic in this schema from which a past
one could be reconstructed, and inventing them is the manufactured history the
product refuses.

`removed_at` is indexed because every business read now filters on it, through
each model's own `visible_to` chokepoint — the same place authorization is
applied, and therefore the same place this belongs.

`removed_by` is `SET_NULL`: a colleague's account may be removed while the
record stays, and the `ChangeEvent` carries the attribution that has to survive
regardless.
"""


# Generated by Django 5.2.17 on 2026-09-21 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0035_received_feedback_may_name_nobody"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="removed_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Täidetud, kui kirje on aktiivsest teema käigust eemaldatud.",
                null=True,
                verbose_name="eemaldatud",
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="eemaldaja",
            ),
        ),
        migrations.AddField(
            model_name="matterengagement",
            name="removed_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Täidetud, kui kirje on aktiivsest teema käigust eemaldatud.",
                null=True,
                verbose_name="eemaldatud",
            ),
        ),
        migrations.AddField(
            model_name="matterengagement",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="eemaldaja",
            ),
        ),
        migrations.AddField(
            model_name="matterexternalposition",
            name="removed_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Täidetud, kui kirje on aktiivsest teema käigust eemaldatud.",
                null=True,
                verbose_name="eemaldatud",
            ),
        ),
        migrations.AddField(
            model_name="matterexternalposition",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="eemaldaja",
            ),
        ),
        migrations.AddField(
            model_name="matterproceduraldevelopment",
            name="removed_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Täidetud, kui kirje on aktiivsest teema käigust eemaldatud.",
                null=True,
                verbose_name="eemaldatud",
            ),
        ),
        migrations.AddField(
            model_name="matterproceduraldevelopment",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="eemaldaja",
            ),
        ),
        migrations.AddField(
            model_name="matterwebsiteoverview",
            name="removed_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Täidetud, kui kirje on aktiivsest teema käigust eemaldatud.",
                null=True,
                verbose_name="eemaldatud",
            ),
        ),
        migrations.AddField(
            model_name="matterwebsiteoverview",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="eemaldaja",
            ),
        ),
    ]
