# Generated by Django 5.2.17 on 2026-09-24 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0038_website_overview_address_released_on_removal"),
    ]

    operations = [
        migrations.AddField(
            model_name="matterintakesession",
            name="matter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="matters.matter",
                verbose_name="loodud teema",
            ),
        ),
    ]
