# Generated by Django 5.2.17 on 2026-09-28 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0039_intake_session_records_the_matter_it_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mattertimelinestep',
            options={'ordering': ['phase_key', 'created_at'], 'verbose_name': 'menetluse kulu samm', 'verbose_name_plural': 'menetluse kulu sammud'},
        ),
        migrations.RemoveConstraint(
            model_name='mattertimelinestep',
            name='matters_timeline_step_unique',
        ),
        migrations.RemoveConstraint(
            model_name='mattertimelinestep',
            name='matters_timeline_step_phase_vocabulary',
        ),
        migrations.AddField(
            model_name='mattertimelinestep',
            name='after_key',
            field=models.CharField(blank=True, db_default='', default='', max_length=80, verbose_name='asukoht'),
        ),
        migrations.AddField(
            model_name='mattertimelinestep',
            name='title',
            field=models.CharField(blank=True, db_default='', default='', max_length=120, verbose_name='nimetus'),
        ),
        migrations.AlterField(
            model_name='mattertimelinestep',
            name='phase_key',
            field=models.CharField(blank=True, max_length=32, verbose_name='etapp'),
        ),
        migrations.AddConstraint(
            model_name='mattertimelinestep',
            constraint=models.UniqueConstraint(condition=models.Q(('phase_key', ''), _negated=True), fields=('matter', 'phase_key'), name='matters_timeline_step_unique'),
        ),
        migrations.AddConstraint(
            model_name='mattertimelinestep',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('phase_key__in', ('algus', 'vtk', 'koja-ettepanek', 'kooskolastus', 'valitsus', 'riigikogu', 'joustumine', 'eli-konsultatsioon', 'eesti-seisukoht', 'eli-menetlus', 'ulevotmine')), ('title', '')), models.Q(('phase_key', ''), models.Q(('title', ''), _negated=True)), _connector='OR'), name='matters_timeline_step_phase_vocabulary'),
        ),
        migrations.AddConstraint(
            model_name='mattertimelinestep',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('phase_key', ''), _negated=True), ('hidden', False), _connector='OR'), name='matters_timeline_step_added_is_shown'),
        ),
    ]
