"""`Ülevaade` vs `Uudis` stored on the record (docs/adr/0142 §C).

One additive column with a database default of `""`, so the release still
serving between `migrate` and the swap keeps inserting rows that satisfy it.
No row is rewritten: an existing record keeps `""` and reads its kind from its
koda.ee address where the path says (`MatterWebsiteOverview.effective_kind`).
"""

# Generated by Django 5.2.17 on 2026-10-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0046_save_once_and_plan_fulfilment'),
    ]

    operations = [
        migrations.AddField(
            model_name='matterwebsiteoverview',
            name='kind',
            field=models.CharField(blank=True, choices=[('OVERVIEW', 'Ülevaade'), ('NEWS', 'Uudis')], db_default='', default='', max_length=16, verbose_name='liik'),
        ),
    ]
