# Generated by Django 5.2.17 on 2026-08-18 17:15

import app.core.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(max_length=100, verbose_name='lähtesüsteem')),
                ('source_file_name', models.CharField(blank=True, max_length=400, verbose_name='lähtefail')),
                ('source_snapshot_sha256', models.CharField(blank=True, help_text='Baiditäpse lähteallika kontrollsumma.', max_length=64, verbose_name='hetktõmmise SHA-256')),
                ('importer_version', models.CharField(max_length=50, verbose_name='importija versioon')),
                ('contract_version', models.CharField(help_text='docs/data-contracts all oleva ajastulepingu versioon.', max_length=50, verbose_name='lepingu versioon')),
                ('started_at', models.DateTimeField(verbose_name='algas')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='lõppes')),
                ('source_row_count', models.PositiveIntegerField(default=0, verbose_name='ridu allikas')),
                ('created_matter_count', models.PositiveIntegerField(default=0, verbose_name='loodud teemasid')),
                ('matched_count', models.PositiveIntegerField(default=0, verbose_name='seotud ridu')),
                ('unmatched_count', models.PositiveIntegerField(default=0, verbose_name='sidumata ridu')),
                ('reconciliation_status', models.CharField(choices=[('RUNNING', 'Töötab'), ('COMPLETED', 'Lõpetatud'), ('COMPLETED_WITH_GAPS', 'Lõpetatud lünkadega'), ('FAILED', 'Ebaõnnestus')], default='RUNNING', max_length=32, verbose_name='võrdlusseis')),
                ('notes', models.TextField(blank=True, verbose_name='märkused')),
            ],
            options={
                'verbose_name': 'impordipartii',
                'verbose_name_plural': 'impordipartiid',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MatterSourceReference',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(max_length=100, verbose_name='lähtesüsteem')),
                ('source_file_name', models.CharField(blank=True, max_length=400)),
                ('source_sheet', models.CharField(blank=True, max_length=200)),
                ('source_row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('source_row_raw', models.JSONField(blank=True, default=dict, help_text='Lähterea väärtused täpselt nii, nagu need allikas olid.', verbose_name='algne rida')),
                ('source_title', models.TextField(blank=True)),
                ('source_date_raw', models.CharField(blank=True, help_text='Töötlemata kujul, kaasa arvatud järjenumbrid ja vigased väärtused.', max_length=200, verbose_name='algne kuupäev')),
                ('onenote_page_id', models.CharField(blank=True, max_length=200)),
                ('onenote_url', models.TextField(blank=True)),
                ('match_method', models.CharField(choices=[('DETERMINISTIC_IDENTIFIER', 'Determineeritud identifikaator'), ('REFERENCE_TOKEN', 'Viitenumber või ametlik ID'), ('EXACT_URL', 'Täpne URL'), ('FUZZY_CANDIDATE', 'Mitmesignaaliline sarnasus'), ('HUMAN_REVIEW', 'Inimese otsus'), ('UNMATCHED', 'Sidumata')], default='UNMATCHED', max_length=40, verbose_name='sidumise meetod')),
                ('match_confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='kindlus')),
                ('conflict_state', models.CharField(choices=[('NONE', 'Konflikti pole'), ('CONFLICTING_EVIDENCE', 'Vastuoluline tõendus'), ('RESOLVED_BY_REVIEW', 'Lahendatud ülevaatusega'), ('UNRESOLVED', 'Lahendamata')], default='NONE', max_length=32, verbose_name='konflikt')),
                ('reviewed_by', models.CharField(blank=True, max_length=200, verbose_name='üle vaadanud')),
                ('review_note', models.TextField(blank=True, verbose_name='ülevaatuse märkus')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_references', to='legacy_import.importbatch', verbose_name='impordipartii')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_references', to='matters.matter', verbose_name='teema')),
            ],
            options={
                'verbose_name': 'teema allikaviide',
                'verbose_name_plural': 'teema allikaviited',
                'ordering': ['source_system', 'source_sheet', 'source_row_number'],
                'indexes': [models.Index(fields=['matter'], name='legacy_source_matter'), models.Index(fields=['onenote_page_id'], name='legacy_source_onenote')],
                'constraints': [models.CheckConstraint(condition=models.Q(('match_confidence__isnull', True), models.Q(('match_confidence__gte', 0), ('match_confidence__lte', 1)), _connector='OR'), name='legacy_import_confidence_between_zero_and_one')],
            },
        ),
    ]
