# Generated by Django 5.2.17 on 2026-08-19 07:58

import app.core.ids
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_import', '0001_initial'),
        ('matters', '0004_entry_revision_append_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRowLedger',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_sheet', models.CharField(max_length=200, verbose_name='leht')),
                ('source_row_number', models.PositiveIntegerField(verbose_name='rida')),
                ('source_reference', models.CharField(blank=True, max_length=64, verbose_name='viide allikas')),
                ('outcome', models.CharField(choices=[('IMPORTABLE', 'Imporditav'), ('WOULD_CREATE', 'Loob uue teema'), ('WOULD_MATCH', 'Seob olemasoleva teemaga'), ('ALREADY_IMPORTED', 'Juba imporditud'), ('REVIEW_REQUIRED', 'Vajab ülevaatust'), ('NON_MATTER_ROW', 'Ei ole teemarida'), ('RESERVED_REFERENCE', 'Broneeritud viitenumber'), ('BLANK_PADDING', 'Tühi täiterida'), ('ERROR', 'Viga')], db_index=True, max_length=32, verbose_name='tulem')),
                ('anomalies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None, verbose_name='kõrvalekalded')),
                ('proposed_record_mode', models.CharField(blank=True, choices=[('FULL', 'Täielik kirje'), ('FULL_CANDIDATE', 'Täieliku kirje kandidaat'), ('ARCHIVE', 'Arhiiv')], default='', max_length=32, verbose_name='pakutud kirje liik')),
                ('proposed_record_mode_reason', models.TextField(blank=True, verbose_name='pakutud kirje liigi põhjus')),
                ('note', models.TextField(blank=True, verbose_name='märkus')),
            ],
            options={
                'verbose_name': 'impordirea kanne',
                'verbose_name_plural': 'impordiridade kanded',
                'ordering': ['import_batch', 'source_sheet', 'source_row_number'],
            },
        ),
        migrations.AddField(
            model_name='mattersourcereference',
            name='onenote_content_status',
            field=models.CharField(choices=[('NOT_APPLICABLE', 'Ei kohaldu'), ('NOT_IMPORTED', 'Importimata'), ('IMPORTED', 'Imporditud'), ('UNAVAILABLE', 'Kättesaamatu'), ('FAILED', 'Ebaõnnestus')], default='NOT_APPLICABLE', help_text='Kas lingi taga olev leht on imporditud. Link ise on muutumatu tõendus; see väli on tööseis ja seda tohib muuta.', max_length=32, verbose_name="OneNote'i sisu seis"),
        ),
        migrations.AddField(
            model_name='mattersourcereference',
            name='source_contract_version',
            field=models.CharField(blank=True, help_text='Millise aasta lepingu reeglite järgi see rida loeti.', max_length=50, verbose_name='ajastulepingu versioon'),
        ),
        migrations.AddField(
            model_name='mattersourcereference',
            name='source_era',
            field=models.CharField(blank=True, max_length=32, verbose_name='allika periood'),
        ),
        migrations.AddField(
            model_name='mattersourcereference',
            name='source_parser_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='parseri versioon'),
        ),
        migrations.AddField(
            model_name='mattersourcereference',
            name='source_snapshot_sha256',
            field=models.CharField(blank=True, db_index=True, help_text='Baiditäpne allika identiteet. Kordusimport sama tõmmise pealt tunneb rea selle järgi ära; uus tõmmis on uus tõendus, mitte vana muutmine.', max_length=64, verbose_name='hetktõmmise SHA-256'),
        ),
        migrations.AddConstraint(
            model_name='mattersourcereference',
            constraint=models.UniqueConstraint(condition=models.Q(('source_snapshot_sha256', ''), _negated=True), fields=('source_system', 'source_snapshot_sha256', 'source_sheet', 'source_row_number'), name='legacy_import_one_reference_per_source_row'),
        ),
        migrations.AddField(
            model_name='importrowledger',
            name='import_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_ledger', to='legacy_import.importbatch', verbose_name='impordipartii'),
        ),
        migrations.AddField(
            model_name='importrowledger',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_ledger_entries', to='matters.matter', verbose_name='teema'),
        ),
        migrations.AddIndex(
            model_name='importrowledger',
            index=models.Index(fields=['import_batch', 'outcome'], name='legacy_ledger_batch_outcome'),
        ),
        migrations.AddConstraint(
            model_name='importrowledger',
            constraint=models.UniqueConstraint(fields=('import_batch', 'source_sheet', 'source_row_number'), name='legacy_import_one_ledger_row_per_source_row'),
        ),
    ]
