# Generated by Django 5.2.17 on 2026-08-20 17:07

import app.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_legacy_material_role'),
        ('legacy_import', '0003_provenance_immutable_in_the_database'),
        ('matters', '0005_matter_origin_onenote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacySourcePage',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(choices=[('ONENOTE_DESKTOP', 'OneNote (töölauarakendus)'), ('ONENOTE_GRAPH_INVALID', 'OneNote (Graph, kehtetu eksport)')], default='ONENOTE_DESKTOP', max_length=32, verbose_name='lähtesüsteem')),
                ('source_page_id', models.CharField(max_length=300, verbose_name="OneNote'i lehe ID")),
                ('page_key', models.CharField(max_length=100, verbose_name='arhiivi lehe võti')),
                ('source_notebook', models.CharField(max_length=200, verbose_name='märkmik')),
                ('source_section', models.CharField(max_length=300, verbose_name='sektsioon')),
                ('source_section_group', models.CharField(blank=True, max_length=400, verbose_name='sektsioonirühm')),
                ('source_parent_page', models.CharField(blank=True, max_length=400, verbose_name='ülemleht')),
                ('title', models.TextField(blank=True, verbose_name='pealkiri')),
                ('page_level', models.PositiveSmallIntegerField(default=1, verbose_name='tase')),
                ('page_order', models.PositiveIntegerField(default=0, verbose_name='järjekord sektsioonis')),
                ('child_count', models.PositiveIntegerField(default=0, verbose_name='alamlehti')),
                ('page_role', models.CharField(choices=[('MATTER_LIKE', 'Võib olla teema'), ('CATEGORY_OR_CONTAINER', 'Kategooria või koondleht'), ('BACKGROUND', 'Taustainfo'), ('INDEX_OR_LIST', 'Sisukord või loend'), ('EMPTY_OR_PLACEHOLDER', 'Tühi või kohatäide'), ('UNCLEAR', 'Ebaselge')], db_index=True, default='UNCLEAR', max_length=32, verbose_name='lehe roll')),
                ('role_reason', models.TextField(blank=True, verbose_name='rolli põhjendus')),
                ('source_created_at', models.DateTimeField(blank=True, null=True, verbose_name='loodud allikas')),
                ('source_modified_at', models.DateTimeField(blank=True, null=True, verbose_name='muudetud allikas')),
                ('capture_id', models.CharField(max_length=100, verbose_name='hõive ID')),
                ('source_xml_storage_key', models.CharField(blank=True, help_text='Muutumatu lähtetõend. Ei renderdata kunagi otse kasutajale.', max_length=500, verbose_name='lähte-XML hoidla võti')),
                ('source_xml_sha256', models.CharField(blank=True, max_length=64, verbose_name='lähte-XML SHA-256')),
                ('derived_text', models.TextField(blank=True, verbose_name='tuletatud tekst')),
                ('blocks', models.JSONField(blank=True, default=list, verbose_name='plokid')),
                ('links', models.JSONField(blank=True, default=list, verbose_name='lingid')),
                ('reading_order_ambiguous', models.BooleanField(default=False, help_text='OneNote on vaba paigutusega; siin ei langenud XML-i ja paigutuse järjekord kokku.', verbose_name='lugemisjärjekord ebaselge')),
                ('reading_order_strategy', models.CharField(blank=True, max_length=64, verbose_name='järjestamise strateegia')),
                ('onenote_hyperlink', models.TextField(blank=True, help_text='Genereeritud link, mis avab lehe töölauarakenduses.', verbose_name="OneNote'i link")),
                ('reference_tokens', models.CharField(blank=True, max_length=300, verbose_name='viitenumbrid lehel')),
                ('text_characters', models.PositiveIntegerField(default=0, verbose_name='märke')),
                ('block_count', models.PositiveIntegerField(default=0, verbose_name='plokke')),
                ('file_count', models.PositiveIntegerField(default=0, verbose_name='faile')),
                ('file_bytes', models.BigIntegerField(default=0, verbose_name='failide maht')),
                ('first_imported_at', models.DateTimeField(verbose_name='esimest korda imporditud')),
                ('latest_imported_at', models.DateTimeField(verbose_name='viimati imporditud')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_pages', to='legacy_import.importbatch', verbose_name='impordipartii')),
            ],
            options={
                'verbose_name': 'ajalooline lähteleht',
                'verbose_name_plural': 'ajaloolised lähtelehed',
                'ordering': ['source_section', 'page_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMatchCandidate',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excel_reference', models.CharField(blank=True, max_length=40, verbose_name='Exceli viide')),
                ('excel_title', models.TextField(blank=True, verbose_name='Exceli pealkiri')),
                ('excel_onenote_url', models.TextField(blank=True, verbose_name="Exceli OneNote'i link")),
                ('candidate_class', models.CharField(choices=[('STRONG', 'Tugev'), ('REVIEW_REQUIRED', 'Vajab ülevaatust'), ('CONFLICT', 'Vastuolu'), ('UNLINKED_PAGE', 'Sidumata leht'), ('BROKEN_EXCEL_LINK', 'Katkine Exceli link')], db_index=True, max_length=32, verbose_name='kandidaadi klass')),
                ('score', models.FloatField(default=0.0, verbose_name='hinne')),
                ('match_signals', models.TextField(blank=True, verbose_name='signaalid')),
                ('conflicts', models.TextField(blank=True, verbose_name='vastuolud')),
                ('explanation', models.TextField(blank=True, verbose_name='selgitus')),
                ('state', models.CharField(choices=[('PENDING', 'Ootel'), ('LINKED', 'Seotud teemaga'), ('MATTER_CREATED', 'Loodi uus teema'), ('BACKGROUND', 'Taustamaterjal'), ('CONTAINER', 'Kategooria või koondleht'), ('REJECTED', 'Tagasi lükatud')], db_index=True, default='PENDING', max_length=16, verbose_name='olek')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='otsustatud')),
                ('decision_note', models.TextField(blank=True, verbose_name='otsuse märkus')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_decisions', to=settings.AUTH_USER_MODEL, verbose_name='otsustaja')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='legacy_import.importbatch', verbose_name='impordipartii')),
                ('matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_page_candidates', to='matters.matter', verbose_name='pakutud teema')),
                ('resulting_matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_candidates', to='matters.matter', verbose_name='tulemuseks olev teema')),
                ('source_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='legacy_import.legacysourcepage', verbose_name='lähteleht')),
            ],
            options={
                'verbose_name': 'ajaloo sidumiskandidaat',
                'verbose_name_plural': 'ajaloo sidumiskandidaadid',
                'ordering': ['candidate_class', '-score', 'excel_reference'],
            },
        ),
        migrations.CreateModel(
            name='LegacySourceResource',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_key', models.CharField(max_length=100, verbose_name='ressursi võti')),
                ('original_filename', models.CharField(max_length=500, verbose_name='algne failinimi')),
                ('resource_kind', models.CharField(choices=[('FILE_ATTACHMENT', 'Manustatud fail'), ('IMAGE', 'Pilt'), ('OTHER', 'Muu')], default='FILE_ATTACHMENT', max_length=32, verbose_name='liik')),
                ('source_block_ordinal', models.PositiveIntegerField(default=0, verbose_name='ploki järjekord')),
                ('sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='suurus baitides')),
                ('archive_relative_path', models.TextField(verbose_name='tee arhiivis')),
                ('is_inline', models.BooleanField(default=False, verbose_name='lehesisene')),
                ('source_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='legacy_import.legacysourcepage', verbose_name='lähteleht')),
            ],
            options={
                'verbose_name': 'ajalooline lähtefail',
                'verbose_name_plural': 'ajaloolised lähtefailid',
                'ordering': ['source_page', 'source_block_ordinal', 'original_filename'],
            },
        ),
        migrations.CreateModel(
            name='MatterSourcePage',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_kind', models.CharField(choices=[('PRIMARY', 'Peamine allikas'), ('RELATED', 'Seotud allikas'), ('BACKGROUND', 'Taustamaterjal')], default='PRIMARY', max_length=16, verbose_name='seose liik')),
                ('match_method', models.CharField(choices=[('EXCEL_EXACT_PAGE_ID', 'Exceli link — täpne lehe ID'), ('EXCEL_EXACT_LINK', 'Exceli link — täpne URL'), ('EXACT_REFERENCE_TOKEN', 'Täpne viitenumber'), ('REVIEWED_MATCH', 'Ülevaatusel kinnitatud'), ('ONENOTE_ONLY_MATTER', "OneNote'i-põhine teema"), ('MANUAL', 'Käsitsi lisatud')], max_length=32, verbose_name='sidumise viis')),
                ('match_class', models.CharField(choices=[('EXACT', 'Täpne'), ('REVIEWED', 'Ülevaadatud')], default='EXACT', max_length=16, verbose_name='sidumise klass')),
                ('source_audit_reference', models.CharField(blank=True, help_text='Millisest auditi reast see seos pärineb.', max_length=200, verbose_name='auditi viide')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='üle vaadatud')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_pages', to='matters.matter', verbose_name='teema')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_source_pages', to=settings.AUTH_USER_MODEL, verbose_name='ülevaataja')),
                ('source_page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matter_links', to='legacy_import.legacysourcepage', verbose_name='lähteleht')),
            ],
            options={
                'verbose_name': 'teema lähteleht',
                'verbose_name_plural': 'teema lähtelehed',
                'ordering': ['matter', 'relationship_kind', 'source_page'],
            },
        ),
        migrations.CreateModel(
            name='LegacySourceResourceImport',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('IMPORTED', 'Imporditud'), ('SKIPPED', 'Vahele jäetud'), ('FAILED', 'Ebaõnnestus')], db_index=True, default='IMPORTED', max_length=16, verbose_name='olek')),
                ('error_code', models.CharField(blank=True, max_length=64, verbose_name='vea kood')),
                ('error_detail', models.TextField(blank=True, verbose_name='vea kirjeldus')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_imports', to='documents.document', verbose_name='dokument')),
                ('document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_imports', to='documents.documentversion', verbose_name='tõendiversioon')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resource_imports', to='legacy_import.importbatch', verbose_name='impordipartii')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports', to='legacy_import.legacysourceresource', verbose_name='lähtefail')),
                ('matter_source_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_imports', to='legacy_import.mattersourcepage', verbose_name='teema lähteleht')),
            ],
            options={
                'verbose_name': 'lähtefaili import',
                'verbose_name_plural': 'lähtefailide import',
                'ordering': ['matter_source_page', 'resource'],
            },
        ),
        migrations.AddIndex(
            model_name='legacysourcepage',
            index=models.Index(fields=['source_section', 'page_order'], name='legacy_page_section_order'),
        ),
        migrations.AddIndex(
            model_name='legacysourcepage',
            index=models.Index(fields=['page_role'], name='legacy_page_role'),
        ),
        migrations.AddConstraint(
            model_name='legacysourcepage',
            constraint=models.UniqueConstraint(fields=('source_system', 'source_page_id'), name='legacy_one_row_per_source_page'),
        ),
        migrations.AddConstraint(
            model_name='legacysourcepage',
            constraint=models.UniqueConstraint(fields=('source_system', 'page_key'), name='legacy_one_row_per_archive_page_key'),
        ),
        migrations.AddIndex(
            model_name='historicalmatchcandidate',
            index=models.Index(fields=['state', 'candidate_class'], name='legacy_candidate_queue'),
        ),
        migrations.AddConstraint(
            model_name='historicalmatchcandidate',
            constraint=models.UniqueConstraint(fields=('source_page', 'excel_reference', 'candidate_class'), name='legacy_one_candidate_per_page_ref_class'),
        ),
        migrations.AddIndex(
            model_name='legacysourceresource',
            index=models.Index(fields=['source_page', 'source_block_ordinal'], name='legacy_res_order'),
        ),
        migrations.AddConstraint(
            model_name='legacysourceresource',
            constraint=models.UniqueConstraint(fields=('source_page', 'resource_key'), name='legacy_one_resource_per_page_and_key'),
        ),
        migrations.AddIndex(
            model_name='mattersourcepage',
            index=models.Index(fields=['source_page', 'matter'], name='legacy_link_by_page'),
        ),
        migrations.AddConstraint(
            model_name='mattersourcepage',
            constraint=models.UniqueConstraint(fields=('matter', 'source_page'), name='legacy_one_link_per_matter_and_page'),
        ),
        migrations.AddConstraint(
            model_name='legacysourceresourceimport',
            constraint=models.UniqueConstraint(fields=('matter_source_page', 'resource'), name='legacy_one_import_per_link_and_resource'),
        ),
    ]
