# Generated by Django 5.2.17 on 2026-08-21 13:17

import app.core.ids
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_legacy_material_role'),
        ('legacy_import', '0004_historical_corpus'),
        ('matters', '0005_matter_origin_onenote'),
        ('submissions', '0004_submission_sent_at_precision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpinionArchiveBatch',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_kind', models.CharField(choices=[('OPINIONS_ARCHIVE', 'Arvamuste arhiiv')], default='OPINIONS_ARCHIVE', max_length=32, verbose_name='allika liik')),
                ('archive_file_name', models.CharField(blank=True, max_length=400, verbose_name='arhiivi fail')),
                ('archive_sha256', models.CharField(max_length=64, verbose_name='arhiivi SHA-256')),
                ('archive_occurrence_count', models.PositiveIntegerField(default=0, verbose_name='esinemisi')),
                ('archive_distinct_sha_count', models.PositiveIntegerField(default=0, verbose_name='erinevaid baidijadasid')),
                ('excel_sha256', models.CharField(blank=True, max_length=64, verbose_name='Exceli SHA-256')),
                ('kodadash_artifact_name', models.CharField(blank=True, max_length=400, verbose_name='KodaDashi artefakt')),
                ('kodadash_artifact_sha256', models.CharField(blank=True, max_length=64, verbose_name='KodaDashi SHA-256')),
                ('onenote_capture_id', models.CharField(blank=True, max_length=100, verbose_name="OneNote'i hõive")),
                ('importer_version', models.CharField(max_length=50, verbose_name='importija versioon')),
                ('started_at', models.DateTimeField(verbose_name='algas')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='lõppes')),
                ('notes', models.TextField(blank=True, verbose_name='märkused')),
            ],
            options={
                'verbose_name': 'arvamuste arhiivi partii',
                'verbose_name_plural': 'arvamuste arhiivi partiid',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='OpinionArchiveItem',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive_sha256', models.CharField(max_length=64, verbose_name='arhiivi SHA-256')),
                ('archive_relative_path', models.TextField(verbose_name='tee arhiivis')),
                ('original_filename', models.CharField(max_length=500, verbose_name='algne failinimi')),
                ('filename_encoding', models.CharField(blank=True, max_length=40, verbose_name='failinime kodeering')),
                ('sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='suurus baitides')),
                ('detected_type', models.CharField(blank=True, max_length=100, verbose_name='tuvastatud tüüp')),
                ('filename_date', models.DateField(blank=True, null=True, verbose_name='failinime kuupäev')),
                ('filename_recipient', models.CharField(blank=True, max_length=300, verbose_name='failinime saaja')),
                ('filename_title', models.TextField(blank=True, verbose_name='failinime pealkiri')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='legacy_import.opinionarchivebatch', verbose_name='partii')),
            ],
            options={
                'verbose_name': 'arvamuste arhiivi kirje',
                'verbose_name_plural': 'arvamuste arhiivi kirjed',
                'ordering': ['filename_date', 'original_filename'],
            },
        ),
        migrations.CreateModel(
            name='OpinionArchiveMetadata',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(choices=[('KODADASH', 'KodaDash (tuletatud rikastus)')], default='KODADASH', max_length=32, verbose_name='lähtesüsteem')),
                ('source_artifact_name', models.CharField(max_length=400, verbose_name='artefakt')),
                ('source_artifact_sha256', models.CharField(max_length=64, verbose_name='artefakti SHA-256')),
                ('external_id', models.CharField(max_length=100, verbose_name='väline ID')),
                ('captured_at', models.DateTimeField(verbose_name='hõivatud')),
                ('recipient_raw', models.CharField(blank=True, max_length=400, verbose_name='saaja allikas')),
                ('recipient_normalized', models.CharField(blank=True, max_length=400, verbose_name='saaja normaliseeritud')),
                ('recipient_filter_group', models.CharField(blank=True, max_length=200, verbose_name='saaja filtrirühm')),
                ('recipient_type', models.CharField(blank=True, max_length=40, verbose_name='saaja liik')),
                ('recipient_secondary', models.CharField(blank=True, max_length=400, verbose_name='teine saaja')),
                ('recipient_review_required', models.BooleanField(default=False, verbose_name='saaja vajab ülevaatust')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='dokumendi kuupäev')),
                ('title', models.TextField(blank=True, verbose_name='pealkiri')),
                ('related_koda_news_url', models.TextField(blank=True, verbose_name='seotud uudise link')),
                ('related_koda_news_id', models.CharField(blank=True, max_length=100, verbose_name='uudise ID')),
                ('policy_thread_id', models.CharField(blank=True, max_length=100, verbose_name='teemalõnga ID')),
                ('public_import_eligible', models.BooleanField(blank=True, null=True, verbose_name='avalik import lubatud')),
                ('excluded_from_public', models.BooleanField(default=False, verbose_name='avalikust välja jäetud')),
                ('exclusion_reason', models.TextField(blank=True, verbose_name='väljajätmise põhjus')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='tuletatud väljad')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_rows', to='legacy_import.opinionarchiveitem', verbose_name='arhiivikirje')),
            ],
            options={
                'verbose_name': 'arvamuse tuletatud metaandmed',
                'verbose_name_plural': 'arvamuste tuletatud metaandmed',
                'ordering': ['item', 'source_system'],
            },
        ),
        migrations.CreateModel(
            name='OpinionMatchCandidate',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_class', models.CharField(choices=[('EXACT_BINARY_MATTER', 'Täpne bait ühel teemal'), ('EXACT_BINARY_MULTI_MATTER', 'Täpne bait mitmel teemal'), ('EXCEL_ONENOTE_EXACT', "Exceli ja OneNote'i täpne ühilduvus"), ('STRICT_MULTI_SIGNAL', 'Mitu sõltumatut täpset signaali'), ('REVIEW_REQUIRED', 'Vajab ülevaatust'), ('CONFLICT', 'Vastuolu'), ('UNMATCHED', 'Sidumata')], db_index=True, max_length=32, verbose_name='sidumise klass')),
                ('signals', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('EXACT_BINARY_ONENOTE', "Täpne bait OneNote'i lehel"), ('EXACT_ONENOTE_PAGE', 'Leht on registriga täpselt seotud'), ('EXACT_KODADASH_SOURCE_FILE', 'KodaDashi lähtefaili SHA-256'), ('EXACT_SENT_DATE', 'Sama väljasaatmise kuupäev'), ('EXACT_RECIPIENT', 'Sama adressaat'), ('EXACT_LAW_REFERENCE', 'Sama õigusakti viide'), ('EXACT_TITLE_TOKEN', 'Sama eristav pealkirjasõna'), ('SENT_DATE_WITHIN_ONE_DAY', 'Kuupäev erineb ühe päeva'), ('RELATED_KODA_NEWS_SUPPORT', 'KodaDashi uudiselink toetab'), ('POLICY_THREAD_SUPPORT', 'KodaDashi teemalõng toetab')], max_length=40), blank=True, default=list, size=None, verbose_name='signaalid')),
                ('conflicts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('DATE_CONFLICT', 'Kuupäevad ei klapi'), ('RECIPIENT_CONFLICT', 'Adressaadid ei klapi'), ('TITLE_CONFLICT', 'Pealkirjad ei klapi'), ('YEAR_CONFLICT', 'Aastad ei klapi'), ('MULTIPLE_MATTER_BINARY', 'Sama bait mitmel teemal'), ('MULTIPLE_SOURCE_ROWS', 'Mitu registri rida sobib'), ('UNKNOWN_RECIPIENT', 'Adressaat tundmatu'), ('EXCEL_DIRECTION_NOT_COMPARABLE', 'Registri vastaspool on saatja, mitte adressaat'), ('EXISTING_SUBMISSION_DISAGREES', 'Olemasolev arvamus ütleb muud')], max_length=40), blank=True, default=list, size=None, verbose_name='vastuolud')),
                ('excel_reference', models.CharField(blank=True, max_length=40, verbose_name='registri viide')),
                ('excel_sent_date', models.DateField(blank=True, null=True, verbose_name='registri VÄLJA')),
                ('excel_addressee_raw', models.CharField(blank=True, max_length=400, verbose_name='registri KELLELE')),
                ('onenote_page_key', models.CharField(blank=True, max_length=100, verbose_name="OneNote'i leht")),
                ('onenote_page_title', models.TextField(blank=True, verbose_name="OneNote'i lehe pealkiri")),
                ('onenote_section', models.CharField(blank=True, max_length=300, verbose_name="OneNote'i sektsioon")),
                ('onenote_block_ordinal', models.PositiveIntegerField(blank=True, null=True, verbose_name='ploki järjekord')),
                ('competing_matter_count', models.PositiveIntegerField(default=0, verbose_name='konkureerivaid')),
                ('explanation', models.TextField(blank=True, verbose_name='selgitus')),
                ('state', models.CharField(choices=[('PENDING', 'Ootel'), ('APPLIED', 'Rakendatud'), ('LINKED', 'Seotud teemaga'), ('REJECTED', 'Tagasi lükatud'), ('DUPLICATE', 'Duplikaat'), ('NOT_AN_OPINION', 'Ei ole arvamus'), ('DEFERRED', 'Edasi lükatud')], db_index=True, default='PENDING', max_length=20, verbose_name='olek')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='otsustatud')),
                ('decision_note', models.TextField(blank=True, verbose_name='otsuse märkus')),
                ('review_approves_submission', models.BooleanField(default=False, verbose_name='ülevaataja kinnitas saatmise')),
                ('reviewed_sent_date', models.DateField(blank=True, null=True, verbose_name='ülevaatusel kinnitatud kuupäev')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='legacy_import.opinionarchivebatch', verbose_name='partii')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opinion_decisions', to=settings.AUTH_USER_MODEL, verbose_name='otsustaja')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='legacy_import.opinionarchiveitem', verbose_name='arhiivikirje')),
                ('matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opinion_candidates', to='matters.matter', verbose_name='teema')),
            ],
            options={
                'verbose_name': 'arvamuse sidumiskandidaat',
                'verbose_name_plural': 'arvamuste sidumiskandidaadid',
                'ordering': ['match_class', 'item__filename_date', 'item__original_filename'],
            },
        ),
        migrations.CreateModel(
            name='OpinionSubmissionImport',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_submission', models.BooleanField(default=False, verbose_name='loodi siin')),
                ('match_class', models.CharField(choices=[('EXACT_BINARY_MATTER', 'Täpne bait ühel teemal'), ('EXACT_BINARY_MULTI_MATTER', 'Täpne bait mitmel teemal'), ('EXCEL_ONENOTE_EXACT', "Exceli ja OneNote'i täpne ühilduvus"), ('STRICT_MULTI_SIGNAL', 'Mitu sõltumatut täpset signaali'), ('REVIEW_REQUIRED', 'Vajab ülevaatust'), ('CONFLICT', 'Vastuolu'), ('UNMATCHED', 'Sidumata')], max_length=32, verbose_name='sidumise klass')),
                ('sent_date_basis', models.CharField(blank=True, choices=[('OUTGOING_EMAIL', 'Väljuva kirja ajatempel'), ('EXCEL_OUT_DATE', 'Registri VÄLJA kuupäev'), ('OPINION_DOCUMENT_DATE', 'Dokumendi enda kuupäev'), ('REVIEWED_DECISION', 'Ülevaatusel otsustatud')], max_length=32, verbose_name='kuupäeva alus')),
                ('recipient_basis', models.CharField(choices=[('OUTGOING_EMAIL', 'Väljuva kirja To/CC'), ('OPINION_DOCUMENT', 'Arvamuse enda adressaat'), ('KODADASH_RAW', 'KodaDashi töötlemata saaja'), ('EXCEL_ADDRESSEE', 'Registri KELLELE'), ('REVIEWED_MAPPING', 'Ülevaatusel kinnitatud vastendus'), ('UNRESOLVED', 'Lahendamata')], default='UNRESOLVED', max_length=32, verbose_name='saaja alus')),
                ('matter_match_signals', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None, verbose_name='teema signaalid')),
                ('note', models.TextField(blank=True, verbose_name='märkus')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_imports', to='legacy_import.opinionarchivebatch', verbose_name='partii')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_imports', to='legacy_import.opinionmatchcandidate', verbose_name='kandidaat')),
                ('document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opinion_archive_imports', to='documents.documentversion', verbose_name='tõendiversioon')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_imports', to='legacy_import.opinionarchiveitem', verbose_name='arhiivikirje')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_imports', to='submissions.submission', verbose_name='arvamus')),
            ],
            options={
                'verbose_name': 'arvamuse arhiiviimport',
                'verbose_name_plural': 'arvamuste arhiiviimport',
                'ordering': ['submission', 'item'],
            },
        ),
        migrations.AddIndex(
            model_name='opinionarchiveitem',
            index=models.Index(fields=['sha256'], name='opinion_item_sha'),
        ),
        migrations.AddIndex(
            model_name='opinionarchiveitem',
            index=models.Index(fields=['filename_date'], name='opinion_item_file_date'),
        ),
        migrations.AddConstraint(
            model_name='opinionarchiveitem',
            constraint=models.UniqueConstraint(fields=('archive_sha256', 'archive_relative_path', 'sha256'), name='opinion_one_item_per_archive_path'),
        ),
        migrations.AddConstraint(
            model_name='opinionarchiveitem',
            constraint=models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-f]{64}$')), name='opinion_item_sha256_is_lowercase_hex'),
        ),
        migrations.AddIndex(
            model_name='opinionarchivemetadata',
            index=models.Index(fields=['source_system', 'external_id'], name='opinion_meta_external'),
        ),
        migrations.AddConstraint(
            model_name='opinionarchivemetadata',
            constraint=models.UniqueConstraint(fields=('item', 'source_system', 'source_artifact_sha256', 'external_id'), name='opinion_one_metadata_row_per_artifact'),
        ),
        migrations.AddIndex(
            model_name='opinionmatchcandidate',
            index=models.Index(fields=['state', 'match_class'], name='opinion_candidate_queue'),
        ),
        migrations.AddConstraint(
            model_name='opinionmatchcandidate',
            constraint=models.UniqueConstraint(condition=models.Q(('matter__isnull', False)), fields=('item', 'matter', 'match_class'), name='opinion_one_candidate_per_item_matter_class'),
        ),
        migrations.AddConstraint(
            model_name='opinionmatchcandidate',
            constraint=models.UniqueConstraint(condition=models.Q(('matter__isnull', True)), fields=('item', 'match_class'), name='opinion_one_matterless_candidate_per_item_class'),
        ),
        migrations.AddConstraint(
            model_name='opinionsubmissionimport',
            constraint=models.UniqueConstraint(fields=('item', 'submission'), name='opinion_one_import_per_item_and_submission'),
        ),
    ]
