# Generated by Django 5.2.17 on 2026-08-21 13:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add `SAME_DAY_BUNDLE` to the conflict vocabulary.

    The rule it names came out of the real corpus after the models were
    written: several archive files landing on one Matter on one day are one
    letter with annexes, not several sent actions. A choices-only change, so
    nothing is rewritten in the table.
    """

    dependencies = [
        ("legacy_import", "0005_opinionarchivebatch_opinionarchiveitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opinionmatchcandidate",
            name="conflicts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DATE_CONFLICT", "Kuupäevad ei klapi"),
                        ("RECIPIENT_CONFLICT", "Adressaadid ei klapi"),
                        ("TITLE_CONFLICT", "Pealkirjad ei klapi"),
                        ("YEAR_CONFLICT", "Aastad ei klapi"),
                        ("MULTIPLE_MATTER_BINARY", "Sama bait mitmel teemal"),
                        ("MULTIPLE_SOURCE_ROWS", "Mitu registri rida sobib"),
                        ("UNKNOWN_RECIPIENT", "Adressaat tundmatu"),
                        (
                            "EXCEL_DIRECTION_NOT_COMPARABLE",
                            "Registri vastaspool on saatja, mitte adressaat",
                        ),
                        ("EXISTING_SUBMISSION_DISAGREES", "Olemasolev arvamus ütleb muud"),
                        ("SAME_DAY_BUNDLE", "Mitu faili samal päeval samal teemal"),
                    ],
                    max_length=40,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="vastuolud",
            ),
        ),
    ]
