# Generated by Django 5.2.17 on 2026-08-22 03:24

import app.core.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_import', '0006_alter_opinionmatchcandidate_conflicts'),
        ('matters', '0006_policy_area_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentRegisterState',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_snapshot_sha256', models.CharField(db_index=True, help_text='Milline töövihik selle tõlgenduse andis.', max_length=64, verbose_name='hetktõmmise SHA-256')),
                ('source_sheet', models.CharField(blank=True, max_length=200, verbose_name='leht')),
                ('source_row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('CURRENT', 'Jooksev töö'), ('RETIRED', 'Registris lõppenud'), ('SUPERSEDED', 'Jätkub teise teema all'), ('REVIEW_REQUIRED', 'Vajab ülevaatust')], db_index=True, max_length=32, verbose_name='registri seis')),
                ('status_label', models.CharField(blank=True, help_text='Allika sõnastuses, tõlgendamata.', max_length=200, verbose_name='HETKESEIS')),
                ('opinion_sent_date', models.DateField(blank=True, help_text='Registri märge arvamuse väljasaatmise kohta. Ei ole Submission.', null=True, verbose_name='VÄLJA')),
                ('next_action_text', models.TextField(blank=True, verbose_name='JÄRGMISEKS')),
                ('owner_raw', models.CharField(blank=True, help_text='Eesnimi allika sõnastuses; kanooniline vastutaja on Matter.owner.', max_length=200, verbose_name='VASTUTAJA allikas')),
                ('owner_resolved', models.BooleanField(default=False, help_text='Kas allika nimi vastab üheselt kasutajale.', verbose_name='vastutaja tuvastatud')),
                ('continues_under_reference', models.CharField(blank=True, help_text='AAAA_N, kui JÄRGMISEKS ütleb üheselt, kuhu töö liikus.', max_length=40, verbose_name='jätkub teema all')),
                ('review_reason', models.TextField(blank=True, verbose_name='ülevaatuse põhjus')),
                ('observed_at', models.DateTimeField(verbose_name='tuletatud')),
                ('matter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_register_state', to='matters.matter', verbose_name='teema')),
                ('source_reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_states', to='legacy_import.mattersourcereference', verbose_name='allikaviide')),
            ],
            options={
                'verbose_name': 'registri hetkeseis',
                'verbose_name_plural': 'registri hetkeseisud',
                'ordering': ['-source_sheet', 'matter'],
                'indexes': [models.Index(fields=['currency', 'opinion_sent_date'], name='legacy_register_drafting')],
                'constraints': [models.CheckConstraint(condition=models.Q(('currency__in', ['CURRENT', 'RETIRED', 'SUPERSEDED', 'REVIEW_REQUIRED'])), name='legacy_register_currency_vocabulary'), models.CheckConstraint(condition=models.Q(models.Q(('currency', 'SUPERSEDED'), models.Q(('continues_under_reference', ''), _negated=True)), models.Q(models.Q(('currency', 'SUPERSEDED'), _negated=True), ('continues_under_reference', '')), _connector='OR'), name='legacy_register_continuation_only_when_superseded')],
            },
        ),
    ]
