# Generated by Django 5.2.17 on 2026-08-22 09:18

import app.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_import', '0007_final_register_cutover_state'),
        ('matters', '0006_policy_area_other'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpinionArchiveBinary',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sha256', models.CharField(max_length=64, unique=True, verbose_name='SHA-256')),
                ('size_bytes', models.BigIntegerField(verbose_name='suurus baitides')),
                ('mime_type', models.CharField(max_length=200, verbose_name='MIME tüüp')),
                ('storage_key', models.CharField(max_length=500, unique=True, verbose_name='hoidla võti')),
                ('source_archive_sha256', models.CharField(max_length=64, verbose_name='arhiivi SHA-256')),
                ('materialized_at', models.DateTimeField(verbose_name='jäädvustatud')),
            ],
            options={
                'verbose_name': 'arvamuste arhiivi bait',
                'verbose_name_plural': 'arvamuste arhiivi baidid',
                'ordering': ['-materialized_at'],
            },
        ),
        migrations.CreateModel(
            name='OpinionArchiveMatterLink',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basis', models.CharField(choices=[('REVIEWED', 'Ülevaatusel kinnitatud'), ('EXACT_BINARY', 'Täpne bait teema juures'), ('APPLIED_SUBMISSION', 'Kanoonilise arvamuse kaudu')], max_length=32, verbose_name='alus')),
                ('linked_at', models.DateTimeField(verbose_name='seotud')),
                ('note', models.TextField(blank=True, verbose_name='märkus')),
            ],
            options={
                'verbose_name': 'arvamuse arhiivi teemaseos',
                'verbose_name_plural': 'arvamuste arhiivi teemaseosed',
                'ordering': ['-linked_at'],
            },
        ),
        migrations.CreateModel(
            name='OpinionArchiveText',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('PENDING', 'Ootel'), ('DONE', 'Tekst olemas'), ('NO_TEXT_LAYER', 'Tekstikihti ei ole'), ('BLOCKED', 'Turvapoliitika ei luba eraldamist'), ('FAILED', 'Eraldamine ebaõnnestus')], db_index=True, default='PENDING', max_length=32, verbose_name='olek')),
                ('body', models.TextField(blank=True, verbose_name='tekst')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='lehti')),
                ('characters', models.PositiveIntegerField(default=0, verbose_name='märke')),
                ('parser', models.CharField(blank=True, max_length=100, verbose_name='parser')),
                ('parser_version', models.CharField(blank=True, max_length=50, verbose_name='parseri versioon')),
                ('extracted_at', models.DateTimeField(blank=True, null=True, verbose_name='eraldatud')),
                ('note', models.TextField(blank=True, verbose_name='märkus')),
            ],
            options={
                'verbose_name': 'arvamuse arhiivi tekst',
                'verbose_name_plural': 'arvamuste arhiivi tekstid',
                'ordering': ['-extracted_at'],
            },
        ),
        migrations.AddField(
            model_name='opinionmatchcandidate',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='asendatud'),
        ),
        migrations.AddField(
            model_name='opinionmatchcandidate',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='legacy_import.opinionmatchcandidate', verbose_name='asendatud kandidaadiga'),
        ),
        migrations.AddField(
            model_name='opinionmatchcandidate',
            name='supersession_reason',
            field=models.TextField(blank=True, verbose_name='asendamise põhjus'),
        ),
        migrations.AlterField(
            model_name='opinionmatchcandidate',
            name='state',
            field=models.CharField(choices=[('PENDING', 'Ootel'), ('APPLIED', 'Rakendatud'), ('LINKED', 'Seotud teemaga'), ('REJECTED', 'Tagasi lükatud'), ('DUPLICATE', 'Duplikaat'), ('NOT_AN_OPINION', 'Ei ole arvamus'), ('DEFERRED', 'Edasi lükatud'), ('SUPERSEDED', 'Asendatud uuema tõendiga')], db_index=True, default='PENDING', max_length=20, verbose_name='olek'),
        ),
        migrations.AddConstraint(
            model_name='opinionmatchcandidate',
            constraint=models.CheckConstraint(condition=models.Q(('superseded_by', models.F('id')), _negated=True), name='opinion_candidate_does_not_supersede_itself'),
        ),
        migrations.AddConstraint(
            model_name='opinionarchivebinary',
            constraint=models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-f]{64}$')), name='opinion_binary_sha256_is_lowercase_hex'),
        ),
        migrations.AddConstraint(
            model_name='opinionarchivebinary',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gte', 0)), name='opinion_binary_size_is_not_negative'),
        ),
        migrations.AddField(
            model_name='opinionarchiveitem',
            name='binary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='legacy_import.opinionarchivebinary', verbose_name='bait'),
        ),
        migrations.AddField(
            model_name='opinionarchivematterlink',
            name='binary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matter_links', to='legacy_import.opinionarchivebinary', verbose_name='bait'),
        ),
        migrations.AddField(
            model_name='opinionarchivematterlink',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matter_links', to='legacy_import.opinionmatchcandidate', verbose_name='kandidaat'),
        ),
        migrations.AddField(
            model_name='opinionarchivematterlink',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matter_links', to='legacy_import.opinionarchiveitem', verbose_name='arhiivikirje'),
        ),
        migrations.AddField(
            model_name='opinionarchivematterlink',
            name='linked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opinion_archive_links', to=settings.AUTH_USER_MODEL, verbose_name='siduja'),
        ),
        migrations.AddField(
            model_name='opinionarchivematterlink',
            name='matter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinion_archive_links', to='matters.matter', verbose_name='teema'),
        ),
        migrations.AddField(
            model_name='opinionarchivetext',
            name='binary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='legacy_import.opinionarchivebinary', verbose_name='bait'),
        ),
        migrations.AddIndex(
            model_name='opinionarchivematterlink',
            index=models.Index(fields=['matter'], name='opinion_link_matter'),
        ),
        migrations.AddConstraint(
            model_name='opinionarchivematterlink',
            constraint=models.UniqueConstraint(fields=('binary', 'matter'), name='opinion_one_archive_link_per_binary_matter'),
        ),
    ]
