# Generated by Django 5.2.17 on 2026-08-22 09:46

import app.core.ids
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_import', '0008_opinion_archive_binary'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpinionArchiveSearchDocument',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(blank=True, verbose_name='pealkiri')),
                ('recipient', models.TextField(blank=True, verbose_name='saaja')),
                ('occurrence_paths', models.TextField(blank=True, verbose_name='teed arhiivis')),
                ('identifiers', models.TextField(blank=True, verbose_name='tunnused')),
                ('body_text', models.TextField(blank=True, verbose_name='sisu')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='dokumendi kuupäev')),
                ('source_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='aasta')),
                ('match_class', models.CharField(blank=True, max_length=32, verbose_name='sidumise klass')),
                ('review_state', models.CharField(blank=True, max_length=20, verbose_name='ülevaatuse olek')),
                ('has_body_text', models.BooleanField(default=False, verbose_name='sisu olemas')),
                ('is_linked', models.BooleanField(default=False, verbose_name='teemaga seotud')),
                ('has_submission', models.BooleanField(default=False, verbose_name='kanooniline arvamus')),
                ('occurrence_count', models.PositiveIntegerField(default=0, verbose_name='esinemisi')),
                ('search_estonian', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('search_simple', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('index_version', models.CharField(default='1', editable=False, max_length=16, verbose_name='indeksi versioon')),
                ('indexed_at', models.DateTimeField(blank=True, null=True, verbose_name='indekseeritud')),
                ('binary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_document', to='legacy_import.opinionarchivebinary', verbose_name='bait')),
            ],
            options={
                'verbose_name': 'arvamuste arhiivi otsingurida',
                'verbose_name_plural': 'arvamuste arhiivi otsinguread',
                'ordering': ['-document_date', '-created_at', 'pk'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_estonian'], name='opinion_arch_est_gin'), django.contrib.postgres.indexes.GinIndex(fields=['search_simple'], name='opinion_arch_simple_gin'), models.Index(fields=['source_year'], name='opinion_arch_year'), models.Index(fields=['review_state'], name='opinion_arch_state'), models.Index(fields=['-document_date', '-created_at'], name='opinion_arch_order')],
            },
        ),
    ]
