# Generated by Django 5.2.17 on 2026-08-22 10:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_import', '0009_opinion_archive_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinionmatchcandidate',
            name='match_class',
            field=models.CharField(choices=[('EXACT_BINARY_MATTER', 'Täpne bait ühel teemal'), ('EXACT_BINARY_MULTI_MATTER', 'Täpne bait mitmel teemal'), ('EXCEL_ONENOTE_EXACT', "Exceli ja OneNote'i täpne ühilduvus"), ('STRICT_MULTI_SIGNAL', 'Mitu sõltumatut täpset signaali'), ('CONTENT_MULTI_SIGNAL', 'Sisust mitu täpset signaali'), ('REVIEW_REQUIRED', 'Vajab ülevaatust'), ('CONFLICT', 'Vastuolu'), ('UNMATCHED', 'Sidumata')], db_index=True, max_length=32, verbose_name='sidumise klass'),
        ),
        migrations.AlterField(
            model_name='opinionmatchcandidate',
            name='signals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('EXACT_BINARY_ONENOTE', "Täpne bait OneNote'i lehel"), ('EXACT_ONENOTE_PAGE', 'Leht on registriga täpselt seotud'), ('EXACT_KODADASH_SOURCE_FILE', 'KodaDashi lähtefaili SHA-256'), ('EXACT_SENT_DATE', 'Sama väljasaatmise kuupäev'), ('EXACT_RECIPIENT', 'Sama adressaat'), ('EXACT_LAW_REFERENCE', 'Sama õigusakti viide'), ('EXACT_TITLE_TOKEN', 'Sama eristav pealkirjasõna'), ('SENT_DATE_WITHIN_ONE_DAY', 'Kuupäev erineb ühe päeva'), ('RELATED_KODA_NEWS_SUPPORT', 'KodaDashi uudiselink toetab'), ('POLICY_THREAD_SUPPORT', 'KodaDashi teemalõng toetab'), ('CONTENT_EXACT_LAW_REFERENCE', 'Sisus sama õigusakti viide'), ('CONTENT_EXACT_ADDRESSEE', 'Sisus sama adressaat'), ('CONTENT_EXACT_DATE', 'Sisus sama kuupäev')], max_length=40), blank=True, default=list, size=None, verbose_name='signaalid'),
        ),
        migrations.AlterField(
            model_name='opinionsubmissionimport',
            name='match_class',
            field=models.CharField(choices=[('EXACT_BINARY_MATTER', 'Täpne bait ühel teemal'), ('EXACT_BINARY_MULTI_MATTER', 'Täpne bait mitmel teemal'), ('EXCEL_ONENOTE_EXACT', "Exceli ja OneNote'i täpne ühilduvus"), ('STRICT_MULTI_SIGNAL', 'Mitu sõltumatut täpset signaali'), ('CONTENT_MULTI_SIGNAL', 'Sisust mitu täpset signaali'), ('REVIEW_REQUIRED', 'Vajab ülevaatust'), ('CONFLICT', 'Vastuolu'), ('UNMATCHED', 'Sidumata')], max_length=32, verbose_name='sidumise klass'),
        ),
    ]
