# Generated by Django 5.2.17 on 2026-08-22 17:24
#
# Schema only, and deliberately no data migration.
#
# The obvious backfill would be
# `opinion_sent_recorded = opinion_sent_date IS NOT NULL`, and it is exactly the
# bug this field exists to fix: fourteen current rows in the approved snapshot
# hold a VÄLJA value the date parser cannot read, and that rule would mark every
# one of them as unsent all over again. The raw cell lives on the immutable
# MatterSourceReference, not here, so a correct backfill would have to re-read
# each row through its era contract — which is what the rebuild already does.
#
# `CurrentRegisterState` is derived and rebuildable, so the answer is to rebuild
# it rather than to guess. **The field is `False` for every existing row until
# that happens**, so a deployment must rebuild the derived state from the
# approved snapshot *before* the new web container serves traffic, or
# "Arvamusi koostamisel" will read 200 instead of 15. The ordering is written
# out in the pull request and in docs/production-readiness.md.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legacy_import", "0010_opinion_content_signals"),
        ("matters", "0006_policy_area_other"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="currentregisterstate",
            name="legacy_register_drafting",
        ),
        migrations.AddField(
            model_name="currentregisterstate",
            name="opinion_sent_recorded",
            field=models.BooleanField(
                default=False,
                help_text="Kas registris on VÄLJA lahtris märge. Ei sõltu sellest, kas see on kuupäev.",
                verbose_name="VÄLJA märgitud",
            ),
        ),
        migrations.AlterField(
            model_name="currentregisterstate",
            name="opinion_sent_date",
            field=models.DateField(
                blank=True,
                help_text="Parsitud kuupäev, kui lahter on kuupäev. Võib puududa ka siis, kui VÄLJA on märgitud. Ei ole Submission.",
                null=True,
                verbose_name="VÄLJA kuupäevana",
            ),
        ),
        migrations.AddIndex(
            model_name="currentregisterstate",
            index=models.Index(
                fields=["currency", "opinion_sent_recorded"], name="legacy_register_drafting"
            ),
        ),
    ]
