# Generated by Django 5.2.17 on 2026-08-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_import', '0011_current_register_send_recorded'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinionsubmissionimport',
            name='recipient_raw',
            field=models.CharField(blank=True, max_length=400, verbose_name='saaja allikas'),
        ),
    ]
