# Generated by Django 5.2.17 on 2026-08-28 12:59

import app.core.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_import', '0013_current_register_source_facts'),
        ('matters', '0011_matter_successor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterEngagementImport',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('EMAIL_CAMPAIGN', 'Sendsmaily kampaania'), ('PUBLIC_PAGE', 'koda.ee avalik konsultatsioon')], db_index=True, max_length=32, verbose_name='kanal')),
                ('source_key', models.CharField(max_length=1000, verbose_name='allika tunnus')),
                ('mapping_sha256', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ülevaadatud vaste SHA-256')),
                ('created_engagement', models.BooleanField(default=False, verbose_name='loodi siin')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_imports', to='matters.matterengagement', verbose_name='kaasamine')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_engagement_imports', to='matters.matter', verbose_name='teema')),
            ],
            options={
                'verbose_name': 'registri kaasamise import',
                'verbose_name_plural': 'registri kaasamise impordid',
                'ordering': ['matter', 'channel', 'source_key'],
                'constraints': [models.UniqueConstraint(fields=('matter', 'channel', 'source_key'), name='legacy_register_one_engagement_per_source'), models.CheckConstraint(condition=models.Q(('source_key', ''), _negated=True), name='legacy_register_engagement_source_key_required'), models.CheckConstraint(condition=models.Q(('channel__in', ['EMAIL_CAMPAIGN', 'PUBLIC_PAGE'])), name='legacy_register_engagement_channel_vocabulary')],
            },
        ),
    ]
