# Generated by Django 5.2.17 on 2026-09-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_import', '0014_register_engagement_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinionmatchcandidate',
            name='match_class',
            field=models.CharField(choices=[('EXACT_BINARY_MATTER', 'Täpne bait ühel teemal'), ('EXACT_BINARY_MULTI_MATTER', 'Täpne bait mitmel teemal'), ('EXCEL_ONENOTE_EXACT', "Exceli ja OneNote'i täpne ühilduvus"), ('EXACT_LAW_REFERENCE_MATTER', 'Täpne õigusakti viide ühel teemal'), ('STRICT_MULTI_SIGNAL', 'Mitu sõltumatut täpset signaali'), ('CONTENT_MULTI_SIGNAL', 'Sisust mitu täpset signaali'), ('REVIEW_REQUIRED', 'Vajab ülevaatust'), ('CONFLICT', 'Vastuolu'), ('UNMATCHED', 'Sidumata')], db_index=True, max_length=32, verbose_name='sidumise klass'),
        ),
        migrations.AlterField(
            model_name='opinionsubmissionimport',
            name='match_class',
            field=models.CharField(choices=[('EXACT_BINARY_MATTER', 'Täpne bait ühel teemal'), ('EXACT_BINARY_MULTI_MATTER', 'Täpne bait mitmel teemal'), ('EXCEL_ONENOTE_EXACT', "Exceli ja OneNote'i täpne ühilduvus"), ('EXACT_LAW_REFERENCE_MATTER', 'Täpne õigusakti viide ühel teemal'), ('STRICT_MULTI_SIGNAL', 'Mitu sõltumatut täpset signaali'), ('CONTENT_MULTI_SIGNAL', 'Sisust mitu täpset signaali'), ('REVIEW_REQUIRED', 'Vajab ülevaatust'), ('CONFLICT', 'Vastuolu'), ('UNMATCHED', 'Sidumata')], max_length=32, verbose_name='sidumise klass'),
        ),
    ]
