# Generated by Django 5.2.17 on 2026-10-09 03:37

import app.core.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_carry_dormant_working_documents'),
        ('legacy_import', '0015_alter_opinionmatchcandidate_match_class_and_more'),
        ('matters', '0047_website_overview_kind'),
        ('submissions', '0009_opinion_sent_files'),
        ('workflow', '0015_current_register_status_labels'),
    ]

    # docs/adr/0148. **Additive.** One new table for the 2026 Excel pilot's
    # provenance; no existing table or row changes.
    operations = [
        migrations.CreateModel(
            name='ExcelPilotImport',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pilot', models.CharField(db_index=True, max_length=64, verbose_name='piloot')),
                ('pilot_version', models.CharField(max_length=32, verbose_name='piloodi versioon')),
                ('manifest_sha256', models.CharField(db_index=True, max_length=64, verbose_name='manifesti SHA-256')),
                ('workbook_sha256', models.CharField(max_length=64, verbose_name='töövihiku SHA-256')),
                ('source_sheet', models.CharField(max_length=64, verbose_name='leht')),
                ('source_row_number', models.PositiveIntegerField(verbose_name='rida')),
                ('source_reference_label', models.CharField(max_length=32, verbose_name='registri viide')),
                ('selection_group', models.CharField(choices=[('A', 'A — arvamus koostamisel'), ('B', 'B — saadetud arvamus, töö jätkub'), ('C', 'C — lõpetatud või mujal jätkuv')], max_length=1, verbose_name='valikugrupp')),
                ('selection_reason', models.TextField(blank=True, verbose_name='valiku põhjus')),
                ('work_status', models.CharField(max_length=16, verbose_name='töö olek importimisel')),
                ('interpretation', models.JSONField(blank=True, default=dict, verbose_name='tõlgendus')),
                ('follow_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilot_imports', to='workflow.opinionfollowup', verbose_name='järelkontroll')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_imports', to='matters.matter', verbose_name='teema')),
                ('placeholder_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilot_placeholder', to='documents.documentversion', verbose_name='asendusdokument')),
                ('source_reference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_import', to='legacy_import.mattersourcereference', verbose_name='allikaviide')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilot_imports', to='submissions.submission', verbose_name='imporditud arvamus')),
            ],
            options={
                'verbose_name': 'Exceli pilootimpordi kirje',
                'verbose_name_plural': 'Exceli pilootimpordi kirjed',
                'ordering': ['source_sheet', 'source_row_number'],
                'constraints': [models.UniqueConstraint(fields=('matter',), name='legacy_import_pilot_one_per_matter'), models.UniqueConstraint(fields=('pilot', 'source_reference_label'), name='legacy_import_pilot_reference_once'), models.CheckConstraint(condition=models.Q(('selection_group__in', ['A', 'B', 'C'])), name='legacy_import_pilot_group_vocabulary')],
            },
        ),
    ]
