# Generated by Django 5.2.17 on 2026-09-05 05:57

import app.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legacy_import', '0015_alter_opinionmatchcandidate_match_class_and_more'),
        ('matters', '0013_matter_assignment_notice'),
        ('submissions', '0006_document_reparent_evidence_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatterBackgroundMaterial',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_at', models.DateTimeField(verbose_name='lisatud')),
                ('note', models.TextField(blank=True, verbose_name='märkus')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='background_materials_added', to=settings.AUTH_USER_MODEL, verbose_name='lisas')),
                ('archive_binary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='background_uses', to='legacy_import.opinionarchivebinary', verbose_name='arhiivikiri')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_materials', to='matters.matter', verbose_name='teema')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_uses', to='submissions.submission', verbose_name='arvamus')),
            ],
            options={
                'verbose_name': 'taustmaterjal',
                'verbose_name_plural': 'taustmaterjalid',
                'ordering': ['-added_at', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('archive_binary__isnull', True), ('submission__isnull', False)), models.Q(('archive_binary__isnull', False), ('submission__isnull', True)), _connector='OR'), name='related_background_has_exactly_one_source'), models.UniqueConstraint(condition=models.Q(('submission__isnull', False)), fields=('matter', 'submission'), name='related_one_background_per_submission'), models.UniqueConstraint(condition=models.Q(('archive_binary__isnull', False)), fields=('matter', 'archive_binary'), name='related_one_background_per_archive_binary')],
            },
        ),
        migrations.CreateModel(
            name='MatterRelation',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_at', models.DateTimeField(verbose_name='seotud')),
                ('note', models.TextField(blank=True, verbose_name='märkus')),
                ('linked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matter_relations_made', to=settings.AUTH_USER_MODEL, verbose_name='sidus')),
                ('matter_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_first', to='matters.matter', verbose_name='teema A')),
                ('matter_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_second', to='matters.matter', verbose_name='teema B')),
            ],
            options={
                'verbose_name': 'seotud teema',
                'verbose_name_plural': 'seotud teemad',
                'ordering': ['-linked_at', 'pk'],
                'indexes': [models.Index(fields=['matter_b'], name='related_relation_by_second')],
                'constraints': [models.CheckConstraint(condition=models.Q(('matter_a__lt', models.F('matter_b'))), name='related_relation_pair_is_canonical'), models.UniqueConstraint(fields=('matter_a', 'matter_b'), name='related_one_relation_per_pair')],
            },
        ),
        migrations.CreateModel(
            name='RelatedSuggestionDismissal',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dismissed_at', models.DateTimeField(verbose_name='peidetud')),
                ('candidate_archive_binary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_as_background_candidate', to='legacy_import.opinionarchivebinary', verbose_name='kandidaatarhiivikiri')),
                ('candidate_matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_as_related_candidate', to='matters.matter', verbose_name='kandidaatteema')),
                ('candidate_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_as_background_candidate', to='submissions.submission', verbose_name='kandidaatarvamus')),
                ('dismissed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_suggestions_dismissed', to=settings.AUTH_USER_MODEL, verbose_name='peitis')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_suggestion_dismissals', to='matters.matter', verbose_name='teema')),
            ],
            options={
                'verbose_name': 'peidetud soovitus',
                'verbose_name_plural': 'peidetud soovitused',
                'ordering': ['-dismissed_at', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('candidate_archive_binary__isnull', True), ('candidate_matter__isnull', False), ('candidate_submission__isnull', True)), models.Q(('candidate_archive_binary__isnull', True), ('candidate_matter__isnull', True), ('candidate_submission__isnull', False)), models.Q(('candidate_archive_binary__isnull', False), ('candidate_matter__isnull', True), ('candidate_submission__isnull', True)), _connector='OR'), name='related_dismissal_has_exactly_one_candidate'), models.CheckConstraint(condition=models.Q(('candidate_matter', models.F('matter')), _negated=True), name='related_dismissal_is_not_of_itself'), models.UniqueConstraint(condition=models.Q(('candidate_matter__isnull', False)), fields=('matter', 'candidate_matter'), name='related_one_dismissal_per_candidate_matter'), models.UniqueConstraint(condition=models.Q(('candidate_submission__isnull', False)), fields=('matter', 'candidate_submission'), name='related_one_dismissal_per_candidate_submission'), models.UniqueConstraint(condition=models.Q(('candidate_archive_binary__isnull', False)), fields=('matter', 'candidate_archive_binary'), name='related_one_dismissal_per_candidate_binary')],
            },
        ),
    ]
