# Generated by Django 5.2.17 on 2026-08-18 17:15

import app.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility_override', models.CharField(blank=True, choices=[('NORMAL', 'Tavaline'), ('RESTRICTED', 'Piiratud')], default='', help_text='Tühi tähendab, et nähtavus päritakse teemalt.', max_length=16, verbose_name='nähtavuse kitsendus')),
                ('effective_visibility', models.CharField(choices=[('NORMAL', 'Tavaline'), ('RESTRICTED', 'Piiratud')], db_index=True, default='NORMAL', editable=False, max_length=16, verbose_name='tegelik nähtavus')),
                ('role', models.CharField(choices=[('INCOMING_AUTHORITY', 'Saabunud ametlik dokument'), ('ORIGINAL_EMAIL', 'Algne e-kiri'), ('MEMBER_FEEDBACK', 'Liikme tagasiside'), ('EXTERNAL_POSITION', 'Välise osapoole seisukoht'), ('KODA_SUBMISSION_FINAL', 'Koja väljasaadetud arvamus'), ('OUTCOME_EVIDENCE', 'Tulemuse tõend'), ('WORKING_DOCUMENT', 'Töödokument'), ('OTHER', 'Muu')], db_index=True, default='OTHER', max_length=32, verbose_name='roll')),
                ('title', models.CharField(max_length=400, verbose_name='pealkiri')),
                ('sharepoint_site_id', models.CharField(blank=True, max_length=200)),
                ('sharepoint_drive_id', models.CharField(blank=True, max_length=200)),
                ('sharepoint_item_id', models.CharField(blank=True, max_length=200)),
                ('sharepoint_web_url', models.URLField(blank=True, max_length=1000)),
                ('sharepoint_etag', models.CharField(blank=True, max_length=200)),
                ('sharepoint_observed_at', models.DateTimeField(blank=True, null=True)),
                ('retention_class', models.CharField(choices=[('UNCLASSIFIED', 'Määramata'), ('POLICY_RECORD', 'Poliitikakirje'), ('RAW_EMAIL', 'Algne e-kiri'), ('MEMBER_CONFIDENTIAL', 'Liikme konfidentsiaalne materjal')], default='UNCLASSIFIED', max_length=32, verbose_name='säilitusklass')),
                ('legal_hold', models.BooleanField(default=False, verbose_name='õiguslik säilituskohustus')),
                ('legal_hold_reason', models.TextField(blank=True, verbose_name='säilituskohustuse põhjus')),
                ('legal_hold_set_at', models.DateTimeField(blank=True, null=True)),
                ('provenance_note', models.TextField(blank=True, verbose_name='päritolu märkus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('legal_hold_set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legal_holds_set', to=settings.AUTH_USER_MODEL)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='matters.matter', verbose_name='teema')),
            ],
            options={
                'verbose_name': 'dokument',
                'verbose_name_plural': 'dokumendid',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField(verbose_name='versioon')),
                ('storage_key', models.CharField(max_length=500, verbose_name='hoidla võti')),
                ('original_filename', models.CharField(max_length=400, verbose_name='algne failinimi')),
                ('mime_type', models.CharField(max_length=200, verbose_name='MIME tüüp')),
                ('size_bytes', models.BigIntegerField(verbose_name='suurus baitides')),
                ('sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256')),
                ('acquired_at', models.DateTimeField(verbose_name='saadi')),
                ('source_path', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('source_identifier', models.CharField(blank=True, max_length=400)),
                ('sharepoint_item_version', models.CharField(blank=True, max_length=200)),
                ('malware_scan_state', models.CharField(choices=[('PENDING', 'Ootel'), ('CLEAN', 'Puhas'), ('INFECTED', 'Nakatunud'), ('QUARANTINED', 'Karantiinis'), ('SKIPPED', 'Vahele jäetud'), ('ERROR', 'Viga')], default='PENDING', max_length=32, verbose_name='pahavarakontroll')),
                ('extraction_state', models.CharField(choices=[('PENDING', 'Ootel'), ('DONE', 'Tehtud'), ('FAILED', 'Ebaõnnestus'), ('NOT_APPLICABLE', 'Ei kohaldu')], default='PENDING', max_length=32, verbose_name='teksti eraldamine')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='documents.document', verbose_name='dokument')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_document_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dokumendi versioon',
                'verbose_name_plural': 'dokumendi versioonid',
                'ordering': ['document', 'version_number'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentversion', verbose_name='kehtiv tõendiversioon'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='documents_unique_version_per_document'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-f]{64}$')), name='documents_sha256_is_lowercase_hex'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gte', 0)), name='documents_size_not_negative'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['matter', 'role'], name='documents_matter_role'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('effective_visibility', 'NORMAL'), ('visibility_override', 'RESTRICTED'), _negated=True), name='documents_document_effective_not_weaker_than_override'),
        ),
    ]
