# Generated by Django 5.2.17 on 2026-08-19 13:00

import app.core.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_visibility_override_vocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='extraction_claimed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='töötlemine algas'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='extraction_note',
            field=models.CharField(blank=True, max_length=300, verbose_name='eraldamise märkus'),
        ),
        migrations.AlterField(
            model_name='document',
            name='role',
            field=models.CharField(choices=[('INCOMING_AUTHORITY', 'Saabunud ametlik dokument'), ('ORIGINAL_EMAIL', 'Algne e-kiri'), ('MEMBER_FEEDBACK', 'Liikme tagasiside'), ('EXTERNAL_POSITION', 'Välise osapoole seisukoht'), ('KODA_SUBMISSION_FINAL', 'Koja väljasaadetud arvamus'), ('EMAIL_ATTACHMENT', 'E-kirja manus'), ('OUTCOME_EVIDENCE', 'Tulemuse tõend'), ('WORKING_DOCUMENT', 'Töödokument'), ('OTHER', 'Muu')], db_index=True, default='OTHER', max_length=32, verbose_name='roll'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='extraction_state',
            field=models.CharField(choices=[('PENDING', 'Ootel'), ('PROCESSING', 'Töötlemisel'), ('DONE', 'Tehtud'), ('FAILED', 'Ebaõnnestus'), ('NOT_APPLICABLE', 'Ei kohaldu')], db_index=True, default='PENDING', max_length=32, verbose_name='teksti eraldamine'),
        ),
        migrations.CreateModel(
            name='DocumentDerivative',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('EXTRACTED_TEXT', 'Eraldatud tekst'), ('OCR_TEXT', 'OCR tekst'), ('SAFE_PREVIEW', 'Turvaline eelvaade'), ('THUMBNAIL', 'Pisipilt'), ('EMAIL_METADATA', 'E-kirja metaandmed')], db_index=True, max_length=32, verbose_name='tuletise liik')),
                ('generator', models.CharField(max_length=64, verbose_name='tuletaja')),
                ('generator_version', models.CharField(max_length=64, verbose_name='tuletaja versioon')),
                ('status', models.CharField(choices=[('BUILDING', 'Koostamisel'), ('ACTIVE', 'Kehtiv'), ('SUPERSEDED', 'Asendatud'), ('FAILED', 'Ebaõnnestus')], db_index=True, default='BUILDING', max_length=16, verbose_name='olek')),
                ('content_sha256', models.CharField(blank=True, max_length=64, verbose_name='sisu SHA-256')),
                ('storage_key', models.CharField(blank=True, max_length=500, verbose_name='hoidla võti')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Parseri struktuuritulemus: e-kirja päised, lehekülgede arv, OCR-i osakaal.', verbose_name='metaandmed')),
                ('error_code', models.CharField(blank=True, max_length=64, verbose_name='vea kood')),
                ('error_detail', models.TextField(blank=True, help_text='Operaatorile loetav põhjus. Ei sisalda dokumendi sisu.', verbose_name='vea kirjeldus')),
                ('character_count', models.PositiveIntegerField(default=0, verbose_name='märkide arv')),
                ('fragment_count', models.PositiveIntegerField(default=0, verbose_name='fragmentide arv')),
                ('built_at', models.DateTimeField(blank=True, null=True, verbose_name='valmis')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivatives', to='documents.documentversion', verbose_name='tõendiversioon')),
            ],
            options={
                'verbose_name': 'dokumendi tuletis',
                'verbose_name_plural': 'dokumendi tuletised',
                'ordering': ['version', 'kind', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTextFragment',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordinal', models.PositiveIntegerField(verbose_name='järjekord')),
                ('text', models.TextField(verbose_name='tekst')),
                ('text_source', models.CharField(choices=[('NATIVE', 'Dokumendi oma tekst'), ('OCR', 'OCR')], default='NATIVE', max_length=16, verbose_name='teksti päritolu')),
                ('locator_kind', models.CharField(choices=[('PAGE', 'Lehekülg'), ('SLIDE', 'Slaid'), ('SHEET', 'Tööleht'), ('SECTION', 'Osa'), ('LINE_RANGE', 'Read'), ('BODY', 'Sisu'), ('NONE', 'Määramata')], default='NONE', max_length=16, verbose_name='asukoha liik')),
                ('locator', models.JSONField(blank=True, default=dict, help_text='Struktuurne asukoht, näiteks lehekülje number või töölehe nimi.', verbose_name='asukoht')),
                ('locator_label', models.CharField(blank=True, help_text='Eestikeelne kuju, mida otsingutulemus näitab.', max_length=200, verbose_name='asukoha nimetus')),
                ('character_count', models.PositiveIntegerField(default=0, verbose_name='märkide arv')),
                ('derivative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='documents.documentderivative', verbose_name='tuletis')),
            ],
            options={
                'verbose_name': 'dokumendi tekstiosa',
                'verbose_name_plural': 'dokumendi tekstiosad',
                'ordering': ['derivative', 'ordinal'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachmentLink',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordinal', models.PositiveIntegerField(verbose_name='järjekord')),
                ('declared_filename', models.CharField(max_length=400, verbose_name='manuse nimi kirjas')),
                ('content_id', models.CharField(blank=True, max_length=200, verbose_name='content-id')),
                ('disposition', models.CharField(choices=[('ATTACHMENT', 'Manus'), ('INLINE', 'Sisene ressurss')], default='ATTACHMENT', max_length=16, verbose_name='liik')),
                ('attachment_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='email_origin', to='documents.documentversion', verbose_name='manuse versioon')),
                ('parent_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_attachments', to='documents.documentversion', verbose_name='e-kirja versioon')),
            ],
            options={
                'verbose_name': 'e-kirja manuse seos',
                'verbose_name_plural': 'e-kirja manuste seosed',
                'ordering': ['parent_version', 'ordinal'],
            },
        ),
        migrations.AddIndex(
            model_name='documentderivative',
            index=models.Index(fields=['version', 'kind', 'status'], name='documents_derivative_lookup'),
        ),
        migrations.AddConstraint(
            model_name='documentderivative',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('version', 'kind'), name='documents_one_active_derivative_per_kind'),
        ),
        migrations.AddIndex(
            model_name='documenttextfragment',
            index=models.Index(fields=['derivative', 'ordinal'], name='documents_fragment_order'),
        ),
        migrations.AddConstraint(
            model_name='documenttextfragment',
            constraint=models.UniqueConstraint(fields=('derivative', 'ordinal'), name='documents_unique_fragment_ordinal'),
        ),
        migrations.AddConstraint(
            model_name='emailattachmentlink',
            constraint=models.UniqueConstraint(fields=('parent_version', 'ordinal'), name='documents_unique_attachment_ordinal'),
        ),
    ]
