# Generated by Django 5.2.17 on 2026-08-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_derivatives_and_email_provenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='role',
            field=models.CharField(choices=[('INCOMING_AUTHORITY', 'Saabunud ametlik dokument'), ('ORIGINAL_EMAIL', 'Algne e-kiri'), ('MEMBER_FEEDBACK', 'Liikme tagasiside'), ('EXTERNAL_POSITION', 'Välise osapoole seisukoht'), ('KODA_SUBMISSION_FINAL', 'Koja väljasaadetud arvamus'), ('EMAIL_ATTACHMENT', 'E-kirja manus'), ('LEGACY_MATERIAL', 'Ajalooline materjal'), ('OUTCOME_EVIDENCE', 'Tulemuse tõend'), ('WORKING_DOCUMENT', 'Töödokument'), ('OTHER', 'Muu')], db_index=True, default='OTHER', max_length=32, verbose_name='roll'),
        ),
    ]
