# Generated by Django 5.2.17 on 2026-09-11 13:04

import app.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_documentversion_extraction_state'),
        ('intelligence', '0001_initial'),
        ('matters', '0017_engagement_meeting_and_response_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='sidus')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='documents.document', verbose_name='dokument')),
                ('effective_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='intelligence.mattereffectivedate', verbose_name='jõustumine')),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='matters.matterengagement', verbose_name='kaasamine')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='matters.entry', verbose_name='sissekanne')),
                ('important_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='intelligence.matterimportantdate', verbose_name='oluline tähtaeg')),
                ('work_victory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='intelligence.matterworkvictory', verbose_name='töövõit')),
            ],
            options={
                'verbose_name': 'dokumendi seos',
                'verbose_name_plural': 'dokumendi seosed',
                'ordering': ['created_at', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('entry__isnull', False), ('engagement__isnull', True), ('important_date__isnull', True), ('effective_date__isnull', True), ('work_victory__isnull', True)), models.Q(('engagement__isnull', False), ('entry__isnull', True), ('important_date__isnull', True), ('effective_date__isnull', True), ('work_victory__isnull', True)), models.Q(('important_date__isnull', False), ('entry__isnull', True), ('engagement__isnull', True), ('effective_date__isnull', True), ('work_victory__isnull', True)), models.Q(('effective_date__isnull', False), ('entry__isnull', True), ('engagement__isnull', True), ('important_date__isnull', True), ('work_victory__isnull', True)), models.Q(('work_victory__isnull', False), ('entry__isnull', True), ('engagement__isnull', True), ('important_date__isnull', True), ('effective_date__isnull', True)), _connector='OR'), name='documents_link_has_exactly_one_record'), models.UniqueConstraint(condition=models.Q(('entry__isnull', False)), fields=('document', 'entry'), name='documents_one_link_per_entry'), models.UniqueConstraint(condition=models.Q(('engagement__isnull', False)), fields=('document', 'engagement'), name='documents_one_link_per_engagement'), models.UniqueConstraint(condition=models.Q(('important_date__isnull', False)), fields=('document', 'important_date'), name='documents_one_link_per_important_date'), models.UniqueConstraint(condition=models.Q(('effective_date__isnull', False)), fields=('document', 'effective_date'), name='documents_one_link_per_effective_date'), models.UniqueConstraint(condition=models.Q(('work_victory__isnull', False)), fields=('document', 'work_victory'), name='documents_one_link_per_work_victory')],
            },
        ),
    ]
