# Generated by Django 5.2.17 on 2026-09-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_document_record_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="sharepoint_web_url",
            field=models.URLField(blank=True, max_length=4096),
        ),
    ]
