"""`removed_at` / `removed_by` on `Document` — a mistaken upload can leave the Matter.

docs/adr/0120 (UQ-12) extends ADR 0102's removal to the file itself. Two
nullable columns, the pair `RemovableRecord` already puts on eight business
records; every existing row is `NULL`, which reads as «still on the file», which
is what every existing document is. No backfill, no `RunPython`, no `RunSQL`,
and nothing about `DocumentVersion` changes: its bytes, checksums and immutability
trigger are untouched, and a removed document keeps every version it had.

Additive and rolling-safe: the running image never reads the columns, and a
`NULL` in them is exactly what it would have written.
"""

# Generated by Django 5.2.17 on 2026-09-29 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0011_procedural_development"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="removed_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Täidetud, kui kirje on aktiivsest teema käigust eemaldatud.",
                null=True,
                verbose_name="eemaldatud",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="eemaldaja",
            ),
        ),
    ]
