# Generated by Django 5.2.17 on 2026-08-18 17:15

import app.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyArea',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=64, unique=True, verbose_name='võti')),
                ('name_et', models.CharField(max_length=200, verbose_name='nimi')),
                ('description', models.TextField(blank=True, verbose_name='kirjeldus')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktiivne')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='järjekord')),
            ],
            options={
                'verbose_name': 'valdkond',
                'verbose_name_plural': 'valdkonnad',
                'ordering': ['sort_order', 'name_et'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=64, unique=True, verbose_name='võti')),
                ('name_et', models.CharField(max_length=200, verbose_name='nimi')),
                ('definition', models.TextField(blank=True, help_text='Millal seda silti kasutada ja millal mitte.', verbose_name='tähendus')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktiivne')),
                ('deprecated_at', models.DateTimeField(blank=True, null=True, verbose_name='aegunud')),
                ('merged_into', models.ForeignKey(blank=True, help_text='Aegunud silt jääb otsitavaks kanoonilise sildi kaudu.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_from', to='taxonomy.tag', verbose_name='liidetud sildiga')),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tags', to=settings.AUTH_USER_MODEL, verbose_name='haldaja')),
            ],
            options={
                'verbose_name': 'silt',
                'verbose_name_plural': 'sildid',
                'ordering': ['name_et'],
            },
        ),
        migrations.CreateModel(
            name='TagAlias',
            fields=[
                ('id', models.UUIDField(default=app.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=200, verbose_name='nimekuju')),
                ('normalized_alias', models.CharField(db_index=True, editable=False, max_length=200)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='taxonomy.tag', verbose_name='silt')),
            ],
            options={
                'verbose_name': 'sildi nimekuju',
                'verbose_name_plural': 'sildi nimekujud',
                'ordering': ['alias'],
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(condition=models.Q(('merged_into', models.F('id')), _negated=True), name='taxonomy_tag_not_merged_into_itself'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(condition=models.Q(('merged_into__isnull', True), ('is_active', False), _connector='OR'), name='taxonomy_tag_merged_is_inactive'),
        ),
        migrations.AddConstraint(
            model_name='tagalias',
            constraint=models.UniqueConstraint(fields=('tag', 'normalized_alias'), name='taxonomy_unique_alias_per_tag'),
        ),
    ]
